import test from 'node:test';
import assert from 'node:assert/strict';
import { assertAttendanceTransition, attendancePermission, buildWorkingDays, canTransitionAttendance, dateInTimezone, isEnrollmentEligible, percentage, statusWeight, summarizeAttendance } from '../src/services/attendance.service.js';
import { assertSameSchool } from '../src/utils/teacherAuthorization.util.js';

const date = (value) => new Date(`${value}T00:00:00.000Z`);
const row = (attendanceDate, status, attendanceUnits) => ({ attendanceDate: date(attendanceDate), status, attendanceUnits });

test('attendance percentage uses attendance units and eligible working days', () => assert.equal(percentage(17.5, 20), 87.5));
test('percentage is not calculated when there are no eligible working days', () => assert.equal(percentage(0, 0), null));
test('half-day calculation is centralized and configurable', () => { assert.equal(statusWeight('HALF_DAY'), .5); assert.equal(statusWeight('HALF_DAY', { halfDayWeight: .25 }), .25); });
test('weekly offs and holidays are excluded from working days', () => { const days=buildWorkingDays({start:date('2026-07-01'),end:date('2026-07-08'),weeklyOffDays:[0],calendarDays:[{calendarDate:date('2026-07-03'),dayType:'HOLIDAY',isFullDay:true}]});assert.equal(days.filter(day=>day.isWorkingDay).length,5);assert.equal(days.find(day=>day.date==='2026-07-03').isWorkingDay,false); });
test('special working day overrides a weekly off', () => { const days=buildWorkingDays({start:date('2026-07-05'),end:date('2026-07-06'),weeklyOffDays:[0],overrides:[{calendarDate:date('2026-07-05'),isWorkingDay:true,eligibleDayWeight:.5}]});assert.deepEqual(days[0],{date:'2026-07-05',isWorkingDay:true,weight:.5,dayType:'WORKING_DAY',title:null}); });
test('new admission excludes days before effective joining date', () => { const days=buildWorkingDays({start:date('2026-07-01'),end:date('2026-07-06'),weeklyOffDays:[]});const result=summarizeAttendance({rows:[row('2026-07-03','PRESENT',1),row('2026-07-04','PRESENT',1),row('2026-07-05','ABSENT',0)],workingDays:days,enrollment:{effectiveFrom:date('2026-07-03')}});assert.equal(result.eligibleWorkingDays,3);assert.equal(result.percentage,66.7); });
test('withdrawal excludes days after effective exit date', () => { const days=buildWorkingDays({start:date('2026-07-01'),end:date('2026-07-06'),weeklyOffDays:[]});const result=summarizeAttendance({rows:[row('2026-07-01','PRESENT',1),row('2026-07-02','ABSENT',0),row('2026-07-03','PRESENT',1)],workingDays:days,enrollment:{effectiveTo:date('2026-07-03')}});assert.equal(result.eligibleWorkingDays,3);assert.equal(result.percentage,66.7); });
test('missing attendance stays visible and does not silently become present', () => { const days=buildWorkingDays({start:date('2026-07-01'),end:date('2026-07-04'),weeklyOffDays:[]});const result=summarizeAttendance({rows:[row('2026-07-01','PRESENT',1)],workingDays:days});assert.equal(result.missingDays,2);assert.equal(result.counts.NOT_MARKED,2);assert.equal(result.percentage,33.3); });
test('custom status definitions drive units without UI hard-coding', () => { const definitions=[{code:'SPORTS_DUTY',attendanceWeight:.75}];assert.equal(statusWeight('SPORTS_DUTY',{},definitions),.75); });
test('class teachers can mark students but cannot approve or lock', () => { assert.equal(attendancePermission('TEACHER','markStudent'),true);assert.equal(attendancePermission('TEACHER','approve'),false);assert.equal(attendancePermission('TEACHER','lock'),false); });
test('HR can manage employees and corrections without student marking rights', () => { assert.equal(attendancePermission('HR','markEmployee'),true);assert.equal(attendancePermission('HR','approve'),true);assert.equal(attendancePermission('HR','markStudent'),false); });
test('student and parent roles are view-only', () => { for(const role of ['STUDENT','PARENT']){assert.equal(attendancePermission(role,'viewOwn'),true);assert.equal(attendancePermission(role,'markStudent'),false);assert.equal(attendancePermission(role,'export'),false);} });
test('school owner attendance administration is view-only by default', () => { assert.equal(attendancePermission('SCHOOL_OWNER','audit'),true); assert.equal(attendancePermission('SCHOOL_OWNER','export'),true); assert.equal(attendancePermission('SCHOOL_OWNER','markStudent'),false); assert.equal(attendancePermission('SCHOOL_OWNER','approve'),false); assert.equal(attendancePermission('SCHOOL_OWNER','lock'),false); });
test('submitted attendance cannot return to draft', () => { assert.equal(canTransitionAttendance('DRAFT','LOCKED'),true); assert.equal(canTransitionAttendance('LOCKED','CORRECTED'),true); assert.equal(canTransitionAttendance('CORRECTED','CORRECTED'),true); assert.equal(canTransitionAttendance('LOCKED','DRAFT'),false); assert.throws(() => assertAttendanceTransition('LOCKED','DRAFT'),/cannot transition/); });
test('tenant isolation rejects cross-school access', () => assert.throws(() => assertSameSchool({role:'ADMIN',schoolId:'school-a'},'school-b'),/another school's data/));
test('session cumulative summary is derived from source records', () => { const days=buildWorkingDays({start:date('2026-04-01'),end:date('2026-04-05'),weeklyOffDays:[]});const result=summarizeAttendance({rows:[row('2026-04-01','PRESENT',1),row('2026-04-02','HALF_DAY',.5),row('2026-04-03','ABSENT',0),row('2026-04-04','PRESENT',1)],workingDays:days});assert.equal(result.attendanceUnits,2.5);assert.equal(result.percentage,62.5); });
test('enrollment boundaries include the joining and exit dates', () => { const enrollment={effectiveFrom:date('2026-07-10'),effectiveTo:date('2026-07-20')};assert.equal(isEnrollmentEligible('2026-07-09',enrollment),false);assert.equal(isEnrollmentEligible('2026-07-10',enrollment),true);assert.equal(isEnrollmentEligible('2026-07-20',enrollment),true);assert.equal(isEnrollmentEligible('2026-07-21',enrollment),false); });
test('school timezone controls the current attendance date', () => assert.equal(dateInTimezone(new Date('2026-07-21T19:30:00Z'),'Asia/Kolkata').toISOString().slice(0,10),'2026-07-22'));
