import React, { lazy } from 'react';

export const LoginPage = lazy(() => import('../pages/LoginPage'));
export const StudentLoginPage = lazy(() => import('../pages/StudentLoginPage'));
export const PlatformOwnerDashboard = lazy(() => import('../pages/dashboards/PlatformOwnerDashboard'));
export const SchoolOwnerDashboard = lazy(() => import('../pages/dashboards/SchoolOwnerDashboard'));
export const AdminDashboard = lazy(() => import('../pages/dashboards/AdminDashboard'));
export const TeacherDashboard = lazy(() => import('../pages/dashboards/TeacherDashboard'));
export const TeacherAssignmentsPage = lazy(() => import('../pages/teacher/TeacherPortalPages').then(m=>({default:m.AssignmentsPage})));
export const TeacherAssignmentDetailPage = lazy(() => import('../pages/teacher/TeacherPortalPages').then(m=>({default:m.AssignmentPage})));
export const TeacherChapterPage = lazy(() => import('../pages/teacher/TeacherPortalPages').then(m=>({default:m.TeacherChapterPage})));
export const TeacherAssignmentStudentsPage = lazy(() => import('../pages/teacher/TeacherPortalPages').then(m=>({default:m.AssignmentStudentsPage})));
export const TeacherStudentPerformancePage = lazy(() => import('../pages/teacher/TeacherPortalPages').then(m=>({default:m.TeacherStudentPage})));
export const TeacherPollsPage = lazy(() => import('../pages/teacher/TeacherPollListPage'));
export const TeacherPollPage = lazy(() => import('../pages/teacher/TeacherWholeClassRatingPage'));
export const TeacherPerformancePage = lazy(() => import('../pages/teacher/TeacherPortalPages').then(m=>({default:m.TeacherPerformancePage})));
export const TeacherMyClassPage = lazy(() => import('../pages/teacher/TeacherPortalPages').then(m=>({default:m.MyClassPage})));
export const ParentDashboard = lazy(() => import('../pages/dashboards/ParentDashboard'));
export const StudentDashboard = lazy(() => import('../pages/dashboards/StudentDashboard'));
export const StudentSubjectsPage = lazy(() => import('../pages/student/StudentPortalPages').then(m => ({ default: m.SubjectsPage })));
export const StudentSubjectPage = lazy(() => import('../pages/student/StudentPortalPages').then(m => ({ default: m.SubjectPage })));
export const StudentChapterPage = lazy(() => import('../pages/student/StudentPortalPages').then(m => ({ default: m.ChapterPage })));
export const StudentAttendanceSummaryPage = lazy(() => import('../pages/student/StudentPortalPages').then(m => ({ default: m.AttendancePage })));
export const StudentAttendanceMonthPage = lazy(() => import('../pages/student/StudentPortalPages').then(m => ({ default: m.AttendanceMonthPage })));
export const StudentPendingPollsPage = lazy(() => import('../pages/student/StudentPortalPages').then(m => ({ default: () => <m.PollsPage /> })));
export const StudentSubmittedPollsPage = lazy(() => import('../pages/student/StudentPortalPages').then(m => ({ default: () => <m.PollsPage submitted /> })));
export const StudentPollPage = lazy(() => import('../pages/student/StudentChapterFeedbackPage'));
export const StudentSubmittedPollPage = lazy(() => import('../pages/student/StudentChapterFeedbackPage'));
export const StudentResourcesPage = lazy(() => import('../pages/student/StudentPortalPages').then(m => ({ default: m.ResourcesPage })));
export const StudentPerformancePage = lazy(() => import('../pages/student/StudentPortalPages').then(m => ({ default: m.PerformancePage })));
export const StaffDashboard = lazy(() => import('../pages/dashboards/StaffDashboard'));
export const SchoolManagementPage = lazy(() => import('../pages/platform/SchoolManagementPage'));
export const SchoolSettingsPage = lazy(() => import('../pages/platform/SchoolSettingsPage'));
export const ClassManagementPage = lazy(() => import('../pages/admin/ClassManagementPage'));
export const ClassDetailsDashboardPage = lazy(() => import('../pages/admin/ClassDetailsDashboardPage'));
export const SubjectDetailsDashboardPage = lazy(() => import('../pages/admin/SubjectDetailsDashboardPage'));
export const ChapterComingSoonPage = lazy(() => import('../pages/admin/ChapterComingSoonPage'));

export const SectionManagementPage = lazy(() => import('../pages/admin/SectionManagementPage'));
export const SubjectManagementPage = lazy(() => import('../pages/admin/SubjectManagementPage'));
export const SubjectAssignmentPage = lazy(() => import('../pages/admin/SubjectAssignmentPage'));
export const TeacherManagementPage = lazy(() => import('../pages/admin/TeacherManagementPage'));
export const TeacherAssignmentPage = lazy(() => import('../pages/admin/TeacherAssignmentPage'));
export const ClassTeacherAssignmentPage = lazy(() => import('../pages/admin/ClassTeacherAssignmentPage'));
export const TeacherAssignmentSummaryPage = lazy(() => import('../pages/admin/TeacherAssignmentSummaryPage'));
export const StudentAttendancePage = lazy(() => import('../pages/attendance/StudentAttendancePage'));
export const TeacherAttendancePage = lazy(() => import('../pages/attendance/TeacherAttendancePage'));
export const MyAttendancePage = lazy(() => import('../pages/attendance/MyAttendancePage'));
export const AcademicCalendarPage = lazy(() => import('../pages/attendance/AcademicCalendarPage'));
export const AttendanceDashboardPage = lazy(() => import('../pages/attendance/AttendanceDashboardPage'));
export const MonthlyClassAttendancePage = lazy(() => import('../pages/attendance/MonthlyClassAttendancePage'));
export const StudentAttendanceProfilePage = lazy(() => import('../pages/attendance/StudentAttendanceProfilePage'));
export const EmployeeMonthlyAttendancePage = lazy(() => import('../pages/attendance/EmployeeMonthlyAttendancePage'));
export const AttendanceCorrectionsPage = lazy(() => import('../pages/attendance/AttendanceCorrectionsPage'));
export const AttendanceSettingsPage = lazy(() => import('../pages/attendance/AttendanceSettingsPage'));
export const AttendanceAuditPage = lazy(() => import('../pages/attendance/AttendanceAuditPage'));
export const AttendanceCorrectionRequestPage = lazy(() => import('../pages/attendance/AttendanceCorrectionRequestPage'));
export const WeeklySlotManagementPage = lazy(() => import('../pages/admin/WeeklySlotManagementPage'));
export const TimetableBuilderPage = lazy(() => import('../pages/admin/TimetableBuilderPage'));
export const TimetableReconciliationPage = lazy(() => import('../pages/admin/TimetableReconciliationPage'));
export const GalleryStudioPage = lazy(() => import('../pages/admin/GalleryStudioPage'));
export const AddStudentPage = lazy(() => import('../pages/admin/AddStudentPage'));
export const StudentAllocationPage = lazy(() => import('../pages/admin/StudentAllocationPage'));
export const SchoolDirectoryPage = lazy(() => import('../pages/admin/SchoolDirectoryPage'));
export const GalleryPage = lazy(() => import('../pages/GalleryPage'));
export const PlatformOwnerProfilePage = lazy(() => import('../pages/profile/PlatformOwnerProfilePage'));
export const SchoolOwnerProfilePage = lazy(() => import('../pages/profile/SchoolOwnerProfilePage'));
export const AdminProfilePage = lazy(() => import('../pages/profile/AdminProfilePage'));
export const UserManagementPage = lazy(() => import('../pages/admin/UserManagementPage'));
export const TeacherProfilePage = lazy(() => import('../pages/profile/TeacherProfilePage'));
export const ParentProfilePage = lazy(() => import('../pages/profile/ParentProfilePage'));
export const StudentProfilePage = lazy(() => import('../pages/profile/StudentProfilePage'));
export const StaffProfilePage = lazy(() => import('../pages/profile/StaffProfilePage'));
export const CurriculumManagerProfilePage = lazy(() => import('../pages/profile/CurriculumManagerProfilePage'));
export const WidgetHubPage = lazy(() => import('../pages/widgets/WidgetHubPage'));
export const MyReportsPage = lazy(() => import('../pages/support/MyReportsPage'));
export const IssueManagementPage = lazy(() => import('../pages/platform/IssueManagementPage'));
export const LoginCredentialsPage = lazy(() => import('../pages/admin/LoginCredentialsPage'));
export const AccountRecoveryPage = lazy(() => import('../pages/AccountRecoveryPage'));
export const CurriculumDashboardPage = lazy(() => import('../pages/curriculum/CurriculumDashboardPage'));
export const CurriculumManagePage = lazy(() => import('../pages/curriculum/CurriculumManagePage'));
export const FeePortalPage = lazy(() => import('../pages/fees/FeePortalPage'));
export const FeeManagerProfilePage = lazy(() => import('../pages/profile/FeeManagerProfilePage'));
export const FeeStructureWizardPage = lazy(() => import('../pages/fees/FeeStructureWizardPage'));
export const FeeOperationsPage = lazy(() => import('../pages/fees/FeeOperationsPage'));
export const FeeAdministrationPage = lazy(() => import('../pages/fees/FeeAdministrationPage'));
export const FamilyFeePage = lazy(() => import('../pages/fees/FamilyFeePage'));
export const PlatformFeeAnalyticsPage = lazy(() => import('../pages/fees/PlatformFeeAnalyticsPage'));
export const ReceiptVerificationPage = lazy(() => import('../pages/fees/ReceiptVerificationPage'));
export const TeacherFeePage = lazy(() => import('../pages/fees/TeacherFeePage'));
export const HomeworkWorkspacePage = lazy(() => import('../pages/homework/HomeworkWorkspacePage'));
export const NotificationCenterPage = lazy(() => import('../pages/communication/NotificationCenterPage'));
export const CommunicationWorkspacePage = lazy(() => import('../pages/communication/CommunicationWorkspacePage'));
export const HRWorkspacePage = lazy(() => import('../pages/hr/HRWorkspacePage'));
export const EmployeeSelfServicePage = lazy(() => import('../pages/hr/EmployeeSelfServicePage'));
export const StudentAnalyticsListPage = lazy(() => import('../features/analytics/pages/StudentAnalyticsListPage'));
export const StudentAnalyticsPage = lazy(() => import('../features/analytics/pages/StudentAnalyticsPage'));
export const SubjectAnalyticsPage = lazy(() => import('../features/analytics/pages/SubjectAnalyticsPage'));
export const ChapterAnalyticsPage = lazy(() => import('../features/analytics/pages/ChapterAnalyticsPage'));
export const AnalyticsConfigurationPage = lazy(() => import('../features/analytics/pages/AnalyticsConfigurationPage'));
export const SchoolAnalyticsPage = lazy(() => import('../features/analytics/pages/SchoolAnalyticsPage'));
export const ClassAnalyticsPage = lazy(() => import('../features/analytics/pages/ClassAnalyticsPage'));
export const ExaminationWorkspacePage = lazy(() => import('../pages/examinations/ExaminationHubPage'));
export const OfflinePage = lazy(() => import('../pages/OfflinePage'));
export const PermissionDeniedPage = lazy(() => import('../pages/PermissionDeniedPage'));
export const WorkspaceSelectionPage = lazy(() => import('../pages/WorkspaceSelectionPage'));
export const ClassTeacherDashboard = lazy(() => import('../pages/dashboards/ClassTeacherDashboard'));
export const RoleManagementPage = lazy(() => import('../pages/admin/RoleManagementPage'));
export const SessionExpiredPage = lazy(() => import('../pages/SessionExpiredPage'));
