import 'dotenv/config';
const { PrismaClient } = await import('../src/generated/prisma/index.js');
const prisma = new PrismaClient();

const definitions = [
  ['SCHOOL_WELCOME','GENERAL','NORMAL','Welcome to the new academic session','The school community welcomes every family to a productive new session.','PUBLISHED',null],
  ['HOMEWORK_PUBLISHED','HOMEWORK','NORMAL','New mathematics homework','Practice set 4 is available and due this Friday.','PUBLISHED','/homework'],
  ['RESOURCE_PUBLISHED','RESOURCE','NORMAL','Learning resource available','A new chapter revision guide is ready.','PUBLISHED','/homework'],
  ['ATTENDANCE_ABSENT','ATTENDANCE','HIGH','Absence recorded','Attendance was marked absent today. Contact the school if this needs correction.','PUBLISHED','/student/attendance'],
  ['FEE_DUE','FEE','HIGH','Fee installment due','The next fee installment is approaching its due date.','PUBLISHED','/parent/fees'],
  ['PAYMENT_RECEIVED','FEE','NORMAL','Payment received','Your payment was received and the receipt is available.','PUBLISHED','/parent/fees'],
  ['EXAM_TIMETABLE','EXAM','HIGH','Exam timetable published','The term examination timetable is now available.','PUBLISHED','/dashboard/calendar'],
  ['RESULT_PUBLISHED','RESULT','HIGH','Result published','The term result is now available in the student portal.','PUBLISHED','/student/performance'],
  ['HOLIDAY_NOTICE','HOLIDAY','NORMAL','School holiday','The school will remain closed for the regional holiday.','PUBLISHED','/dashboard/calendar'],
  ['EMERGENCY_CLOSURE','EMERGENCY','EMERGENCY','Emergency closure notice','School is closed today due to severe weather. Please acknowledge this alert.','PUBLISHED',null],
  ['SCHEDULED_PTM','EVENT','NORMAL','Parent-teacher meeting','The next parent-teacher meeting schedule will be published soon.','SCHEDULED',null],
  ['EXPIRED_EVENT','EVENT','LOW','Science fair registration','Registration for this event has closed.','EXPIRED',null],
];

const seedSchool = async (school) => {
  const creator = await prisma.user.findFirst({ where: { schoolId: school.id, role: { in: ['ADMIN','SCHOOL_OWNER'] }, isActive: true } });
  if (!creator) return;
  const students = await prisma.student.findMany({ where: { schoolId: school.id, isActive: true }, take: 3 });
  const staff = await prisma.user.findMany({ where: { schoolId: school.id, isActive: true }, take: 3 });
  const recipientRows = [...staff.map((user) => ({ recipientKey: `user:${user.id}`, userId: user.id, role: user.role, studentId: null, parentId: null })), ...students.flatMap((student) => [{ recipientKey: `student:${student.id}`, userId: null, role: 'STUDENT', studentId: student.id, parentId: null }, ...(student.parentUserId ? [{ recipientKey: `parent:${student.parentUserId}`, userId: null, role: 'PARENT', studentId: student.id, parentId: student.parentUserId }] : [])])];
  await prisma.communicationPolicy.upsert({ where: { schoolId: school.id }, create: { schoolId: school.id }, update: {} });
  for (const [code,name,category] of [['ABSENCE_ALERT','Absence alert','ATTENDANCE'],['FEE_DUE','Fee due reminder','FEE'],['HOMEWORK_DUE','Homework due reminder','HOMEWORK'],['EMERGENCY_ALERT','Emergency alert','EMERGENCY']]) await prisma.notificationTemplate.upsert({ where: { schoolId_code_channel: { schoolId: school.id, code, channel: 'IN_APP' } }, create: { schoolId: school.id, code, name, category, channel: 'IN_APP', titleTemplate: name, bodyTemplate: '{{studentName}}: {{schoolName}} has an update for you.', allowedVariables: ['studentName','schoolName'], isSystemTemplate: true, createdByUserId: creator.id }, update: { isActive: true } });
  for (const recipient of recipientRows.slice(0,4)) await prisma.notificationPreference.upsert({ where: { schoolId_recipientKey_category: { schoolId: school.id, recipientKey: recipient.recipientKey, category: 'GENERAL' } }, create: { schoolId: school.id, recipientKey: recipient.recipientKey, userId: recipient.userId, category: 'GENERAL', timezone: 'Asia/Kolkata' }, update: {} });
  for (const [index, [type,category,priority,title,message,status,actionUrl]] of definitions.entries()) {
    const dedupeKey = `DEMO:${type}`; let notification = await prisma.notification.findFirst({ where: { schoolId: school.id, dedupeKey } });
    if (!notification) notification = await prisma.notification.create({ data: { schoolId: school.id, type, category, priority, title, message, actionUrl, actionLabel: actionUrl ? 'Open' : null, sourceModule: category === 'GENERAL' ? 'COMMUNICATION' : category, sourceEntityType: 'DEMO', sourceEntityId: type, createdByUserId: creator.id, createdByRole: creator.role, status, publishedAt: status === 'PUBLISHED' ? new Date(Date.now()-index*3600000) : null, scheduledAt: status === 'SCHEDULED' ? new Date(Date.now()+86400000) : null, expiresAt: status === 'EXPIRED' ? new Date(Date.now()-86400000) : null, requiresAcknowledgement: type === 'EMERGENCY_CLOSURE', isMandatory: type === 'EMERGENCY_CLOSURE', isSystemGenerated: !['SCHOOL_WELCOME','HOLIDAY_NOTICE','EMERGENCY_CLOSURE','SCHEDULED_PTM'].includes(type), dedupeKey, resolvedRecipientCount: status === 'PUBLISHED' ? recipientRows.length : 0, audienceRules: { create: { kind: 'SCHOOL_WIDE' } }, recipients: status === 'PUBLISHED' ? { create: recipientRows.map((recipient, recipientIndex) => ({ schoolId: school.id, recipientKey: recipient.recipientKey, userId: recipient.userId, studentId: recipient.studentId, parentId: recipient.parentId, recipientRole: recipient.role, deliveryContext: 'SCHOOL_WIDE', readAt: index % 3 === 0 && recipientIndex === 0 ? new Date() : null, acknowledgedAt: type === 'EMERGENCY_CLOSURE' && recipientIndex === 0 ? new Date() : null, archivedAt: index === 1 && recipientIndex === 0 ? new Date() : null, deliveries: { create: [{ channel: 'IN_APP', status: 'DELIVERED', provider: 'database', attemptCount: 1, sentAt: new Date(), deliveredAt: new Date() }, ...(index === 4 && recipientIndex === 0 ? [{ channel: 'EMAIL', status: 'FAILED', provider: 'demo-smtp', attemptCount: 3, failedAt: new Date(), failureReason: 'Demo provider unavailable' }] : [])] } })) } : undefined } });
    if (['SCHOOL_WELCOME','HOLIDAY_NOTICE','EMERGENCY_CLOSURE','SCHEDULED_PTM','EXPIRED_EVENT'].includes(type)) { const existing = await prisma.announcement.findFirst({ where: { notificationId: notification.id } }); if (!existing) await prisma.announcement.create({ data: { schoolId: school.id, notificationId: notification.id, title, content: message, category, priority, status, publishAt: notification.publishedAt || notification.scheduledAt, expiresAt: notification.expiresAt, requiresAcknowledgement: type === 'EMERGENCY_CLOSURE', createdByUserId: creator.id } }); }
  }
  const teacher = staff.find((user) => user.role === 'TEACHER') || creator; const portal = recipientRows.find((row) => row.role === 'PARENT') || recipientRows.find((row) => row.role === 'STUDENT');
  if (portal) for (const [subject,type] of [['Parent-teacher academic discussion','PARENT_TEACHER'],['Fee support request','FEE_SUPPORT'],['Academic support','ACADEMIC_SUPPORT']]) { const existing = await prisma.conversation.findFirst({ where: { schoolId: school.id, subject } }); if (!existing) await prisma.conversation.create({ data: { schoolId: school.id, type, subject, studentId: portal.studentId, createdByKey: portal.recipientKey, participants: { create: [{ participantKey: portal.recipientKey, studentId: portal.studentId, role: portal.role, canManage: true }, { participantKey: `user:${type === 'PARENT_TEACHER' ? teacher.id : creator.id}`, userId: type === 'PARENT_TEACHER' ? teacher.id : creator.id, role: type === 'PARENT_TEACHER' ? teacher.role : creator.role, canManage: true }] }, messages: { create: [{ schoolId: school.id, senderKey: portal.recipientKey, senderRole: portal.role, content: type === 'FEE_SUPPORT' ? 'Please help me understand the latest fee statement.' : 'Could we discuss the student’s recent progress?' }] } } }); }
  console.log(`[communication-seed] ${school.schoolName}: ready`);
};

export const seedCommunication = async () => { const schools = await prisma.school.findMany({ where: { status: 'ACTIVE' } }); for (const school of schools) await seedSchool(school); };
export const disconnectCommunicationSeed = () => prisma.$disconnect();
if (process.argv[1]?.endsWith('seedCommunication.js')) seedCommunication().finally(disconnectCommunicationSeed);
