import 'dotenv/config';
import prisma from '../src/config/prisma.client.js';
import { EMPLOYEE_STATUS_DEFAULTS, STUDENT_STATUS_DEFAULTS, statusWeight } from '../src/services/attendance.service.js';

const day = (year, monthIndex, value) => new Date(Date.UTC(year, monthIndex, value));
const monthRange = (date) => ({ start: day(date.getUTCFullYear(), date.getUTCMonth(), 1), end: day(date.getUTCFullYear(), date.getUTCMonth() + 1, 1) });
const dates = (start, end) => { const rows=[]; for(let cursor=start;cursor<end;cursor=new Date(cursor.getTime()+86400000)) rows.push(cursor); return rows; };

async function seedSchool(school) {
  const now = new Date(); const current = monthRange(now); const previous = monthRange(new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth()-1, 1)));
  const session = await prisma.academicSession.findFirst({ where: { schoolId: school.id, startDate: { lte: now }, endDate: { gte: now } }, orderBy: { startDate: 'desc' } });
  const sessionName = session?.name || `${now.getUTCMonth() >= 3 ? now.getUTCFullYear() : now.getUTCFullYear()-1}-${String((now.getUTCMonth() >= 3 ? now.getUTCFullYear()+1 : now.getUTCFullYear())).slice(-2)}`;
  await prisma.attendanceRule.upsert({ where: { schoolId: school.id }, update: {}, create: { schoolId: school.id, timezone: 'Asia/Kolkata', weeklyOffDays: [0], studentMinimumPercentage: 75, employeeMinimumPercentage: 85, parentAbsenceNotifications: true, requiresFinalSubmission: true } });
  const studentCodes = new Set(STUDENT_STATUS_DEFAULTS.map((item) => item.code)); const employeeCodes = new Set(EMPLOYEE_STATUS_DEFAULTS.map((item) => item.code));
  const defaults = [...new Map([...STUDENT_STATUS_DEFAULTS, ...EMPLOYEE_STATUS_DEFAULTS].map((item) => [item.code, item])).values()].map((item) => ({ ...item, audience: studentCodes.has(item.code) && employeeCodes.has(item.code) ? 'BOTH' : studentCodes.has(item.code) ? 'STUDENT' : 'EMPLOYEE' }));
  for (const [index, item] of defaults.entries()) await prisma.attendanceStatusDefinition.upsert({ where: { schoolId_code: { schoolId: school.id, code: item.code } }, update: { audience: item.audience }, create: { schoolId: school.id, code: item.code, displayName: item.displayName, shortLabel: item.shortLabel, countsAsPresent: Boolean(item.countsAsPresent), countsAsAbsent: Boolean(item.countsAsAbsent), attendanceWeight: item.attendanceWeight, affectsSalary: Boolean(item.affectsSalary), requiresApproval: Boolean(item.requiresApproval), requiresRemark: Boolean(item.requiresRemark), excludedFromWork: Boolean(item.excludedFromWork), audience: item.audience, badgeStyle: item.badgeStyle, displayOrder: index } });
  const sections = await prisma.section.findMany({ where: { schoolId: school.id, deletedAt: null }, include: { class: true }, orderBy: [{ class: { classOrder: 'asc' } }, { sectionOrder: 'asc' }], take: 4 });
  const admins = await prisma.user.findMany({ where: { schoolId: school.id, role: 'ADMIN', isActive: true }, take: 1 }); const actor = admins[0];
  const holidays = new Set((await prisma.academicCalendarDay.findMany({ where: { schoolId: school.id, calendarDate: { gte: previous.start, lt: current.end }, dayType: { in: ['HOLIDAY','WEEKLY_OFF','VACATION'] } }, select: { calendarDate: true } })).map(row=>row.calendarDate.toISOString().slice(0,10)));
  for (const [sectionIndex, section] of sections.entries()) {
    const students = await prisma.student.findMany({ where: { schoolId: school.id, className: section.class.className, section: section.sectionName }, orderBy: [{ serialNo: 'asc' }, { studentFirstName: 'asc' }], take: 35 });
    for (const [studentIndex, student] of students.entries()) {
      const joined = sectionIndex === 1 && studentIndex === 0 ? day(current.start.getUTCFullYear(), current.start.getUTCMonth(), 16) : studentIndex === students.length-1 ? day(current.start.getUTCFullYear(), current.start.getUTCMonth(), 12) : (student.admissionDate || session?.startDate || previous.start);
      const enrollment = await prisma.studentEnrollmentHistory.upsert({ where: { schoolId_studentId_classId_sectionId_effectiveFrom: { schoolId: school.id, studentId: student.id, classId: section.classId, sectionId: section.id, effectiveFrom: new Date(Date.UTC(joined.getUTCFullYear(), joined.getUTCMonth(), joined.getUTCDate())) } }, update: {}, create: { schoolId: school.id, studentId: student.id, academicSession: sessionName, classId: section.classId, sectionId: section.id, effectiveFrom: new Date(Date.UTC(joined.getUTCFullYear(), joined.getUTCMonth(), joined.getUTCDate())) } });
      for (const date of [...dates(previous.start, previous.end), ...dates(current.start, new Date(Math.min(current.end.getTime(), day(now.getUTCFullYear(),now.getUTCMonth(),now.getUTCDate()+1).getTime())))]) {
        const key=date.toISOString().slice(0,10); if(date.getUTCDay()===0||holidays.has(key)||date<enrollment.effectiveFrom) continue;
        let status='PRESENT'; if(studentIndex===1&&date.getUTCDate()%4===0)status='ABSENT'; else if(studentIndex===2&&date.getUTCDate()%5===0)status='LATE'; else if(studentIndex===3&&date.getUTCDate()%7===0)status='HALF_DAY'; else if(studentIndex===4&&date.getUTCDate()%9===0)status='APPROVED_LEAVE'; else if(studentIndex===5&&date.getUTCDate()%3===0)status='ABSENT';
        await prisma.studentAttendance.upsert({ where: { schoolId_classId_sectionId_studentId_attendanceDate: { schoolId: school.id, classId: section.classId, sectionId: section.id, studentId: student.id, attendanceDate: date } }, update: {}, create: { schoolId: school.id, classId: section.classId, sectionId: section.id, studentId: student.id, attendanceDate: date, academicSession: sessionName, status, attendanceUnits: statusWeight(status), enrollmentId: enrollment.id, remarks: status==='APPROVED_LEAVE'?'Approved family leave':status==='ABSENT'?'Absent — demo record':null, leaveReference: status==='APPROVED_LEAVE'?`DEMO-LEAVE-${student.id.slice(0,6)}`:null, markedById: actor?.id } });
      }
    }
    for(const date of dates(previous.start,previous.end)){const key=date.toISOString().slice(0,10);if(date.getUTCDay()===0||holidays.has(key))continue;await prisma.attendanceDailyRegister.upsert({where:{schoolId_classId_sectionId_attendanceDate:{schoolId:school.id,classId:section.classId,sectionId:section.id,attendanceDate:date}},update:{state:'LOCKED'},create:{schoolId:school.id,academicSession:sessionName,classId:section.classId,sectionId:section.id,attendanceDate:date,state:'LOCKED',markedCount:students.length,submittedById:actor?.id,submittedAt:date,lockedById:actor?.id,lockedAt:previous.end}})}
    for(const date of dates(current.start,new Date(Math.min(current.end.getTime(),day(now.getUTCFullYear(),now.getUTCMonth(),now.getUTCDate()+1).getTime())))){const key=date.toISOString().slice(0,10);if(date.getUTCDay()===0||holidays.has(key))continue;await prisma.attendanceDailyRegister.upsert({where:{schoolId_classId_sectionId_attendanceDate:{schoolId:school.id,classId:section.classId,sectionId:section.id,attendanceDate:date}},update:{},create:{schoolId:school.id,academicSession:sessionName,classId:section.classId,sectionId:section.id,attendanceDate:date,state:'SUBMITTED',markedCount:students.length,submittedById:actor?.id,submittedAt:date}})}
    if(sectionIndex===0){const scopeKey=`${section.classId}:${section.id}`,periodEnd=new Date(previous.end.getTime()-86400000),existingLock=await prisma.attendanceLock.findFirst({where:{schoolId:school.id,scope:'MONTH',scopeKey,periodStart:previous.start,periodEnd,isActive:true}});if(!existingLock)await prisma.attendanceLock.create({data:{schoolId:school.id,academicSession:sessionName,scope:'MONTH',scopeKey,periodStart:previous.start,periodEnd,lockedById:actor?.id||'seed'}})}
  }
  if(sections.length>1){const transferStudent=await prisma.student.findFirst({where:{schoolId:school.id,className:sections[1].class.className,section:sections[1].sectionName},orderBy:[{serialNo:'asc'},{studentFirstName:'asc'}]});if(transferStudent){const transferDate=day(current.start.getUTCFullYear(),current.start.getUTCMonth(),16),priorEnd=day(current.start.getUTCFullYear(),current.start.getUTCMonth(),15);const prior=await prisma.studentEnrollmentHistory.upsert({where:{schoolId_studentId_classId_sectionId_effectiveFrom:{schoolId:school.id,studentId:transferStudent.id,classId:sections[0].classId,sectionId:sections[0].id,effectiveFrom:session?.startDate||previous.start}},update:{effectiveTo:priorEnd,exitReason:'SECTION_TRANSFER'},create:{schoolId:school.id,studentId:transferStudent.id,academicSession:sessionName,classId:sections[0].classId,sectionId:sections[0].id,effectiveFrom:session?.startDate||previous.start,effectiveTo:priorEnd,exitReason:'SECTION_TRANSFER'}});for(const date of dates(current.start,transferDate)){const key=date.toISOString().slice(0,10);if(date.getUTCDay()===0||holidays.has(key))continue;await prisma.studentAttendance.upsert({where:{schoolId_classId_sectionId_studentId_attendanceDate:{schoolId:school.id,classId:sections[0].classId,sectionId:sections[0].id,studentId:transferStudent.id,attendanceDate:date}},update:{},create:{schoolId:school.id,classId:sections[0].classId,sectionId:sections[0].id,studentId:transferStudent.id,attendanceDate:date,academicSession:sessionName,status:'PRESENT',attendanceUnits:1,enrollmentId:prior.id,remarks:'Historical record before section transfer',markedById:actor?.id}})}}}
  const employees=await prisma.employee.findMany({where:{schoolId:school.id,deletedAt:null},take:30});
  for(const [index,employee] of employees.entries())for(const date of dates(current.start,new Date(Math.min(current.end.getTime(),day(now.getUTCFullYear(),now.getUTCMonth(),now.getUTCDate()+1).getTime())))){if(date.getUTCDay()===0)continue;const status=index===1&&date.getUTCDate()%5===0?'LATE':index===2&&date.getUTCDate()%7===0?'PAID_LEAVE':index===3&&date.getUTCDate()%6===0?'ABSENT':'PRESENT';await prisma.employeeAttendance.upsert({where:{schoolId_employeeId_attendanceDate:{schoolId:school.id,employeeId:employee.id,attendanceDate:date}},update:{},create:{schoolId:school.id,employeeId:employee.id,attendanceDate:date,status,attendanceUnits:statusWeight(status),salaryImpactDays:status==='ABSENT'?1:0,minutesLate:status==='LATE'?20:0,remarks:status==='PAID_LEAVE'?'Approved demo leave':null,leaveReference:status==='PAID_LEAVE'?`DEMO-EL-${employee.id.slice(0,6)}`:null,markedById:actor?.id}})}
  if(actor&&sections[0]){const sample=await prisma.studentAttendance.findFirst({where:{schoolId:school.id,classId:sections[0].classId,sectionId:sections[0].id,status:'ABSENT'}});if(sample&&!await prisma.attendanceCorrectionRequest.findFirst({where:{schoolId:school.id,studentAttendanceId:sample.id,status:'PENDING'}}))await prisma.attendanceCorrectionRequest.create({data:{schoolId:school.id,personType:'STUDENT',personId:sample.studentId,attendanceDate:sample.attendanceDate,studentAttendanceId:sample.id,existingStatus:sample.status,requestedStatus:'MEDICAL_LEAVE',reason:'Medical certificate submitted after attendance was marked',status:'PENDING',requestedById:actor.id}})}
  // One complete, inspectable Admin-override + correction history scenario.
  if(actor&&sections[0]&&session){
    const demoDate=day(2026,7,2),assignment=await prisma.sectionClassTeacherAssignment.findFirst({where:{schoolId:school.id,academicSessionId:session.id,sectionId:sections[0].id,isPrimary:true},include:{teacher:true}}),rows=await prisma.studentAttendance.findMany({where:{schoolId:school.id,classId:sections[0].classId,sectionId:sections[0].id,attendanceDate:demoDate},orderBy:{studentId:'asc'}});
    if(rows.length){
      const register=await prisma.attendanceDailyRegister.upsert({where:{schoolId_classId_sectionId_attendanceDate:{schoolId:school.id,classId:sections[0].classId,sectionId:sections[0].id,attendanceDate:demoDate}},update:{state:'CORRECTED',isLocked:true,assignedClassTeacherId:assignment?.teacherId,markedById:actor.id,markedByRole:'ADMIN',markedByType:'ADMIN',overrideReasonCode:'CLASS_TEACHER_ABSENT',overrideReasonNote:'Class Teacher was on approved medical leave.',submittedById:actor.id,submittedAt:demoDate,lockedAt:demoDate,correctedAt:demoDate,currentRevisionNumber:2},create:{schoolId:school.id,academicSession:sessionName,classId:sections[0].classId,sectionId:sections[0].id,attendanceDate:demoDate,state:'CORRECTED',isLocked:true,assignedClassTeacherId:assignment?.teacherId,createdById:actor.id,markedById:actor.id,markedByRole:'ADMIN',markedByType:'ADMIN',overrideReasonCode:'CLASS_TEACHER_ABSENT',overrideReasonNote:'Class Teacher was on approved medical leave.',markedCount:rows.length,submittedById:actor.id,submittedAt:demoDate,lockedAt:demoDate,correctedAt:demoDate,currentRevisionNumber:2}});
      const snapshot=rows.map(row=>({studentId:row.studentId,status:row.status,remarks:row.remarks})),summary={totalStudents:rows.length,counts:rows.reduce((all,row)=>({...all,[row.status]:(all[row.status]||0)+1}),{})};
      await prisma.attendanceRevision.upsert({where:{attendanceSessionId_revisionNumber:{attendanceSessionId:register.id,revisionNumber:1}},update:{},create:{schoolId:school.id,attendanceSessionId:register.id,revisionNumber:1,actionType:'ATTENDANCE_MARKED_BY_ADMIN',createdByUserId:actor.id,createdByRole:'ADMIN',reasonCode:'CLASS_TEACHER_ABSENT',reasonNote:'Class Teacher was on approved medical leave.',summarySnapshot:summary,recordSnapshot:snapshot}});
      await prisma.attendanceRevision.upsert({where:{attendanceSessionId_revisionNumber:{attendanceSessionId:register.id,revisionNumber:2}},update:{},create:{schoolId:school.id,attendanceSessionId:register.id,revisionNumber:2,actionType:'ATTENDANCE_CORRECTED',createdByUserId:actor.id,createdByRole:'ADMIN',reasonCode:'REGISTER_VERIFICATION',reasonNote:'One student was verified present from the physical register.',summarySnapshot:summary,recordSnapshot:snapshot}});
    }
  }
  console.log(`Attendance demo seeded for ${school.schoolName}`);
}

async function main(){const schools=await prisma.school.findMany({where:{status:'ACTIVE'}});for(const school of schools)await seedSchool(school);}
main().catch(error=>{console.error(error);process.exitCode=1}).finally(()=>prisma.$disconnect());
