import 'dotenv/config';
import bcrypt from 'bcryptjs';
import prisma from '../src/config/prisma.client.js';

const firstNames=['Aarav','Aditi','Arjun','Ananya','Rohan','Kavya','Vikram','Meera','Rahul','Ishita','Karan','Nisha','Dev','Priya','Sanjay','Neha','Aditya','Riya','Manish','Sneha','Akash','Pooja','Nitin','Shreya','Vivek','Divya','Rajesh','Sakshi','Deepak','Tanvi','Amit','Swati','Varun','Preeti','Gaurav','Anjali','Mohan','Simran','Naveen','Rekha','Harish','Komal','Ajay','Rashmi'];
const roles=[
  ['Principal','Administration','ADMINISTRATION',30000],['Vice Principal','Administration','ADMINISTRATION',27000],
  ...Array.from({length:20},(_,i)=>[`${['English','Mathematics','Science','Social Science','Hindi','Computer Science'][i%6]} Teacher`,'Academics','TEACHING',25000+(i%6)*1000]),
  ['Accountant','Finance','ADMINISTRATION',22000],['Receptionist','Front Office','ADMINISTRATION',15000],['Librarian','Library','LIBRARY',13000],
  ['Driver','Transport','TRANSPORT',11000],['Driver','Transport','TRANSPORT',10500],['Conductor','Transport','TRANSPORT',10000],['Conductor','Transport','TRANSPORT',9500],
  ['Peon','Administration','SUPPORT',8000],['Peon','Administration','SUPPORT',8500],['Security Guard','Security','SUPPORT',12000],['Cleaner','Facilities','SUPPORT',7000],
  ['IT Administrator','IT','IT',20000],['School Nurse','Health','NON_TEACHING',8000],['Sports Coach','Sports','TEACHING',16000],['Lab Assistant','Laboratory','LABORATORY',14000],
  ['Fee Manager','Finance','ADMINISTRATION',15000],['HR Manager','Human Resources','ADMINISTRATION',17500],['Clerk','Administration','NON_TEACHING',13500],
  ['Hostel Warden','Hostel','NON_TEACHING',17000],['Transport Manager','Transport','TRANSPORT',16000],['Office Executive','Administration','NON_TEACHING',21000],['Counsellor','Student Wellness','NON_TEACHING',9000],
];
const hash=(...values)=>Math.abs(values.join('|').split('').reduce((a,c)=>((a*31)+c.charCodeAt(0))|0,7));
const utc=(y,m,d)=>new Date(Date.UTC(y,m,d));

async function main(){
  const school=process.env.HR_SEED_SCHOOL_ID?await prisma.school.findUnique({where:{id:process.env.HR_SEED_SCHOOL_ID}}):await prisma.school.findFirst({where:{status:'ACTIVE'},orderBy:{createdAt:'asc'}});
  if(!school)throw new Error('No active school found. Seed a school first.');
  const admin=await prisma.user.findFirst({where:{schoolId:school.id,role:{in:['SCHOOL_OWNER','ADMIN']}},select:{id:true}});
  await prisma.hrLeavePolicy.upsert({where:{schoolId:school.id},update:{},create:{schoolId:school.id,annualLeaveCount:15,monthlyPaidLimit:2,carryForward:true,lateEntriesPerDay:3,updatedById:admin?.id}});
  const employees=[];
  for(let i=0;i<roles.length;i++){
    const [designation,department,category,salary]=roles[i]; const firstName=firstNames[i],lastName=['Sharma','Verma','Singh','Patel','Gupta','Rao','Nair','Mehta'][i%8]; const employeeId=`${school.schoolCode.toUpperCase()}-EMP-${String(i+1).padStart(4,'0')}`; const email=`${firstName}.${lastName}.${i+1}@${school.slug}.schoolos.test`.toLowerCase();
    const existingTeacher=category==='TEACHING'?await prisma.teacher.findFirst({where:{schoolId:school.id,OR:[{employeeId},{email}]} }):null;
    const employee=await prisma.employee.upsert({where:{schoolId_employeeId:{schoolId:school.id,employeeId}},update:{firstName,lastName,department,designation,category},create:{schoolId:school.id,employeeId,firstName,lastName,mobile:`9${String(100000000+i*7919).padStart(9,'0').slice(-9)}`,email,gender:i%3===0?'FEMALE':'MALE',dateOfBirth:utc(1975+(i%22),i%12,3+(i%24)),bloodGroup:['O+','A+','B+','AB+'][i%4],address:`${18+i}, Green Avenue, ${school.city}`,department,designation,category,employmentType:i%9===0?'CONTRACT':'PERMANENT',joiningDate:utc(2014+(i%10),i%12,1+(i%20)),bankName:['State Bank of India','HDFC Bank','ICICI Bank'][i%3],bankAccountMasked:`XXXXXX${String(4100+i)}`,ifsc:['SBIN0001234','HDFC0001456','ICIC0001789'][i%3],teacherId:existingTeacher?.id,emergencyContact:{name:`${firstNames[(i+7)%firstNames.length]} ${lastName}`,mobile:`98${String(20000000+i*337).padStart(8,'0').slice(-8)}`},qualifications:[category==='TEACHING'?'B.Ed':'Graduate'],experience:{years:3+(i%16)}}});
    await prisma.employeeSalaryRevision.upsert({where:{employeeId_effectiveFrom:{employeeId:employee.id,effectiveFrom:utc(2025,3,1)}},update:{monthlyGross:salary,basicSalary:Math.round(salary*.55)},create:{employeeId:employee.id,monthlyGross:salary,basicSalary:Math.round(salary*.55),effectiveFrom:utc(2025,3,1),approvedById:admin?.id,reason:'Opening HR seed salary',components:{allowances:[{name:'HRA',amount:Math.round(salary*.12)},{name:'Transport',amount:1600}],deductions:[{name:'PF',amount:Math.round(salary*.06)}]}}});
    await prisma.employeeLeaveBalance.upsert({where:{employeeId_leaveYear:{employeeId:employee.id,leaveYear:new Date().getUTCFullYear()}},update:{},create:{employeeId:employee.id,leaveYear:new Date().getUTCFullYear(),opening:i%3,accrued:15,used:i%5}}); employees.push({...employee,salary});
  }
  const hrEmployee=employees.find(x=>x.designation==='HR Manager'); const hrEmail=hrEmployee.email; const hrUser=await prisma.user.upsert({where:{email:hrEmail},update:{role:'HR',schoolId:school.id,employeeId:hrEmployee.employeeId,isActive:true,mustChangePassword:false},create:{email:hrEmail,password:await bcrypt.hash(process.env.HR_SEED_PASSWORD||'Hr@SchoolOS2026!',12),name:`${hrEmployee.firstName} ${hrEmployee.lastName}`,role:'HR',schoolId:school.id,employeeId:hrEmployee.employeeId,isActive:true,mustChangePassword:false}}); await prisma.employee.update({where:{id:hrEmployee.id},data:{userId:hrUser.id}});
  const now=new Date(); const attendance=[]; const payroll=[];
  for(let back=5;back>=0;back--){const start=utc(now.getUTCFullYear(),now.getUTCMonth()-back,1),end=utc(now.getUTCFullYear(),now.getUTCMonth()-back+1,1);let working=0;for(let d=new Date(start);d<end&&d<=now;d.setUTCDate(d.getUTCDate()+1)){if([0,6].includes(d.getUTCDay()))continue;working++;for(let i=0;i<employees.length;i++){const employee=employees[i];const roll=hash(employee.id,d.toISOString().slice(0,10))%100;const status=roll<86?'PRESENT':roll<91?'LATE':roll<94?'HALF_DAY':roll<97?'PAID_LEAVE':'ABSENT';attendance.push({schoolId:school.id,employeeId:employee.id,attendanceDate:new Date(d),status,source:'IMPORT',minutesLate:status==='LATE'?8+(roll%30):0,markedById:admin?.id,remarks:'Realistic HR demonstration data'});}}
    for(let i=0;i<employees.length;i++){const employee=employees[i];const rows=attendance.filter(x=>x.employeeId===employee.id&&x.attendanceDate>=start&&x.attendanceDate<end);const payable=rows.reduce((s,x)=>s+(x.status==='ABSENT'?0:x.status==='HALF_DAY'?.5:1),0);const base=Math.round(employee.salary*(payable/Math.max(1,working))*100)/100;const allowance=Math.round((employee.salary*.12+1600)*100)/100,deduction=Math.round(employee.salary*.06*100)/100;payroll.push({schoolId:school.id,employeeId:employee.id,payrollMonth:start,workingDays:working,payableDays:payable,attendanceSummary:{workingDays:working,payableDays:payable,presentDays:rows.filter(x=>['PRESENT','LATE'].includes(x.status)).length,absentDays:rows.filter(x=>x.status==='ABSENT').length,halfDays:rows.filter(x=>x.status==='HALF_DAY').length,paidLeaves:rows.filter(x=>x.status==='PAID_LEAVE').length},monthlyGross:employee.salary,basePay:base,allowances:[{name:'HRA',amount:Math.round(employee.salary*.12)},{name:'Transport',amount:1600}],allowanceTotal:allowance,deductions:[{name:'PF',amount:deduction}],deductionTotal:deduction,netSalary:Math.max(0,base+allowance-deduction),status:back?'PAID':'PROCESSED',lockedAt:new Date(),generatedById:admin?.id,paidAt:back?new Date(Date.UTC(start.getUTCFullYear(),start.getUTCMonth()+1,1)):null,transactionReference:back?`BANK-${start.toISOString().slice(0,7).replace('-','')}-${i+1}`:null,payslipNumber:`PAY-${start.toISOString().slice(0,7).replace('-','')}-${String(i+1).padStart(4,'0')}`});}
  }
  for(let i=0;i<attendance.length;i+=500)await prisma.employeeAttendance.createMany({data:attendance.slice(i,i+500),skipDuplicates:true});
  for(let i=0;i<payroll.length;i+=250)await prisma.employeePayroll.createMany({data:payroll.slice(i,i+250),skipDuplicates:true});
  if(await prisma.employeeLeaveApplication.count({where:{schoolId:school.id}})===0)for(let i=0;i<12;i++){const employee=employees[(i*3)%employees.length],start=utc(now.getUTCFullYear(),Math.max(0,now.getUTCMonth()-(i%5)),5+(i%18));await prisma.employeeLeaveApplication.create({data:{schoolId:school.id,employeeId:employee.id,leaveType:['CASUAL','MEDICAL','PAID'][i%3],startDate:start,endDate:start,days:1,reason:['Family commitment','Medical appointment','Personal work'][i%3],status:i%4===0?'PENDING':'APPROVED',reviewedById:i%4===0?null:admin?.id,reviewedAt:i%4===0?null:new Date()}});}
  console.log(`HR seed complete: ${employees.length} employees, ${attendance.length} attendance rows, ${payroll.length} payroll rows for ${school.schoolName}.`);
}
main().catch(e=>{console.error(e);process.exitCode=1}).finally(()=>prisma.$disconnect());
