import express from 'express';
import { authMiddleware, requireRole } from '../../middleware/auth.middleware.js';
import * as controller from './examination.controller.js';

const router = express.Router();
router.get('/verify/:verificationId', controller.verify);
router.use(authMiddleware);
router.get('/dashboard', requireRole('PLATFORM_OWNER','SCHOOL_OWNER','PRINCIPAL','EXAM_COORDINATOR','ADMIN','CURRICULUM_MANAGER','TEACHER','CLASS_TEACHER'), controller.roleDashboard);
router.get('/metadata', requireRole('SCHOOL_OWNER','PRINCIPAL','EXAM_COORDINATOR','ADMIN','CURRICULUM_MANAGER'), controller.metadata);
router.get('/audit-logs', requireRole('SCHOOL_OWNER','PRINCIPAL','EXAM_COORDINATOR','ADMIN'), controller.auditLogs);
router.post('/configuration/grade-scales', requireRole('EXAM_COORDINATOR','ADMIN','CURRICULUM_MANAGER'), controller.saveGradeScale);
router.patch('/configuration/grade-scales/:scaleId', requireRole('EXAM_COORDINATOR','ADMIN','CURRICULUM_MANAGER'), controller.saveGradeScale);
router.post('/configuration/rule-sets', requireRole('EXAM_COORDINATOR','ADMIN','CURRICULUM_MANAGER'), controller.saveRuleSet);
router.patch('/configuration/rule-sets/:ruleId', requireRole('EXAM_COORDINATOR','ADMIN','CURRICULUM_MANAGER'), controller.saveRuleSet);
router.get('/my-results', requireRole('STUDENT','PARENT'), controller.studentResults);
router.get('/', requireRole('PLATFORM_OWNER','SCHOOL_OWNER','PRINCIPAL','EXAM_COORDINATOR','ADMIN','CURRICULUM_MANAGER','TEACHER','CLASS_TEACHER'), controller.list);
router.post('/', requireRole('EXAM_COORDINATOR','ADMIN','CURRICULUM_MANAGER'), controller.create);
router.get('/:id', requireRole('SCHOOL_OWNER','PRINCIPAL','EXAM_COORDINATOR','ADMIN','CURRICULUM_MANAGER','TEACHER','CLASS_TEACHER'), controller.detail);
router.patch('/:id', requireRole('EXAM_COORDINATOR','ADMIN','CURRICULUM_MANAGER'), controller.update);
router.post('/:id/transition', requireRole('PRINCIPAL','EXAM_COORDINATOR','ADMIN'), controller.transition);
router.get('/:id/mark-sheet', requireRole('EXAM_COORDINATOR','ADMIN','TEACHER'), controller.markSheet);
router.put('/:id/marks', requireRole('EXAM_COORDINATOR','ADMIN','TEACHER'), controller.saveMarks);
router.post('/:id/subjects/:examSubjectId/submit', requireRole('EXAM_COORDINATOR','ADMIN','TEACHER'), controller.submitMarks);
router.post('/:id/review', requireRole('PRINCIPAL','EXAM_COORDINATOR','ADMIN','TEACHER','CLASS_TEACHER'), controller.review);
router.post('/:id/calculate', requireRole('EXAM_COORDINATOR','ADMIN'), controller.calculate);
router.post('/:id/publish', requireRole('PRINCIPAL','EXAM_COORDINATOR'), controller.publish);
router.post('/:id/corrections', requireRole('PRINCIPAL','EXAM_COORDINATOR'), controller.requestCorrection);
router.get('/:id/results/students/:studentId', requireRole('SCHOOL_OWNER','PRINCIPAL','EXAM_COORDINATOR','ADMIN','CURRICULUM_MANAGER','TEACHER','STUDENT','PARENT'), controller.studentResults);
router.get('/:id/analytics', requireRole('PLATFORM_OWNER','SCHOOL_OWNER','PRINCIPAL','EXAM_COORDINATOR','ADMIN','CURRICULUM_MANAGER'), controller.analytics);
router.get('/:id/result-register', requireRole('SCHOOL_OWNER','PRINCIPAL','EXAM_COORDINATOR','ADMIN','CURRICULUM_MANAGER','TEACHER'), controller.resultRegister);
router.get('/:id/report-cards/:studentId.pdf', requireRole('SCHOOL_OWNER','PRINCIPAL','EXAM_COORDINATOR','ADMIN','TEACHER','STUDENT','PARENT'), controller.reportCard);
export default router;
