import crypto from 'node:crypto';
import prisma from '../../config/prisma.client.js';
import { calculateCharge } from './feeCalculation.service.js';

const schoolIdOf = (user) => { if (!user?.schoolId) throw Object.assign(new Error('School tenant required'), { status: 403 }); return user.schoolId; };
const safe = (value) => JSON.parse(JSON.stringify(value, (_, item) => typeof item === 'bigint' ? Number(item) : item));
const priority = { STUDENT: 100, GROUP: 90, CATEGORY: 90, SECTION: 80, CLASS: 70, STREAM: 60, COURSE: 60, BATCH: 60, TRANSPORT: 50, HOSTEL: 50, SCHOOL: 10 };
const monthsFor = { ONE_TIME: 1, MONTHLY: 12, BI_MONTHLY: 6, QUARTERLY: 4, FOUR_MONTHLY: 3, HALF_YEARLY: 2, ANNUAL: 1, PER_TERM: 3, PER_SEMESTER: 2 };
const recordAudit = (tx, req, action, entityType, entityId, details, reason) => tx.feeAuditLog.create({ data: { schoolId: schoolIdOf(req.user), userId: req.user.id, userRole: req.user.role, action, entityType, entityId, newValue: details ? safe(details) : undefined, reason, ipAddress: req.ip, userAgent: req.get?.('user-agent') } });
const ensureUnlocked = async (tx, schoolId, date) => { const locked = await tx.feeFinancialPeriod.findFirst({ where: { schoolId, lockedAt: { not: null }, startDate: { lte: date }, endDate: { gte: date } } }); if (locked) throw Object.assign(new Error(`Financial period ${locked.periodKey} is locked`), { status: 409 }); };

const assignmentMatches = (assignment, student) => {
  if (assignment.targetType === 'SCHOOL') return true;
  if (assignment.targetType === 'STUDENT') return assignment.studentId === student.id;
  if (assignment.targetType === 'CLASS') return assignment.targetValue === student.className;
  if (assignment.targetType === 'SECTION') return assignment.targetValue === `${student.className}:${student.section}` || assignment.targetValue === student.section;
  if (assignment.targetType === 'CATEGORY') return assignment.targetValue === student.category;
  return false;
};

export const previewAssignment = async (user, data) => {
  const schoolId = schoolIdOf(user); const structure = await prisma.feeStructure.findFirst({ where: { id: data.feeStructureId, schoolId }, include: { components: true } });
  if (!structure) throw Object.assign(new Error('Fee structure not found'), { status: 404 });
  const students = await prisma.student.findMany({ where: { schoolId, isActive: true, session: structure.academicSession } });
  const affected = students.filter((student) => assignmentMatches({ ...data, priority: priority[data.targetType] }, student));
  const perStudent = structure.components.filter((c) => c.active).reduce((sum, c) => sum + BigInt(c.amountMinor) * BigInt(monthsFor[c.frequency] || 1), 0n);
  const classImpact = Object.values(affected.reduce((map, student) => { const key = `${student.className}${student.section ? ` / ${student.section}` : ''}`; map[key] ||= { classSection: key, students: 0, expectedMinor: 0n }; map[key].students += 1; map[key].expectedMinor += perStudent; return map; }, {}));
  const existing = await prisma.feeAssignment.findMany({ where: { schoolId, academicSession: structure.academicSession, active: true }, include: { feeStructure: { select: { name: true } } } });
  const conflicts = affected.flatMap((student) => existing.filter((a) => assignmentMatches(a, student) && (a.priority || priority[a.targetType]) >= priority[data.targetType]).map((a) => ({ studentId: student.id, admissionNo: student.admissionNo, existingStructure: a.feeStructure.name, existingPriority: a.priority })));
  return safe({ affectedStudents: affected.length, projectedRevenueMinor: perStudent * BigInt(affected.length), perStudentMinor: perStudent, classImpact, conflicts, students: affected.map((s) => ({ id: s.id, name: `${s.studentFirstName} ${s.studentLastName || ''}`.trim(), admissionNo: s.admissionNo, className: s.className, section: s.section })) });
};

export const createAssignmentAndCharges = (req, data) => prisma.$transaction(async (tx) => {
  const schoolId = schoolIdOf(req.user); const structure = await tx.feeStructure.findFirst({ where: { id: data.feeStructureId, schoolId, status: 'PUBLISHED' }, include: { components: { where: { active: true } } } });
  if (!structure) throw Object.assign(new Error('Published fee structure not found'), { status: 404 });
  const assignment = await tx.feeAssignment.create({ data: { schoolId, academicSession: structure.academicSession, feeStructureId: structure.id, studentId: data.targetType === 'STUDENT' ? data.studentId : null, targetType: data.targetType, targetValue: data.targetValue, priority: priority[data.targetType], createdById: req.user.id } });
  const students = (await tx.student.findMany({ where: { schoolId, isActive: true, session: structure.academicSession } })).filter((student) => assignmentMatches(assignment, student));
  let created = 0;
  for (const student of students) {
    const superior = await tx.feeAssignment.findFirst({ where: { schoolId, studentId: student.id, active: true, priority: { gt: assignment.priority } } }); if (superior) continue;
    const account = await tx.studentFeeAccount.upsert({ where: { schoolId_studentId_academicSession: { schoolId, studentId: student.id, academicSession: structure.academicSession } }, create: { schoolId, studentId: student.id, academicSession: structure.academicSession }, update: {} });
    for (const component of structure.components) {
      const count = monthsFor[component.frequency] || 1; const interval = Math.max(1, Math.floor(12 / count));
      for (let index = 0; index < count; index += 1) {
        const dueDate = new Date(data.scheduleStart || `${structure.academicSession.slice(0, 4)}-04-01T00:00:00.000Z`); dueDate.setUTCMonth(dueDate.getUTCMonth() + index * interval); if (component.dueDay) dueDate.setUTCDate(component.dueDay);
        const installmentName = count === 1 ? component.name : `${component.name} ${index + 1}/${count}`;
        const charge = await tx.studentFeeCharge.upsert({ where: { schoolId_studentId_feeStructureId_feeComponentId_academicSession_installmentName: { schoolId, studentId: student.id, feeStructureId: structure.id, feeComponentId: component.id, academicSession: structure.academicSession, installmentName } }, create: { schoolId, studentId: student.id, feeAccountId: account.id, feeStructureId: structure.id, feeComponentId: component.id, academicSession: structure.academicSession, installmentName, dueDate, baseAmountMinor: component.amountMinor, status: dueDate < new Date() ? 'OVERDUE' : 'UPCOMING', calculationSnapshot: { componentCode: component.code, structureVersion: structure.version } }, update: {} });
        if (charge.createdAt.getTime() === charge.updatedAt.getTime()) { const last = await tx.feeLedgerEntry.findFirst({ where: { feeAccountId: account.id }, orderBy: { createdAt: 'desc' } }); await tx.feeLedgerEntry.create({ data: { schoolId, studentId: student.id, feeAccountId: account.id, academicSession: structure.academicSession, entryType: 'CHARGE', referenceType: 'StudentFeeCharge', referenceId: charge.id, referenceNumber: component.code, description: installmentName, debitMinor: component.amountMinor, balanceMinor: BigInt(last?.balanceMinor || 0) + BigInt(component.amountMinor), createdById: req.user.id } }).catch((e) => { if (e.code !== 'P2002') throw e; }); created += 1; }
      }
    }
  }
  await recordAudit(tx, req, 'FEE_ASSIGNMENT_PUBLISHED', 'FeeAssignment', assignment.id, { affectedStudents: students.length, chargesCreated: created }); return { assignment, affectedStudents: students.length, chargesCreated: created };
}, { isolationLevel: 'Serializable', timeout: 30000 });

export const changeChequeStatus = (req, paymentId, nextStatus, reason) => prisma.$transaction(async (tx) => {
  const schoolId = schoolIdOf(req.user); const payment = await tx.feePayment.findFirst({ where: { id: paymentId, schoolId, method: 'CHEQUE' }, include: { allocations: true, receipt: true, feeAccount: true } });
  if (!payment) throw Object.assign(new Error('Cheque payment not found'), { status: 404 }); await ensureUnlocked(tx, schoolId, new Date());
  const allowed = { PENDING_CLEARANCE: ['CLEARED', 'BOUNCED', 'CANCELLED'], CLEARED: ['BOUNCED'], BOUNCED: ['PENDING_CLEARANCE'] }; if (!allowed[payment.status]?.includes(nextStatus)) throw Object.assign(new Error(`Cannot change cheque from ${payment.status} to ${nextStatus}`), { status: 409 });
  await tx.feePayment.update({ where: { id: payment.id }, data: { status: nextStatus, metadata: { ...(payment.metadata || {}), statusReason: reason, statusChangedAt: new Date().toISOString() } } });
  if (nextStatus === 'CLEARED') for (const a of payment.allocations) { const charge = await tx.studentFeeCharge.findUnique({ where: { id: a.chargeId } }); const paid = BigInt(charge.paidMinor) + BigInt(a.amountMinor); const payable = calculateCharge({ ...charge, paidMinor: paid }).payableMinor; await tx.studentFeeCharge.update({ where: { id: charge.id }, data: { paidMinor: paid, status: payable === 0n ? 'PAID' : 'PARTIALLY_PAID' } }); }
  if (nextStatus === 'CLEARED' && payment.unappliedMinor > 0n) await tx.studentFeeAccount.update({ where: { id: payment.feeAccountId }, data: { advanceBalanceMinor: { increment: payment.unappliedMinor } } });
  if (nextStatus === 'BOUNCED' && payment.status === 'CLEARED') for (const a of payment.allocations) { const charge = await tx.studentFeeCharge.findUnique({ where: { id: a.chargeId } }); const paid = BigInt(charge.paidMinor) >= BigInt(a.amountMinor) ? BigInt(charge.paidMinor) - BigInt(a.amountMinor) : 0n; const payable = calculateCharge({ ...charge, paidMinor: paid }).payableMinor; await tx.studentFeeCharge.update({ where: { id: charge.id }, data: { paidMinor: paid, status: paid > 0n ? 'PARTIALLY_PAID' : charge.dueDate < new Date() ? 'OVERDUE' : 'DUE' } }); }
  if (nextStatus === 'BOUNCED' && payment.status === 'CLEARED' && payment.unappliedMinor > 0n) await tx.studentFeeAccount.update({ where: { id: payment.feeAccountId }, data: { advanceBalanceMinor: { decrement: payment.unappliedMinor } } });
  if (nextStatus === 'BOUNCED' && payment.receipt) await tx.feeReceipt.update({ where: { id: payment.receipt.id }, data: { status: 'CANCELLED' } });
  const last = await tx.feeLedgerEntry.findFirst({ where: { feeAccountId: payment.feeAccountId }, orderBy: { createdAt: 'desc' } });
  await tx.feeLedgerEntry.create({ data: { schoolId, studentId: payment.studentId, feeAccountId: payment.feeAccountId, academicSession: payment.academicSession, entryType: nextStatus === 'CLEARED' ? 'PAYMENT' : 'REVERSAL', referenceType: 'ChequeStatus', referenceId: `${payment.id}:${nextStatus}`, referenceNumber: payment.paymentNumber, description: `Cheque ${nextStatus.toLowerCase().replace('_', ' ')}: ${reason}`, debitMinor: nextStatus === 'BOUNCED' ? payment.amountMinor : 0, creditMinor: nextStatus === 'CLEARED' ? payment.amountMinor : 0, balanceMinor: BigInt(last?.balanceMinor || 0) + (nextStatus === 'BOUNCED' ? BigInt(payment.amountMinor) : -BigInt(payment.amountMinor)), createdById: req.user.id } });
  await recordAudit(tx, req, `CHEQUE_${nextStatus}`, 'FeePayment', payment.id, { previousStatus: payment.status, nextStatus }, reason); return { paymentId, status: nextStatus };
});

export const reviewAdjustment = (req, id, decision, comment) => prisma.$transaction(async (tx) => {
  const schoolId = schoolIdOf(req.user); const adjustment = await tx.feeAdjustment.findFirst({ where: { id, schoolId, status: 'PENDING' } }); if (!adjustment) throw Object.assign(new Error('Pending adjustment not found'), { status: 404 });
  if (adjustment.requestedById === req.user.id) throw Object.assign(new Error('You cannot approve your own request'), { status: 409 });
  const status = decision === 'APPROVE' ? 'APPROVED' : 'REJECTED'; const result = await tx.feeAdjustment.update({ where: { id }, data: { status, approvedById: req.user.id, approvedAt: new Date(), metadata: { ...(adjustment.metadata || {}), reviewComment: comment } } });
  await recordAudit(tx, req, `FEE_ADJUSTMENT_${status}`, 'FeeAdjustment', id, { amountMinor: adjustment.amountMinor }, comment); return result;
});

export const processAdjustment = (req, id) => prisma.$transaction(async (tx) => {
  const schoolId = schoolIdOf(req.user); const adjustment = await tx.feeAdjustment.findFirst({ where: { id, schoolId, status: 'APPROVED' } }); if (!adjustment) throw Object.assign(new Error('Approved adjustment not found'), { status: 404 });
  const account = await tx.studentFeeAccount.findUnique({ where: { schoolId_studentId_academicSession: { schoolId, studentId: adjustment.studentId, academicSession: adjustment.academicSession } } }); if (!account) throw new Error('Student fee account not found'); await ensureUnlocked(tx, schoolId, new Date());
  const last = await tx.feeLedgerEntry.findFirst({ where: { feeAccountId: account.id }, orderBy: { createdAt: 'desc' } }); const creditTypes = new Set(['DISCOUNT', 'SCHOLARSHIP', 'WAIVER', 'LATE_FEE_WAIVER', 'REFUND', 'CREDIT_NOTE']);
  const ledgerType = ['DISCOUNT', 'SCHOLARSHIP', 'WAIVER', 'LATE_FEE_WAIVER', 'REFUND', 'REVERSAL', 'CREDIT_NOTE', 'DEBIT_NOTE', 'CARRY_FORWARD'].includes(adjustment.type) ? (adjustment.type === 'LATE_FEE_WAIVER' ? 'WAIVER' : adjustment.type) : 'CREDIT_NOTE';
  await tx.feeLedgerEntry.create({ data: { schoolId, studentId: adjustment.studentId, feeAccountId: account.id, academicSession: adjustment.academicSession, entryType: ledgerType, referenceType: 'FeeAdjustment', referenceId: adjustment.id, description: adjustment.reason, debitMinor: adjustment.type === 'REFUND' ? adjustment.amountMinor : 0, creditMinor: adjustment.type === 'REFUND' ? 0 : adjustment.amountMinor, balanceMinor: BigInt(last?.balanceMinor || 0) + (adjustment.type === 'REFUND' ? BigInt(adjustment.amountMinor) : -BigInt(adjustment.amountMinor)), createdById: req.user.id } });
  if (adjustment.type === 'REFUND') { const paid = await tx.feePayment.aggregate({ where: { schoolId, studentId: adjustment.studentId, status: { in: ['COMPLETED', 'CLEARED'] } }, _sum: { amountMinor: true } }); const prior = await tx.feeAdjustment.aggregate({ where: { schoolId, studentId: adjustment.studentId, type: 'REFUND', status: 'PROCESSED' }, _sum: { amountMinor: true } }); if (BigInt(prior._sum.amountMinor || 0) + BigInt(adjustment.amountMinor) > BigInt(paid._sum.amountMinor || 0)) throw Object.assign(new Error('Refund exceeds collected amount'), { status: 409 }); }
  const result = await tx.feeAdjustment.update({ where: { id }, data: { status: 'PROCESSED', processedAt: new Date() } }); await recordAudit(tx, req, 'FEE_ADJUSTMENT_PROCESSED', 'FeeAdjustment', id, result); return result;
});

export const cancelReceipt = (req, id, reason, approvalRequestId) => prisma.$transaction(async (tx) => { const schoolId = schoolIdOf(req.user); const receipt = await tx.feeReceipt.findFirst({ where: { id, schoolId, status: 'VALID' }, include: { payment: true } }); if (!receipt) throw Object.assign(new Error('Valid receipt not found'), { status: 404 }); if (!approvalRequestId) { const request = await tx.feeApprovalRequest.create({ data: { schoolId, academicSession: receipt.academicSession, actionType: 'RECEIPT_CANCELLATION', entityType: 'FeeReceipt', entityId: id, reason, requestedById: req.user.id } }); await recordAudit(tx, req, 'RECEIPT_CANCELLATION_REQUESTED', 'FeeReceipt', id, { approvalId: request.id }, reason); return { id, status: 'PENDING_APPROVAL', approvalRequestId: request.id }; } const approval = await tx.feeApprovalRequest.findFirst({ where: { id: approvalRequestId, schoolId, entityId: id, actionType: 'RECEIPT_CANCELLATION', status: 'PENDING' } }); if (!approval) throw Object.assign(new Error('Pending cancellation approval not found'), { status: 404 }); if (approval.requestedById === req.user.id) throw Object.assign(new Error('You cannot approve your own cancellation request'), { status: 409 }); await tx.feeApprovalRequest.update({ where: { id: approval.id }, data: { status: 'APPROVED', reviewedById: req.user.id, reviewedAt: new Date() } }); await tx.feeReceipt.update({ where: { id }, data: { status: 'CANCELLED' } }); await recordAudit(tx, req, 'RECEIPT_CANCELLED', 'FeeReceipt', id, { approvalId: approval.id }, reason); return { id, status: 'CANCELLED' }; });

const render = (text, values) => text.replace(/{{(\w+)}}/g, (_, key) => values[key] ?? '');
export const saveTemplate = (req, data) => prisma.feeNotificationTemplate.upsert({ where: { schoolId_name: { schoolId: schoolIdOf(req.user), name: data.name } }, create: { schoolId: schoolIdOf(req.user), createdById: req.user.id, ...data }, update: data });
export const listTemplates = (user) => prisma.feeNotificationTemplate.findMany({ where: { schoolId: schoolIdOf(user) }, orderBy: { name: 'asc' } });
export const sendReminders = async (req, data) => { const schoolId = schoolIdOf(req.user); const template = await prisma.feeNotificationTemplate.findFirst({ where: { id: data.templateId, schoolId, active: true } }); if (!template) throw Object.assign(new Error('Template not found'), { status: 404 }); const charges = await prisma.studentFeeCharge.findMany({ where: { schoolId, academicSession: data.academicSession, status: { in: data.statuses || ['OVERDUE', 'PARTIALLY_PAID', 'DUE'] }, ...(data.studentIds?.length ? { studentId: { in: data.studentIds } } : {}) }, include: { student: true } }); const unique = new Map(charges.map((c) => [c.studentId, c])); const rows = [...unique.values()].map((c) => ({ schoolId, studentId: c.studentId, academicSession: c.academicSession, type: template.type, title: render(template.title, { studentName: c.student.studentFirstName, dueAmount: Number(c.baseAmountMinor) / 100 }), message: render(template.body, { studentName: c.student.studentFirstName, parentName: c.student.fatherName, class: c.student.className, section: c.student.section || '', dueAmount: (Number(c.baseAmountMinor) / 100).toFixed(2), dueDate: c.dueDate.toLocaleDateString(), installmentName: c.installmentName }), sentById: req.user.id })); if (rows.length) await prisma.feeReminder.createMany({ data: rows }); return { sent: rows.length, channel: 'IN_APP' }; };

export const submitClosing = async (req, data) => { const schoolId = schoolIdOf(req.user); const start = new Date(data.closingDate); start.setHours(0, 0, 0, 0); const end = new Date(start); end.setDate(end.getDate() + 1); const payments = await prisma.feePayment.findMany({ where: { schoolId, collectedById: req.user.id, paymentDate: { gte: start, lt: end }, status: { in: ['COMPLETED', 'CLEARED'] } } }); const cash = payments.filter((p) => p.method === 'CASH').reduce((s, p) => s + BigInt(p.amountMinor), 0n); const nonCash = payments.filter((p) => p.method !== 'CASH').reduce((s, p) => s + BigInt(p.amountMinor), 0n); const opening = BigInt(data.openingCashMinor || 0); const actual = BigInt(data.actualClosingMinor); const expected = opening + cash; return prisma.feeDailyCashClosing.upsert({ where: { schoolId_closingDate_feeManagerId: { schoolId, closingDate: start, feeManagerId: req.user.id } }, create: { schoolId, closingDate: start, feeManagerId: req.user.id, openingCashMinor: opening, cashCollectedMinor: cash, nonCashCollectedMinor: nonCash, expectedClosingMinor: expected, actualClosingMinor: actual, differenceMinor: actual - expected, notes: data.notes }, update: { openingCashMinor: opening, cashCollectedMinor: cash, nonCashCollectedMinor: nonCash, expectedClosingMinor: expected, actualClosingMinor: actual, differenceMinor: actual - expected, notes: data.notes, status: 'PENDING' } }); };
export const reviewClosing = (req, id, status, comment) => prisma.feeDailyCashClosing.updateMany({ where: { id, schoolId: schoolIdOf(req.user), status: 'PENDING' }, data: { status, reviewedById: req.user.id, reviewComment: comment, reviewedAt: new Date() } });
export const listClosings = (user) => prisma.feeDailyCashClosing.findMany({ where: { schoolId: schoolIdOf(user), ...(user.role === 'FEE_MANAGER' ? { feeManagerId: user.id } : {}) }, orderBy: { closingDate: 'desc' } });

export const setPeriodLock = (req, data) => prisma.$transaction(async (tx) => { const schoolId = schoolIdOf(req.user); const period = await tx.feeFinancialPeriod.upsert({ where: { schoolId_academicSession_periodKey: { schoolId, academicSession: data.academicSession, periodKey: data.periodKey } }, create: { schoolId, academicSession: data.academicSession, periodKey: data.periodKey, startDate: new Date(data.startDate), endDate: new Date(data.endDate), lockedAt: data.lock ? new Date() : null, lockedById: data.lock ? req.user.id : null, reopenedAt: data.lock ? null : new Date(), reopenedById: data.lock ? null : req.user.id, reopenReason: data.reason }, update: data.lock ? { lockedAt: new Date(), lockedById: req.user.id } : { lockedAt: null, reopenedAt: new Date(), reopenedById: req.user.id, reopenReason: data.reason } }); await recordAudit(tx, req, data.lock ? 'PERIOD_LOCKED' : 'PERIOD_REOPENED', 'FeeFinancialPeriod', period.id, period, data.reason); return period; });

export const rollover = (req, data) => prisma.$transaction(async (tx) => { const schoolId = schoolIdOf(req.user); const accounts = await tx.studentFeeAccount.findMany({ where: { schoolId, academicSession: data.fromSession }, include: { ledgerEntries: { orderBy: { createdAt: 'desc' }, take: 1 } } }); let carried = 0; for (const old of accounts) { const balance = BigInt(old.ledgerEntries[0]?.balanceMinor || 0); if (balance <= 0n) continue; const account = await tx.studentFeeAccount.upsert({ where: { schoolId_studentId_academicSession: { schoolId, studentId: old.studentId, academicSession: data.toSession } }, create: { schoolId, studentId: old.studentId, academicSession: data.toSession, carriedForwardMinor: balance }, update: { carriedForwardMinor: { increment: balance } } }); await tx.feeLedgerEntry.create({ data: { schoolId, studentId: old.studentId, feeAccountId: account.id, academicSession: data.toSession, entryType: 'CARRY_FORWARD', referenceType: 'SessionRollover', referenceId: `${old.id}:${data.toSession}`, description: `Outstanding dues carried from ${data.fromSession}`, debitMinor: balance, balanceMinor: balance, createdById: req.user.id } }).catch((e) => { if (e.code !== 'P2002') throw e; }); carried += 1; } await recordAudit(tx, req, 'SESSION_DUES_ROLLED_OVER', 'StudentFeeAccount', data.toSession, { from: data.fromSession, accounts: carried }, data.reason); return { accountsCarried: carried }; });

export const createScholarship = (req, data) => prisma.feeScholarship.create({ data: { schoolId: schoolIdOf(req.user), createdById: req.user.id, ...data, valueMinor: data.valueMinor == null ? null : BigInt(data.valueMinor), maximumMinor: data.maximumMinor == null ? null : BigInt(data.maximumMinor) } });
export const assignScholarship = (req, data) => prisma.studentFeeScholarship.create({ data: { schoolId: schoolIdOf(req.user), studentId: data.studentId, scholarshipId: data.scholarshipId, chargeId: data.chargeId, academicSession: data.academicSession, amountMinor: BigInt(data.amountMinor), reason: data.reason, requestedById: req.user.id, status: req.user.role === 'FEE_MANAGER' ? 'PENDING' : 'APPROVED', approvedById: req.user.role === 'FEE_MANAGER' ? null : req.user.id, approvedAt: req.user.role === 'FEE_MANAGER' ? null : new Date() } });

export const familyOverview = async (user) => { const schoolId = schoolIdOf(user); const links = await prisma.feeFamilyLink.findMany({ where: { schoolId, parentUserId: user.email, active: true }, include: { student: true } }); const fallback = links.length ? links : await prisma.student.findMany({ where: { id: user.studentId, schoolId } }).then((students) => students.map((student) => ({ student }))); const children = []; for (const { student } of fallback) { const account = await prisma.studentFeeAccount.findUnique({ where: { schoolId_studentId_academicSession: { schoolId, studentId: student.id, academicSession: student.session } }, include: { charges: true, payments: { include: { receipt: true }, orderBy: { paymentDate: 'desc' }, take: 5 } } }); const pending = (account?.charges || []).reduce((sum, c) => sum + calculateCharge(c).payableMinor, 0n); children.push({ student: { id: student.id, name: `${student.studentFirstName} ${student.studentLastName || ''}`.trim(), className: student.className, section: student.section }, account: safe(account), pendingMinor: Number(pending) }); } return { children, combinedPendingMinor: children.reduce((s, c) => s + c.pendingMinor, 0) }; };
export const linkFamily = (req, data) => prisma.feeFamilyLink.create({ data: { schoolId: schoolIdOf(req.user), parentUserId: data.parentUserId, studentId: data.studentId, relationship: data.relationship || 'PARENT' } });

export const report = async (user, filters) => { const schoolId = schoolIdOf(user); const where = { schoolId, ...(filters.academicSession ? { academicSession: filters.academicSession } : {}), ...(filters.from || filters.to ? { paymentDate: { ...(filters.from ? { gte: new Date(filters.from) } : {}), ...(filters.to ? { lte: new Date(filters.to) } : {}) } } : {}), ...(filters.method ? { method: filters.method } : {}) }; const rows = await prisma.feePayment.findMany({ where, include: { student: { select: { studentFirstName: true, studentLastName: true, admissionNo: true, className: true, section: true } }, receipt: true }, orderBy: { paymentDate: 'desc' }, take: 10000 }); return safe({ rows, totalMinor: rows.reduce((s, p) => s + BigInt(p.amountMinor), 0n), filters }); };
export const platformAnalytics = async (user) => { if (user.role !== 'PLATFORM_OWNER') throw Object.assign(new Error('Forbidden'), { status: 403 }); const settings = await prisma.feeModuleSetting.findMany({ include: { school: { select: { schoolName: true, schoolCode: true } } } }); const summaries = await Promise.all(settings.map(async (setting) => { const payments = setting.allowPlatformSummary ? await prisma.feePayment.aggregate({ where: { schoolId: setting.schoolId, status: { in: ['COMPLETED', 'CLEARED'] } }, _sum: { amountMinor: true }, _count: true }) : null; return { school: setting.school, enabled: setting.enabled, mode: setting.mode, allowPlatformSummary: setting.allowPlatformSummary, collection: payments ? safe(payments) : null }; })); return { enabledSchools: settings.filter((s) => s.enabled).length, configuredSchools: settings.length, schools: summaries }; };
export const auditLogs = (user, query) => prisma.feeAuditLog.findMany({ where: { schoolId: schoolIdOf(user), ...(query.action ? { action: query.action } : {}), ...(query.entityType ? { entityType: query.entityType } : {}) }, orderBy: { createdAt: 'desc' }, take: Math.min(Number(query.limit) || 100, 500) });
export const attachDocument = async (req, data) => { const schoolId = schoolIdOf(req.user); if (!/^https:\/\//i.test(data.url)) throw new Error('Document URL must use HTTPS'); const entityExists = data.entityType === 'StudentFeeScholarship' ? await prisma.studentFeeScholarship.findFirst({ where: { id: data.entityId, schoolId } }) : data.entityType === 'FeeAdjustment' ? await prisma.feeAdjustment.findFirst({ where: { id: data.entityId, schoolId } }) : null; if (!entityExists) throw Object.assign(new Error('Document entity not found'), { status: 404 }); return prisma.feeDocument.create({ data: { schoolId, entityType: data.entityType, entityId: data.entityId, name: data.name, url: data.url, mimeType: data.mimeType, uploadedById: req.user.id } }); };
