import React, { useEffect, useState } from 'react';
import { Bus, FileText, Layers3, RefreshCw, RotateCcw, Tags } from 'lucide-react';
import toast from 'react-hot-toast';
import DashboardLayout from '../../layouts/DashboardLayout';
import { authService } from '../../services/authService';
import { feeService } from '../../services/feeService';

const card = 'rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900';
const input = 'h-11 w-full rounded-xl border border-slate-300 bg-white px-3 text-sm dark:border-slate-700 dark:bg-slate-950';
const button = 'rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50';
const money = (minor = 0) => new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR' }).format(Number(minor) / 100);
const tabs = [['categories', 'Categories', Tags], ['components', 'Components', Layers3], ['invoices', 'Invoices', FileText], ['refunds', 'Refunds', RotateCcw], ['transport', 'Transport', Bus]];

export default function FeeAdministrationPage() {
  const role = authService.getCurrentUser()?.role; const [tab, setTab] = useState('categories'); const [rows, setRows] = useState([]); const [categories, setCategories] = useState([]); const [busy, setBusy] = useState(false);
  const [form, setForm] = useState({ academicSession: '2026-27', name: '', code: '', categoryId: '', frequency: 'MONTHLY', defaultAmount: '', className: '', section: '', paymentId: '', refundAmount: '', reason: '', vehicleNumber: '', stopName: '', monthlyAmount: '' });
  const set = (name) => (event) => setForm((current) => ({ ...current, [name]: event.target.value }));
  const load = async () => { setBusy(true); try { const cats = await feeService.categories({ includeInactive: true }); setCategories(cats); if (tab === 'categories') setRows(cats); if (tab === 'components') setRows(await feeService.components({ includeInactive: true })); if (tab === 'invoices') setRows((await feeService.invoices({ academicSession: form.academicSession })).items); if (tab === 'refunds') setRows((await feeService.refunds({})).items); if (tab === 'transport') setRows(await feeService.transportRoutes()); } catch (error) { toast.error(error.response?.data?.message || 'Unable to load fee records'); } finally { setBusy(false); } };
  useEffect(() => { load(); }, [tab]);
  const submit = async (event) => { event.preventDefault(); setBusy(true); try {
    if (tab === 'categories') await feeService.createCategory({ name: form.name, code: form.code });
    if (tab === 'components') await feeService.createComponent({ name: form.name, code: form.code, categoryId: form.categoryId || undefined, frequency: form.frequency, defaultAmountMinor: form.defaultAmount ? Math.round(Number(form.defaultAmount) * 100) : undefined });
    if (tab === 'invoices') await feeService.generateInvoices({ academicSession: form.academicSession, className: form.className || undefined, section: form.section || undefined, billingPeriod: form.name || undefined });
    if (tab === 'refunds') await feeService.processRefund({ paymentId: form.paymentId, amountMinor: Math.round(Number(form.refundAmount) * 100), reason: form.reason, method: 'BANK_TRANSFER' });
    if (tab === 'transport') await feeService.createTransportRoute({ name: form.name, code: form.code, vehicleNumber: form.vehicleNumber || undefined, stops: form.stopName ? [{ name: form.stopName, monthlyMinor: Math.round(Number(form.monthlyAmount) * 100) }] : [] });
    toast.success(`${tabs.find(([id]) => id === tab)[1]} saved`); setForm((value) => ({ ...value, name: '', code: '', defaultAmount: '', paymentId: '', refundAmount: '', reason: '', vehicleNumber: '', stopName: '', monthlyAmount: '' })); await load();
  } catch (error) { toast.error(error.response?.data?.message || 'Save failed'); } finally { setBusy(false); } };
  return <DashboardLayout role={role}><div className="space-y-5"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><h1 className="text-2xl font-bold">Fee configuration and records</h1><p className="text-sm text-slate-500">Manage reusable masters, issued invoices, refunds, and selected-student transport.</p></div><button onClick={load} className="inline-flex items-center gap-2 rounded-xl border px-4 py-2 text-sm font-semibold dark:border-slate-700"><RefreshCw size={16}/> Refresh</button></div><div className="flex gap-2 overflow-x-auto">{tabs.map(([id, label, Icon]) => <button key={id} onClick={() => setTab(id)} className={`inline-flex items-center gap-2 whitespace-nowrap rounded-xl px-4 py-2 text-sm font-semibold ${tab === id ? 'bg-slate-900 text-white dark:bg-white dark:text-slate-900' : 'border dark:border-slate-700'}`}><Icon size={16}/>{label}</button>)}</div>
  <form onSubmit={submit} className={card}><h2 className="font-semibold">{tab === 'invoices' ? 'Generate invoice batch' : tab === 'refunds' ? 'Process authorized refund' : `Add ${tab === 'transport' ? 'transport route' : tab.slice(0, -1)}`}</h2><div className="mt-4 grid gap-3 md:grid-cols-3">
    {tab !== 'refunds' && <><input required={tab !== 'invoices'} className={input} placeholder={tab === 'invoices' ? 'Billing period label (optional)' : 'Name'} value={form.name} onChange={set('name')}/>{tab !== 'invoices' && <input required className={input} placeholder="Unique code" value={form.code} onChange={set('code')}/>}</>}
    {tab === 'components' && <><select className={input} value={form.categoryId} onChange={set('categoryId')}><option value="">No category</option>{categories.filter((x) => x.active).map((x) => <option key={x.id} value={x.id}>{x.name}</option>)}</select><select className={input} value={form.frequency} onChange={set('frequency')}>{['ONE_TIME','MONTHLY','QUARTERLY','HALF_YEARLY','ANNUAL','PER_TERM','PER_EXAMINATION','CUSTOM'].map((x) => <option key={x}>{x.replaceAll('_',' ')}</option>)}</select><input className={input} type="number" min="0.01" step="0.01" placeholder="Default amount (optional)" value={form.defaultAmount} onChange={set('defaultAmount')}/></>}
    {tab === 'invoices' && <><input required className={input} value={form.academicSession} onChange={set('academicSession')} placeholder="Academic session"/><input className={input} value={form.className} onChange={set('className')} placeholder="Class filter (blank = all)"/><input className={input} value={form.section} onChange={set('section')} placeholder="Section filter"/></>}
    {tab === 'refunds' && <><input required className={input} value={form.paymentId} onChange={set('paymentId')} placeholder="Original payment ID"/><input required className={input} type="number" min="0.01" step="0.01" value={form.refundAmount} onChange={set('refundAmount')} placeholder="Refund amount"/><input required className={input} value={form.reason} onChange={set('reason')} placeholder="Approval reason"/></>}
    {tab === 'transport' && <><input className={input} value={form.vehicleNumber} onChange={set('vehicleNumber')} placeholder="Vehicle number (optional)"/><input className={input} value={form.stopName} onChange={set('stopName')} placeholder="First stop"/><input className={input} type="number" min="0.01" step="0.01" value={form.monthlyAmount} onChange={set('monthlyAmount')} placeholder="Monthly amount"/></>}
  </div><button disabled={busy} className={`${button} mt-4`}>{busy ? 'Working…' : tab === 'invoices' ? 'Generate invoices' : tab === 'refunds' ? 'Process refund' : 'Save'}</button></form>
  <div className={card}>{busy && !rows.length ? <div className="animate-pulse py-10 text-center text-slate-500">Loading…</div> : !rows.length ? <div className="py-10 text-center text-slate-500">No records yet.</div> : <div className="space-y-2">{rows.map((row) => <div key={row.id} className="grid gap-2 rounded-xl border p-4 text-sm dark:border-slate-800 sm:grid-cols-[1fr_auto]"><div><p className="font-semibold">{row.name || row.invoiceNumber || row.refundNumber}</p><p className="text-xs text-slate-500">{row.code || row.billingPeriod || row.payment?.paymentNumber || `${row.stops?.length || 0} stops`}</p></div><div className="text-left sm:text-right"><p className="font-semibold">{row.outstandingMinor != null ? money(row.outstandingMinor) : row.amountMinor != null ? money(row.amountMinor) : row._count ? `${row._count.components} components` : ''}</p><p className="text-xs text-slate-500">{row.status || (row.active ? 'ACTIVE' : 'INACTIVE')}</p></div></div>)}</div>}</div></div></DashboardLayout>;
}
