import React, { useEffect, useMemo, useState } from 'react';
import { AlertCircle, BadgeIndianRupee, CheckCircle2, Clock3, CreditCard, Download, Plus, Search, WalletCards } from 'lucide-react';
import toast from 'react-hot-toast';
import DashboardLayout from '../../layouts/DashboardLayout';
import { authService } from '../../services/authService';
import { feeService } from '../../services/feeService';

const money = (minor = 0, settings = {}) => new Intl.NumberFormat(settings.locale || 'en-IN', { style: 'currency', currency: settings.currencyCode || 'INR' }).format(Number(minor) / (10 ** (settings.decimalPrecision ?? 2)));
const card = 'rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900';
const input = 'h-10 w-full rounded-xl border border-slate-300 bg-white px-3 text-sm dark:border-slate-700 dark:bg-slate-950';

function State({ loading, error, empty, children }) {
  if (loading) return <div className={`${card} animate-pulse`}><div className="h-5 w-40 rounded bg-slate-200 dark:bg-slate-800" /><div className="mt-4 h-24 rounded bg-slate-100 dark:bg-slate-800/60" /></div>;
  if (error) return <div className={`${card} flex gap-3 text-red-700 dark:text-red-300`}><AlertCircle />{error}</div>;
  if (empty) return <div className={`${card} text-center text-slate-500`}>No fee records are available for this academic session.</div>;
  return children;
}

function Summary({ dashboard, settings }) {
  const items = [['Expected', dashboard?.totals?.expected, WalletCards], ['Collected', dashboard?.totals?.collected, CheckCircle2], ['Pending', dashboard?.totals?.pending, Clock3], ['Overdue', dashboard?.totals?.overdue, AlertCircle]];
  return <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{items.map(([label, value, Icon]) => <div className={card} key={label}><div className="flex items-center justify-between text-slate-500"><span>{label}</span><Icon size={19} /></div><p className="mt-3 text-2xl font-bold">{money(value, settings)}</p></div>)}</div>;
}

function StructureForm({ onDone }) {
  const [form, setForm] = useState({ academicSession: '2026-27', name: '', code: '', mode: 'COMPONENT_BASED', componentName: 'Tuition Fee', componentCode: 'TUITION', amount: '' });
  const [busy, setBusy] = useState(false);
  const submit = async (event) => { event.preventDefault(); setBusy(true); try { await feeService.createStructure({ academicSession: form.academicSession, name: form.name, code: form.code, mode: form.mode, components: [{ name: form.componentName, code: form.componentCode, amountMinor: Math.round(Number(form.amount) * 100), frequency: 'MONTHLY', mandatory: true }] }); toast.success('Draft fee structure saved'); onDone(); } catch (e) { toast.error(e.response?.data?.message || 'Could not save structure'); } finally { setBusy(false); } };
  return <form onSubmit={submit} className={`${card} grid gap-4 md:grid-cols-2`}><div className="md:col-span-2"><h2 className="text-lg font-semibold">New fee structure draft</h2><p className="text-sm text-slate-500">A focused first step; add more components through versioned drafts.</p></div>{[['Academic session','academicSession'],['Structure name','name'],['Structure code','code'],['Component name','componentName'],['Component code','componentCode'],['Monthly amount','amount']].map(([label,key])=><label key={key} className="text-sm"><span className="mb-1 block font-medium">{label}</span><input required className={input} value={form[key]} type={key==='amount'?'number':'text'} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>)}<button disabled={busy} className="md:col-span-2 inline-flex h-11 items-center justify-center gap-2 rounded-xl bg-blue-600 font-semibold text-white disabled:opacity-60"><Plus size={18}/>{busy?'Saving…':'Save draft'}</button></form>;
}

function AdminView({ settings, refreshSettings }) {
  const [dashboard,setDashboard]=useState(); const [structures,setStructures]=useState([]); const [showForm,setShowForm]=useState(false); const [error,setError]=useState('');
  const load=async()=>{try{setError('');const [d,s]=await Promise.all([feeService.dashboard(),feeService.structures()]);setDashboard(d);setStructures(s);}catch(e){setError(e.response?.data?.message||'Unable to load fee module');}};
  useEffect(()=>{load();},[]);
  const toggle=async()=>{try{await feeService.saveSettings({...settings,enabled:!settings.enabled,approvalThresholdMinor:Number(settings.approvalThresholdMinor||50000)});await refreshSettings();toast.success(`Fee module ${settings.enabled?'disabled':'enabled'}`);}catch(e){toast.error(e.response?.data?.message||'Could not update settings');}};
  return <div className="space-y-5"><div className={`${card} flex flex-col justify-between gap-4 sm:flex-row sm:items-center`}><div><h2 className="font-semibold">Module status</h2><p className="text-sm text-slate-500">{settings.enabled?'Enabled for this school':'Disabled for this school'}</p></div><button onClick={toggle} className="rounded-xl bg-slate-900 px-4 py-2 text-sm font-semibold text-white dark:bg-white dark:text-slate-900">{settings.enabled?'Disable':'Enable'} module</button></div><Summary dashboard={dashboard} settings={settings}/><State error={error} empty={!structures.length}><div className={card}><div className="mb-4 flex items-center justify-between"><div><h2 className="text-lg font-semibold">Fee structures</h2><p className="text-sm text-slate-500">Draft, publish, and preserve historical versions.</p></div><button onClick={()=>setShowForm(!showForm)} className="rounded-xl bg-blue-600 px-4 py-2 text-sm font-semibold text-white">Create</button></div><div className="space-y-3">{structures.map(s=><div key={s.id} className="flex flex-col justify-between gap-3 rounded-xl border border-slate-200 p-4 dark:border-slate-800 sm:flex-row"><div><p className="font-semibold">{s.name} <span className="text-xs text-slate-500">v{s.version}</span></p><p className="text-sm text-slate-500">{s.academicSession} · {s.components.length} components</p></div><span className="self-start rounded-full bg-slate-100 px-3 py-1 text-xs font-semibold dark:bg-slate-800">{s.status}</span></div>)}</div></div></State>{showForm&&<StructureForm onDone={()=>{setShowForm(false);load();}}/>}</div>;
}

function CollectionView({ settings }) {
  const [q,setQ]=useState(''); const [students,setStudents]=useState([]); const [selected,setSelected]=useState(); const [fees,setFees]=useState(); const [amount,setAmount]=useState(''); const [method,setMethod]=useState('CASH'); const [busy,setBusy]=useState(false);
  const search=async()=>{try{setStudents(await feeService.searchStudents(q));}catch(e){toast.error(e.response?.data?.message||'Search failed');}};
  const choose=async student=>{setSelected(student);setFees(await feeService.student(student.id,student.session));};
  const collect=async()=>{setBusy(true);try{await feeService.collect({studentId:selected.id,academicSession:selected.session,amountMinor:Math.round(Number(amount)*100),method},crypto.randomUUID());toast.success('Payment recorded and receipt generated');setAmount('');setFees(await feeService.student(selected.id,selected.session));}catch(e){toast.error(e.response?.data?.message||'Payment failed');}finally{setBusy(false);}};
  return <div className="grid gap-5 lg:grid-cols-[360px_1fr]"><div className={card}><h2 className="font-semibold">Student search</h2><div className="mt-3 flex gap-2"><input className={input} placeholder="Name, admission no, mobile…" value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==='Enter'&&search()}/><button onClick={search} className="rounded-xl bg-blue-600 px-3 text-white" aria-label="Search"><Search size={18}/></button></div><div className="mt-4 space-y-2">{students.map(s=><button key={s.id} onClick={()=>choose(s)} className="w-full rounded-xl border border-slate-200 p-3 text-left hover:bg-slate-50 dark:border-slate-800 dark:hover:bg-slate-800"><p className="font-medium">{s.studentFirstName} {s.studentLastName}</p><p className="text-xs text-slate-500">{s.admissionNo||s.studentUserId} · {s.className} {s.section||''}</p></button>)}</div></div><State empty={!selected}>{fees&&<div className="space-y-5"><Summary dashboard={{totals:{expected:fees.totals.expected,collected:fees.totals.paid,pending:fees.totals.pending,overdue:0}}} settings={settings}/><div className={card}><h2 className="text-lg font-semibold">Collect fee for {fees.student.studentFirstName}</h2><div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="text-sm">Amount<input className={`${input} mt-1`} type="number" min="0.01" value={amount} onChange={e=>setAmount(e.target.value)}/></label><label className="text-sm">Payment method<select className={`${input} mt-1`} value={method} onChange={e=>setMethod(e.target.value)}>{['CASH','CHEQUE','BANK_TRANSFER','UPI','NEFT','RTGS','IMPS','DEMAND_DRAFT','POS_CARD','OTHER'].map(x=><option key={x}>{x}</option>)}</select></label></div><button disabled={busy||!amount} onClick={collect} className="mt-4 w-full rounded-xl bg-emerald-600 py-3 font-semibold text-white disabled:opacity-50">{busy?'Recording…':'Record offline payment'}</button><button disabled className="mt-2 w-full rounded-xl border border-slate-300 py-3 text-sm text-slate-500 dark:border-slate-700">Online Payment — Coming Soon</button></div></div>}</State></div>;
}

function MyFees({ settings }) {
  const [fees,setFees]=useState(); const [error,setError]=useState(''); useEffect(()=>{feeService.myFees().then(setFees).catch(e=>setError(e.response?.data?.message||'Unable to load fees'));},[]);
  return <State loading={!fees&&!error} error={error} empty={fees&&!fees.account}><div className="space-y-5">{fees&&<><Summary dashboard={{totals:{expected:fees.totals.expected,collected:fees.totals.paid,pending:fees.totals.pending,overdue:0}}} settings={settings}/><div className={card}><h2 className="text-lg font-semibold">Installments and receipts</h2><div className="mt-4 space-y-3">{fees.account?.charges.map(c=><div key={c.id} className="flex justify-between rounded-xl border border-slate-200 p-4 dark:border-slate-800"><div><p className="font-medium">{c.installmentName}</p><p className="text-xs text-slate-500">Due {new Date(c.dueDate).toLocaleDateString()}</p></div><div className="text-right"><p className="font-semibold">{money(c.baseAmountMinor,settings)}</p><span className="text-xs">{c.status.replaceAll('_',' ')}</span></div></div>)}</div>{fees.account?.payments.map(p=>p.receipt&&<a key={p.id} href={feeService.receiptPdfUrl(p.receipt.id)} className="mt-3 inline-flex items-center gap-2 text-sm font-semibold text-blue-600"><Download size={16}/> {p.receipt.receiptNumber}</a>)}</div><div className={`${card} border-dashed text-center`}><CreditCard className="mx-auto text-slate-400"/><p className="mt-2 font-semibold">Online Payment</p><p className="text-sm text-slate-500">Coming Soon — secure payment gateway integration will be available in a future update.</p><button disabled className="mt-3 rounded-xl bg-slate-200 px-5 py-2 text-sm text-slate-500 dark:bg-slate-800">Pay online</button></div></>}</div></State>;
}

export default function FeePortalPage(){const user=authService.getCurrentUser();const role=user?.role;const [settings,setSettings]=useState({});const [error,setError]=useState('');const refresh=()=>feeService.settings().then(setSettings).catch(e=>setError(e.response?.data?.message||'Fee module unavailable'));useEffect(()=>{let mounted=true;const run=async()=>{try{await refresh();}finally{if(!mounted) return;}};run();return()=>{mounted=false;};},[]);const content=useMemo(()=>role==='FEE_MANAGER'?<CollectionView settings={settings}/>:['STUDENT','PARENT'].includes(role)?<MyFees settings={settings}/>:<AdminView settings={settings} refreshSettings={refresh}/>,[role,settings]);return <DashboardLayout role={role}><div><div className="mb-5"><div className="flex items-center gap-2 text-blue-600"><BadgeIndianRupee/><span className="text-sm font-semibold">Financial management</span></div><h1 className="mt-1 text-2xl font-bold">{role==='FEE_MANAGER'?'Fee collection':role==='PARENT'?'Children fee overview':role==='STUDENT'?'My fees':'Fee dashboard'}</h1><p className="text-sm text-slate-500">Secure, school-scoped fee records for {user?.name}.</p></div>{error?<State error={error}/>:content}</div></DashboardLayout>}
