import React, { useMemo, useState } from 'react';
import { AlertTriangle, ArrowLeft, ArrowRight, Check, Plus, Trash2 } from 'lucide-react';
import toast from 'react-hot-toast';
import { feeService } from '../../services/feeService';

const steps = ['Basic details','Fee mode','Classes & sections','Fee components','Installments','Due dates','Late fee rules','Discounts & scholarships','Exclusions & overrides','Preview','Publish'];
const field = 'h-11 w-full rounded-xl border border-slate-300 bg-white px-3 dark:border-slate-700 dark:bg-slate-950';
const panel = 'rounded-2xl border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900';
const initial = { academicSession: '2026-27', name: '', code: '', description: '', mode: 'COMPONENT_BASED', targetType: 'SCHOOL', targetValue: '', scheduleStart: '2026-04-10', components: [{ name: 'Tuition Fee', code: 'TUITION', amount: '', frequency: 'MONTHLY', dueDay: 10, gracePeriodDays: 5, lateFeeRule: { type: 'DAILY', amountMinor: 1000, maximumMinor: 50000 } }], discountNotes: '', exclusions: '' };

export default function FeeStructureWizard({ onClose, onPublished }) {
  const [step,setStep]=useState(0); const [form,setForm]=useState(initial); const [structure,setStructure]=useState(); const [preview,setPreview]=useState(); const [busy,setBusy]=useState(false);
  const update=(key,value)=>setForm((old)=>({...old,[key]:value})); const updateComponent=(index,key,value)=>setForm((old)=>({...old,components:old.components.map((c,i)=>i===index?{...c,[key]:value}:c)}));
  const projected=useMemo(()=>form.components.reduce((sum,c)=>sum+(Number(c.amount)||0)*({MONTHLY:12,QUARTERLY:4,HALF_YEARLY:2,ANNUAL:1,ONE_TIME:1}[c.frequency]||1),0),[form.components]);
  const saveDraft=async()=>{if(structure)return structure; const result=await feeService.createStructure({academicSession:form.academicSession,name:form.name,code:form.code,description:form.description,mode:form.mode,components:form.components.map((c,i)=>({...c,amountMinor:Math.round(Number(c.amount)*100),lateFeeRule:c.lateFeeRule,displayOrder:i}))});setStructure(result);return result;};
  const next=async()=>{if(step===9&&!preview){setBusy(true);try{const draft=await saveDraft();setPreview(await feeService.previewAssignment({feeStructureId:draft.id,targetType:form.targetType,targetValue:form.targetValue||undefined}));}catch(e){toast.error(e.response?.data?.message||'Preview failed');return;}finally{setBusy(false);}} setStep((s)=>Math.min(10,s+1));};
  const publish=async()=>{setBusy(true);try{const draft=await saveDraft();await feeService.publishStructure(draft.id);const result=await feeService.publishAssignment({feeStructureId:draft.id,targetType:form.targetType,targetValue:form.targetValue||undefined,scheduleStart:form.scheduleStart});toast.success(`${result.chargesCreated} charges generated for ${result.affectedStudents} students`);onPublished();}catch(e){toast.error(e.response?.data?.message||'Publishing failed');}finally{setBusy(false);}};
  const content=()=>{
    if(step===0)return <div className="grid gap-4 md:grid-cols-2">{[['Structure name','name'],['Structure code','code'],['Academic session','academicSession']].map(([label,key])=><label key={key}>{label}<input className={`${field} mt-1`} value={form[key]} onChange={e=>update(key,e.target.value)} required/></label>)}<label className="md:col-span-2">Description<textarea className={`${field} mt-1 h-24 py-3`} value={form.description} onChange={e=>update('description',e.target.value)}/></label></div>;
    if(step===1)return <div className="grid gap-4 sm:grid-cols-2">{[['SIMPLE','Simple combined fee'],['COMPONENT_BASED','Component-based fee']].map(([value,label])=><button key={value} onClick={()=>update('mode',value)} className={`rounded-2xl border p-6 text-left ${form.mode===value?'border-blue-500 bg-blue-50 dark:bg-blue-950/30':'border-slate-200 dark:border-slate-800'}`}><p className="font-semibold">{label}</p><p className="mt-1 text-sm text-slate-500">{value==='SIMPLE'?'One clear charge title.':'Detailed configurable components.'}</p></button>)}</div>;
    if(step===2)return <div className="grid gap-4 md:grid-cols-2"><label>Assignment level<select className={`${field} mt-1`} value={form.targetType} onChange={e=>update('targetType',e.target.value)}>{['SCHOOL','CLASS','SECTION','CATEGORY','STUDENT'].map(x=><option key={x}>{x}</option>)}</select></label>{form.targetType!=='SCHOOL'&&<label>Target value<input className={`${field} mt-1`} placeholder="Class, section, category, or student ID" value={form.targetValue} onChange={e=>update('targetValue',e.target.value)}/></label>}</div>;
    if(step===3)return <div className="space-y-4">{form.components.map((c,i)=><div key={i} className="grid gap-3 rounded-xl border border-slate-200 p-4 dark:border-slate-800 md:grid-cols-5"><input className={field} placeholder="Name" value={c.name} onChange={e=>updateComponent(i,'name',e.target.value)}/><input className={field} placeholder="Code" value={c.code} onChange={e=>updateComponent(i,'code',e.target.value)}/><input className={field} type="number" placeholder="Amount" value={c.amount} onChange={e=>updateComponent(i,'amount',e.target.value)}/><select className={field} value={c.frequency} onChange={e=>updateComponent(i,'frequency',e.target.value)}>{['ONE_TIME','MONTHLY','QUARTERLY','HALF_YEARLY','ANNUAL','PER_TERM','PER_SEMESTER'].map(x=><option key={x}>{x}</option>)}</select><button onClick={()=>update('components',form.components.filter((_,n)=>n!==i))} className="rounded-xl text-red-600"><Trash2 className="mx-auto"/></button></div>)}<button onClick={()=>update('components',[...form.components,{name:'',code:'',amount:'',frequency:'ONE_TIME',dueDay:10,gracePeriodDays:0}])} className="inline-flex items-center gap-2 rounded-xl border px-4 py-2"><Plus size={16}/>Add component</button></div>;
    if(step===4)return <div><p className="text-sm text-slate-500">Installments are generated from each component frequency.</p><div className="mt-4 grid gap-3 sm:grid-cols-3">{form.components.map(c=><div key={c.code} className="rounded-xl border p-4 dark:border-slate-800"><p className="font-medium">{c.name}</p><p className="text-sm text-slate-500">{c.frequency.replaceAll('_',' ')}</p></div>)}</div></div>;
    if(step===5)return <label>Schedule starts<input type="date" className={`${field} mt-1 max-w-sm`} value={form.scheduleStart} onChange={e=>update('scheduleStart',e.target.value)}/></label>;
    if(step===6)return <div className="space-y-3">{form.components.map((c,i)=><div key={c.code} className="grid gap-3 rounded-xl border p-4 dark:border-slate-800 sm:grid-cols-3"><span className="font-medium">{c.name}</span><label>Due day<input className={`${field} mt-1`} type="number" value={c.dueDay} onChange={e=>updateComponent(i,'dueDay',Number(e.target.value))}/></label><label>Grace days<input className={`${field} mt-1`} type="number" value={c.gracePeriodDays} onChange={e=>updateComponent(i,'gracePeriodDays',Number(e.target.value))}/></label></div>)}</div>;
    if(step===7)return <div><p className="text-sm text-slate-500">Late-fee rules are saved per component. Defaults use a daily capped fine and can be changed through the component API.</p></div>;
    if(step===8)return <label>Scholarship and discount policy notes<textarea className={`${field} mt-1 h-28 py-3`} value={form.discountNotes} onChange={e=>update('discountNotes',e.target.value)}/></label>;
    if(step===9)return <label>Exclusions or override notes<textarea className={`${field} mt-1 h-28 py-3`} value={form.exclusions} onChange={e=>update('exclusions',e.target.value)}/></label>;
    if(step===10)return <div className="space-y-4">{preview?<><div className="grid gap-3 sm:grid-cols-3"><Metric label="Affected students" value={preview.affectedStudents}/><Metric label="Projected annual fee" value={(preview.projectedRevenueMinor/100).toLocaleString()}/><Metric label="Conflicts" value={preview.conflicts.length}/></div>{preview.conflicts.length>0&&<div className="flex gap-2 rounded-xl bg-amber-50 p-4 text-amber-800 dark:bg-amber-950/30 dark:text-amber-200"><AlertTriangle/><span>Higher-priority assignments protect {preview.conflicts.length} student records from duplicate charges.</span></div>}<div className="space-y-2">{preview.classImpact.map(x=><div key={x.classSection} className="flex justify-between rounded-xl border p-3 dark:border-slate-800"><span>{x.classSection}</span><span>{x.students} students · {(x.expectedMinor/100).toLocaleString()}</span></div>)}</div></>:<p>Preparing preview…</p>}</div>;
  };
  return <div className={panel}><div className="mb-5 flex items-center justify-between"><div><p className="text-sm text-blue-600">Step {step+1} of 11</p><h2 className="text-xl font-bold">{steps[step]}</h2></div><button onClick={onClose} className="text-sm text-slate-500">Close</button></div><div className="mb-6 h-2 overflow-hidden rounded-full bg-slate-100 dark:bg-slate-800"><div className="h-full bg-blue-600 transition-all" style={{width:`${((step+1)/11)*100}%`}}/></div>{content()}<div className="sticky bottom-0 mt-8 flex justify-between border-t bg-white/95 pt-4 backdrop-blur dark:border-slate-800 dark:bg-slate-900/95"><button disabled={step===0} onClick={()=>setStep(s=>s-1)} className="inline-flex items-center gap-2 rounded-xl border px-4 py-2 disabled:opacity-40"><ArrowLeft size={16}/>Back</button>{step<10?<button disabled={busy||!form.name||!form.code||!form.components.length} onClick={next} className="inline-flex items-center gap-2 rounded-xl bg-blue-600 px-5 py-2 font-semibold text-white disabled:opacity-50">{busy?'Calculating…':'Continue'}<ArrowRight size={16}/></button>:<button disabled={busy||!preview} onClick={publish} className="inline-flex items-center gap-2 rounded-xl bg-emerald-600 px-5 py-2 font-semibold text-white disabled:opacity-50"><Check size={16}/>{busy?'Publishing…':'Publish and generate charges'}</button>}</div></div>;
}
function Metric({label,value}){return <div className="rounded-xl border p-4 dark:border-slate-800"><p className="text-sm text-slate-500">{label}</p><p className="mt-1 text-xl font-bold">{value}</p></div>}
