import React from 'react';
import { useQuery } from '@tanstack/react-query';
import { Calendar, CheckCircle, ListTodo } from 'lucide-react';
import DashboardLayout from '../../layouts/DashboardLayout';
import { WelcomeCard, SummaryCard } from '../../components/DashboardCards';
import { authService } from '../../services/authService';
import { dashboardService } from '../../services/dashboardService';

export default function StaffDashboard() {
  const user = authService.getCurrentUser();
  const { data, isLoading, isError } = useQuery({ queryKey: ['dashboard-summary', 'staff'], queryFn: dashboardService.summary }); const stats = data?.stats || {};
  return <DashboardLayout role="STAFF"><div className="space-y-6"><WelcomeCard name={user?.name} role="STAFF"/>{isError && <div className="rounded-xl bg-rose-50 p-4 text-sm text-rose-700">Unable to load staff operations.</div>}<div className="grid gap-6 md:grid-cols-3"><SummaryCard icon={<CheckCircle className="h-8 w-8"/>} label="Completed Tasks" value={isLoading ? '…' : stats.tasksCompleted || 0} color="green"/><SummaryCard icon={<ListTodo className="h-8 w-8"/>} label="Open Tasks" value={isLoading ? '…' : stats.tasksRemaining || 0} color="blue"/><SummaryCard icon={<Calendar className="h-8 w-8"/>} label="Events This Week" value={isLoading ? '…' : stats.scheduledEvents || 0} color="orange"/></div><div className="grid gap-6 lg:grid-cols-2"><section className="rounded-xl bg-white p-6 shadow dark:bg-gray-800"><h2 className="text-lg font-bold">My tasks</h2><div className="mt-4 space-y-3">{(data?.tasks || []).map((task) => <div key={task.id} className="rounded-xl border p-4 dark:border-slate-700"><div className="flex justify-between gap-3"><p className="font-semibold">{task.title}</p><span className={`rounded-full px-2 py-1 text-[10px] font-bold ${task.isCompleted ? 'bg-emerald-100 text-emerald-700' : 'bg-amber-100 text-amber-700'}`}>{task.isCompleted ? 'COMPLETED' : task.priority}</span></div>{task.description && <p className="mt-1 text-sm text-slate-500">{task.description}</p>}</div>)}{!isLoading && !(data?.tasks || []).length && <p className="text-sm text-slate-500">No tasks assigned. Tasks created in Widget Hub appear here.</p>}</div></section><section className="rounded-xl bg-white p-6 shadow dark:bg-gray-800"><h2 className="text-lg font-bold">School calendar this week</h2><div className="mt-4 space-y-3">{(data?.events || []).map((event) => <div key={event.id} className="rounded-xl border p-4 dark:border-slate-700"><p className="font-semibold">{event.title || event.type.replace(/_/g, ' ')}</p><p className="mt-1 text-xs text-slate-500">{new Date(`${event.date}T00:00:00`).toLocaleDateString(undefined, { weekday: 'long', month: 'short', day: 'numeric' })} · {event.type.replace(/_/g, ' ')}</p></div>)}{!isLoading && !(data?.events || []).length && <p className="text-sm text-slate-500">No scheduled events in the next seven days.</p>}</div></section></div></div></DashboardLayout>;
}
