import React from 'react';
import { useQuery } from '@tanstack/react-query';
import { motion } from 'framer-motion';
import { Activity, BadgeIndianRupee, BookOpen, CalendarCheck, ClipboardList, TrendingUp } from 'lucide-react';
import DashboardLayout from '../../layouts/DashboardLayout';
import { studentAcademicsService as api } from '../../services/studentAcademicsService';
import { feeService } from '../../services/feeService';
import { ActionLink, Badge, Empty, ErrorState, Loading, Panel, Progress } from '../../components/student/StudentUI';

const quick = [
  ['My Fees', '/student/fees', BadgeIndianRupee],
  ['Academic Analytics', '/analytics/students', Activity],
  ['My Attendance', '/student/attendance', CalendarCheck],
  ['My Subjects', '/student/subjects', BookOpen],
  ['Pending Polls', '/student/polls/pending', ClipboardList],
  ['My Performance', '/student/performance', TrendingUp],
];
const money = (minor = 0) => new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 }).format(Number(minor) / 100);

export default function StudentDashboard() {
  const dashboard = useQuery({ queryKey: ['student-dashboard'], queryFn: api.getDashboard });
  const fees = useQuery({ queryKey: ['student-dashboard-fees'], queryFn: () => feeService.myFees() });
  if (dashboard.isLoading) return <DashboardLayout role="STUDENT"><Loading /></DashboardLayout>;
  if (dashboard.isError) return <DashboardLayout role="STUDENT"><ErrorState error={dashboard.error} retry={dashboard.refetch} /></DashboardLayout>;
  const data = dashboard.data;
  return <DashboardLayout role="STUDENT"><motion.div initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} className="space-y-5">
    <Panel className="bg-gradient-to-br from-indigo-700 to-slate-900 text-white"><div className="flex flex-col justify-between gap-4 md:flex-row"><div><p className="text-sm text-indigo-200">{data.school?.schoolName}</p><h1 className="mt-2 text-3xl font-black">Hello, {data.student.name}</h1><p className="mt-2 text-indigo-100">Class {data.student.className} · Section {data.student.sectionName} · {data.student.session}</p></div><div className="rounded-2xl bg-white/10 p-4"><p className="text-xs uppercase text-indigo-200">Class teacher</p><p className="mt-1 font-bold">{data.classTeacher?.name || 'Assignment pending'}</p><p className="text-sm text-indigo-100">{data.classTeacher?.subject || ''}</p></div></div></Panel>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{quick.map(([label, to, Icon]) => <ActionLink key={to} to={to}><Panel className="w-full transition hover:-translate-y-0.5 hover:border-indigo-300"><Icon /><p className="mt-4 text-base text-slate-900 dark:text-white">{label}</p></Panel></ActionLink>)}</div>
    {fees.isSuccess && <ActionLink to="/student/fees"><Panel className="w-full border-indigo-200 bg-gradient-to-r from-indigo-50 to-blue-50 dark:border-indigo-900 dark:from-indigo-950/40 dark:to-slate-900"><div className="flex flex-wrap items-center justify-between gap-5"><div><p className="text-xs font-bold uppercase tracking-wide text-indigo-600">My published fee record</p><h2 className="mt-1 text-xl font-black text-slate-900 dark:text-white">{fees.data.assignedStructures?.length || 0} shared fee structure{fees.data.assignedStructures?.length === 1 ? '' : 's'}</h2><p className="mt-1 text-sm text-slate-500">Open your complete structure, installment schedule, and receipts.</p></div><div className="grid grid-cols-3 gap-6 text-right"><div><p className="text-xs text-slate-500">Expected</p><p className="font-black text-slate-900 dark:text-white">{money(fees.data.totals.expected)}</p></div><div><p className="text-xs text-slate-500">Paid</p><p className="font-black text-emerald-700">{money(fees.data.totals.paid)}</p></div><div><p className="text-xs text-slate-500">Pending</p><p className="font-black text-amber-700">{money(fees.data.totals.pending)}</p></div></div></div></Panel></ActionLink>}
    {fees.isError && <Panel><p className="text-sm text-red-600">Fee record could not be loaded. <button className="font-bold" onClick={() => fees.refetch()}>Retry</button></p></Panel>}
    <div className="grid gap-4 md:grid-cols-4"><Panel><p className="text-sm text-slate-500">Attendance</p><p className="mt-2 text-3xl font-black">{data.attendance.percentage == null ? '—' : `${data.attendance.percentage}%`}</p><Progress value={data.attendance.percentage} /></Panel><Panel><p className="text-sm text-slate-500">Subjects</p><p className="mt-2 text-3xl font-black">{data.counts.subjects}</p></Panel><Panel><p className="text-sm text-slate-500">Pending polls</p><p className="mt-2 text-3xl font-black">{data.counts.pendingPolls}</p></Panel><Panel><p className="text-sm text-slate-500">Performance</p><p className="mt-2 text-3xl font-black">{data.performance.score == null ? '—' : `${data.performance.score}%`}</p><Badge>{data.performance.label}</Badge></Panel></div>
    <div className="grid gap-5 xl:grid-cols-2"><Panel><div className="flex justify-between"><h2 className="text-lg font-black">Subject overview</h2><ActionLink to="/student/subjects">View all</ActionLink></div><div className="mt-4 space-y-4">{data.subjects.length ? data.subjects.map((subject) => <div key={subject.id}><div className="flex justify-between text-sm"><span className="font-bold">{subject.subjectName}</span><span>{subject.performance.score == null ? 'Not evaluated' : `${subject.performance.score}%`}</span></div><Progress value={subject.performance.score} /></div>) : <Empty>No subjects are assigned to your section yet.</Empty>}</div></Panel><Panel><h2 className="text-lg font-black">Strengths and focus areas</h2><p className="mt-3 text-sm text-slate-600 dark:text-slate-300">{data.performance.summary}</p><div className="mt-4 grid gap-3 sm:grid-cols-2"><div><p className="text-xs font-bold uppercase text-emerald-600">Strongest subject</p><p className="mt-1 font-bold">{data.strongestSubject?.subjectName || 'Not evaluated'}</p></div><div><p className="text-xs font-bold uppercase text-amber-600">Needs focus</p><p className="mt-1 font-bold">{data.improvementSubject?.subjectName || 'Not evaluated'}</p></div></div></Panel></div>
    <Panel><div className="flex justify-between"><h2 className="text-lg font-black">Recently shared resources</h2><span className="text-xs text-slate-500">Open resources inside their chapter</span></div><div className="mt-4 grid gap-3 md:grid-cols-2">{data.recentResources.length ? data.recentResources.map((resource) => <ActionLink key={resource.id} to={resource.chapter ? `/student/subjects/${resource.subject.id}/chapters/${resource.chapter.id}` : `/student/subjects/${resource.subject.id}`}><div className="w-full rounded-xl border border-slate-200 p-4 dark:border-slate-700"><p className="font-bold text-slate-900 dark:text-white">{resource.title}</p><p className="text-xs text-slate-500">{resource.subject.subjectName}{resource.chapter ? ` · ${resource.chapter.chapterName}` : ''}</p></div></ActionLink>) : <Empty>No resources have been shared yet.</Empty>}</div></Panel>
  </motion.div></DashboardLayout>;
}
