import api from './api';

const data = (response) => response.data.data;
export const feeService = {
  settings: () => api.get('/fees/settings').then(data),
  saveSettings: (payload) => api.put('/fees/settings', payload).then(data),
  structures: (academicSession) => api.get('/fees/structures', { params: { academicSession } }).then(data),
  structure: (id) => api.get(`/fees/structures/${id}`).then(data),
  createStructure: (payload) => api.post('/fees/structures', payload).then(data),
  updateStructure: (id, payload) => api.patch(`/fees/structures/${id}`, payload).then(data),
  reviseStructure: (id, reason) => api.post(`/fees/structures/${id}/revise`, { reason }).then(data),
  publishStructure: (id) => api.post(`/fees/structures/${id}/publish`).then(data),
  categories: (params) => api.get('/fees/categories', { params }).then(data),
  createCategory: (payload) => api.post('/fees/categories', payload).then(data),
  updateCategory: (id, payload) => api.patch(`/fees/categories/${id}`, payload).then(data),
  components: (params) => api.get('/fees/components', { params }).then(data),
  createComponent: (payload) => api.post('/fees/components', payload).then(data),
  invoices: (params) => api.get('/fees/invoices', { params }).then(data),
  generateInvoices: (payload, key = crypto.randomUUID()) => api.post('/fees/invoices/generate', payload, { headers: { 'Idempotency-Key': key } }).then(data),
  refunds: (params) => api.get('/fees/refunds', { params }).then(data),
  processRefund: (payload, key = crypto.randomUUID()) => api.post('/fees/refunds', payload, { headers: { 'Idempotency-Key': key } }).then(data),
  transportRoutes: () => api.get('/fees/transport/routes').then(data),
  transportAssignments: (params) => api.get('/fees/transport/assignments', { params }).then(data),
  createTransportRoute: (payload) => api.post('/fees/transport/routes', payload).then(data),
  assignTransport: (payload) => api.post('/fees/transport/assignments', payload).then(data),
  cancelTransport: (id, payload) => api.patch(`/fees/transport/assignments/${id}/cancel`, payload).then(data),
  dashboard: (academicSession) => api.get('/fees/dashboard', { params: { academicSession } }).then(data),
  searchStudents: (q) => api.get('/fees/students/search', { params: { q } }).then(data),
  hierarchy: (academicSession) => api.get('/fees/hierarchy', { params: { academicSession } }).then(data),
  teacherSections: () => api.get('/fees/teacher/sections').then(data),
  teacherSectionFees: (sectionId, academicSession) => api.get(`/fees/teacher/sections/${sectionId}`, { params: { academicSession } }).then(data),
  teacherStudentFees: (studentId, academicSession) => api.get(`/fees/teacher/students/${studentId}`, { params: { academicSession } }).then(data),
  teacherReminder: (payload) => api.post('/fees/teacher/reminders', payload).then(data),
  student: (studentId, academicSession) => api.get(`/fees/students/${studentId}`, { params: { academicSession } }).then(data),
  myFees: (academicSession, studentId) => api.get('/fees/my', { params: { academicSession, ...(studentId ? { studentId } : {}) } }).then(data),

  collect: (payload, key) => api.post('/fees/payments', payload, { headers: { 'Idempotency-Key': key } }).then(data),
  approvals: () => api.get('/fees/approvals').then(data),
  downloadReceipt: async (id, filename = 'fee-receipt.pdf') => {
    const response = await api.get(`/fees/receipts/${id}/pdf`, { responseType: 'blob' });
    const url = URL.createObjectURL(response.data); const link = document.createElement('a'); link.href = url; link.download = filename; link.click(); URL.revokeObjectURL(url);
  },
  previewAssignment: (payload) => api.post('/fees/assignments/preview', payload).then(data),
  publishAssignment: (payload) => api.post('/fees/assignments/publish', payload).then(data),
  chequeStatus: (id, payload) => api.patch(`/fees/cheques/${id}/status`, payload).then(data),
  reviewAdjustment: (id, payload) => api.patch(`/fees/adjustments/${id}/review`, payload).then(data),
  processAdjustment: (id) => api.post(`/fees/adjustments/${id}/process`).then(data),
  cancelReceipt: (id, reason) => api.post(`/fees/receipts/${id}/cancel`, { reason }).then(data),
  templates: () => api.get('/fees/notification-templates').then(data),
  saveTemplate: (payload) => api.post('/fees/notification-templates', payload).then(data),
  sendReminders: (payload) => api.post('/fees/reminders/send', payload).then(data),
  closings: () => api.get('/fees/daily-closing').then(data),
  submitClosing: (payload) => api.post('/fees/daily-closing', payload).then(data),
  reviewClosing: (id, payload) => api.patch(`/fees/daily-closing/${id}/review`, payload).then(data),
  setPeriodLock: (payload) => api.put('/fees/period-locks', payload).then(data),
  rollover: (payload) => api.post('/fees/rollover', payload).then(data),
  createScholarship: (payload) => api.post('/fees/scholarships', payload).then(data),
  assignScholarship: (payload) => api.post('/fees/scholarships/assign', payload).then(data),
  family: () => api.get('/fees/family').then(data),
  linkFamily: (payload) => api.post('/fees/family-links', payload).then(data),
  report: (params) => api.get('/fees/reports/collections', { params }).then(data),
  downloadReport: async (params, filename = 'fee-report.csv') => {
    const response = await api.get('/fees/reports/collections', { params, responseType: 'blob' }); const url = URL.createObjectURL(response.data); const link = document.createElement('a'); link.href = url; link.download = filename; link.click(); URL.revokeObjectURL(url);
  },
  platformAnalytics: () => api.get('/fees/platform/analytics').then(data),
};
