import apiClient from './api';

const data = (response) => response.data.data;
export const homeworkService = {
  list: (params = {}) => apiClient.get('/homework', { params }).then(data),
  detail: (id, params = {}) => apiClient.get(`/homework/${id}`, { params }).then(data),
  create: (payload) => apiClient.post('/homework', payload).then(data),
  update: (id, payload) => apiClient.patch(`/homework/${id}`, payload).then(data),
  transition: (id, action, payload = {}) => apiClient.post(`/homework/${id}/${action}`, payload).then(data),
  remove: (id, payload = {}) => apiClient.delete(`/homework/${id}`, { data: payload }).then(data),
  context: () => apiClient.get('/homework/context').then(data),
  analytics: () => apiClient.get('/homework/analytics').then(data),
  saveDraft: (id, payload) => apiClient.post(`/homework/${id}/submissions/draft`, payload).then(data),
  submit: (id, payload) => apiClient.post(`/homework/${id}/submissions`, payload).then(data),
  submissions: (id, params = {}) => apiClient.get(`/homework/${id}/submissions`, { params }).then(data),
  review: (homeworkId, submissionId, payload) => apiClient.patch(`/homework/${homeworkId}/submissions/${submissionId}/review`, payload).then(data),
  resources: (params = {}) => apiClient.get('/resources', { params }).then(data),
  resource: (id, params = {}) => apiClient.get(`/resources/${id}`, { params }).then(data),
  createResource: (payload) => apiClient.post('/resources', payload).then(data),
  updateResource: (id, payload) => apiClient.patch(`/resources/${id}`, payload).then(data),
  transitionResource: (id, action, payload = {}) => apiClient.post(`/resources/${id}/${action}`, payload).then(data),
  duplicateResource: (id, payload = {}) => apiClient.post(`/resources/${id}/duplicate`, payload).then(data),
  previewAudience: (payload) => apiClient.post('/academic-content/audience-preview', payload).then(data),
  versions: (kind, id) => apiClient.get(`/academic-content/${kind}/${id}/versions`).then(data),
  engagement: (kind, id) => apiClient.get(`/academic-content/${kind}/${id}/engagement`).then(data),
  activity: (kind, id, activity, payload = {}) => apiClient.post(`/academic-content/${kind}/${id}/activity/${activity}`, payload).then(data),
  comments: (kind, id, params = {}) => apiClient.get(`/academic-content/${kind}/${id}/comments`, { params }).then(data),
  comment: (kind, id, payload) => apiClient.post(`/academic-content/${kind}/${id}/comments`, payload).then(data),
  submitModeration: (kind, id) => apiClient.post(`/academic-content/${kind}/${id}/moderation`).then(data),
  moderation: (params = {}) => apiClient.get('/academic-content/moderation', { params }).then(data),
  reviewModeration: (id, payload) => apiClient.patch(`/academic-content/moderation/${id}`, payload).then(data),
  children: () => apiClient.get('/parent/homework-children').then(data),
};
