import prisma from '../../config/prisma.client.js';
import { CLOSED_STATUSES, PUBLIC_REPORT_SELECT } from './issueReport.constants.js';
import { validateCreateIssue, validateMessage, validatePriority, validateStatus } from './issueReport.validation.js';

const bad = (message, status = 400) => Object.assign(new Error(message), { status });
const owner = (user) => { if (user.role !== 'PLATFORM_OWNER') throw bad('Platform Owner access required', 403); };
const audit = (issueId, actorId, action, metadata) => prisma.issueReportAudit.create({ data:{ issueId, actorId, action, metadata } });
const pageArgs = (query) => { const page=Math.max(1,Number(query.page)||1); const limit=Math.min(100,Math.max(1,Number(query.limit)||20)); return {page,limit,skip:(page-1)*limit}; };

export async function createIssue(user, body) {
  const data=validateCreateIssue(body);
  const reporter=await prisma.user.findUnique({where:{id:user.id},select:{id:true,name:true,email:true,role:true,schoolId:true,school:{select:{schoolName:true}}}});
  if (!reporter) throw bad('Authenticated user not found',401);
  const since=new Date(Date.now()-60*60*1000);
  const recent=await prisma.issueReport.count({where:{reporterId:user.id,createdAt:{gte:since}}});
  if (recent>=5) throw bad('Too many reports. Please try again later.',429);
  if (data.priority==='CRITICAL') {
    const critical=await prisma.issueReport.count({where:{reporterId:user.id,priority:'CRITICAL',createdAt:{gte:new Date(Date.now()-24*60*60*1000)}}});
    if (critical>=2 && reporter.role!=='PLATFORM_OWNER') throw bad('Critical priority limit reached. Please use High priority.',429);
  }
  return prisma.issueReport.create({data:{...data,reporterId:reporter.id,reporterRole:reporter.role,reporterName:reporter.name,reporterEmail:reporter.email,schoolId:reporter.schoolId,schoolName:reporter.school?.schoolName},select:PUBLIC_REPORT_SELECT});
}
export async function myIssues(user, query) { const {page,limit,skip}=pageArgs(query); const where={reporterId:user.id}; const [items,total]=await prisma.$transaction([prisma.issueReport.findMany({where,select:PUBLIC_REPORT_SELECT,orderBy:{createdAt:'desc'},skip,take:limit}),prisma.issueReport.count({where})]); return {items,pagination:{page,limit,total,pages:Math.ceil(total/limit)}}; }
export async function myIssue(user,id) { const item=await prisma.issueReport.findFirst({where:{id,reporterId:user.id},select:{...PUBLIC_REPORT_SELECT,messages:{where:{isInternal:false},select:{id:true,senderId:true,senderRole:true,message:true,createdAt:true},orderBy:{createdAt:'asc'}}}}); if(!item) throw bad('Report not found',404); return item; }
export async function allIssues(user,query) { owner(user); const {page,limit,skip}=pageArgs(query); const where={}; for(const k of ['status','priority','category','schoolId','reporterRole','assignedToId']) if(query[k]) where[k]=query[k]; if(query.hasScreenshot==='true') where.screenshotUrl={not:null}; if(query.resolved==='true') where.resolvedAt={not:null}; if(query.resolved==='false') where.resolvedAt=null; if(query.from||query.to) where.createdAt={...(query.from&&{gte:new Date(query.from)}),...(query.to&&{lte:new Date(query.to)})}; if(query.search) where.OR=['title','id','reporterName','reporterEmail','schoolName','description'].map(k=>({[k]:{contains:String(query.search),mode:'insensitive'}})); const allowedSort=['createdAt','updatedAt','priority','status']; const sort=allowedSort.includes(query.sort)?query.sort:'createdAt'; const [items,total]=await prisma.$transaction([prisma.issueReport.findMany({where,include:{assignee:{select:{id:true,name:true,email:true}}},orderBy:{[sort]:query.order==='asc'?'asc':'desc'},skip,take:limit}),prisma.issueReport.count({where})]); return {items,pagination:{page,limit,total,pages:Math.ceil(total/limit)}}; }
export async function ownerIssue(user,id) { owner(user); const item=await prisma.issueReport.findUnique({where:{id},include:{assignee:{select:{id:true,name:true,email:true}},messages:{include:{sender:{select:{name:true,email:true}}},orderBy:{createdAt:'asc'}},audits:{include:{actor:{select:{name:true}}},orderBy:{createdAt:'asc'}}}}); if(!item) throw bad('Report not found',404); return item; }
export async function updateIssue(user,id,changes,action) { owner(user); const existing=await prisma.issueReport.findUnique({where:{id}}); if(!existing) throw bad('Report not found',404); const now=new Date(); if(changes.status) { changes.status=validateStatus(changes.status); if(changes.status==='RESOLVED') changes.resolvedAt=now; if(changes.status==='CLOSED') changes.closedAt=now; if(['OPEN','UNDER_REVIEW','IN_PROGRESS','WAITING_FOR_USER'].includes(changes.status)&&['RESOLVED','CLOSED'].includes(existing.status)) changes.reopenedCount={increment:1}; } if(changes.priority) changes.priority=validatePriority(changes.priority); if(!existing.firstResponseAt) changes.firstResponseAt=now; const result=await prisma.issueReport.update({where:{id},data:changes}); await audit(id,user.id,action,changes); return result; }
export async function reply(user,id,body) { const input=validateMessage(body); const issue=await prisma.issueReport.findUnique({where:{id}}); if(!issue) throw bad('Report not found',404); const isOwner=user.role==='PLATFORM_OWNER'; if(!isOwner&&issue.reporterId!==user.id) throw bad('Report not found',404); if(CLOSED_STATUSES.includes(issue.status)) throw bad('Closed reports cannot accept replies',409); if(input.isInternal&&!isOwner) throw bad('Internal notes require Platform Owner access',403); const message=await prisma.issueReportMessage.create({data:{issueId:id,senderId:user.id,senderRole:user.role,...input}}); if(isOwner&&!issue.firstResponseAt) await prisma.issueReport.update({where:{id},data:{firstResponseAt:new Date()}}); return message; }
export async function removeIssue(user,id) { owner(user); const found=await prisma.issueReport.findUnique({where:{id},select:{id:true}}); if(!found) throw bad('Report not found',404); await prisma.issueReport.delete({where:{id}}); return {id}; }
export async function analytics(user) { owner(user); const [total,status,priority,category,today,resolved]=await Promise.all([prisma.issueReport.count(),prisma.issueReport.groupBy({by:['status'],_count:true}),prisma.issueReport.groupBy({by:['priority'],_count:true}),prisma.issueReport.groupBy({by:['category'],_count:true}),prisma.issueReport.count({where:{createdAt:{gte:new Date(new Date().setHours(0,0,0,0))}}}),prisma.issueReport.findMany({where:{resolvedAt:{not:null}},select:{createdAt:true,resolvedAt:true}})]); const avgResolutionHours=resolved.length?resolved.reduce((n,r)=>n+(r.resolvedAt-r.createdAt)/36e5,0)/resolved.length:0; return {total,today,avgResolutionHours,status,priority,category}; }
