import React, { useMemo, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { BookOpen, Building2, LibraryBig, Plus } from 'lucide-react';
import toast from 'react-hot-toast';
import DashboardLayout from '../../layouts/DashboardLayout';
import curriculumService from '../../services/curriculumService';
import { authService } from '../../services/authService';

const control = 'h-11 w-full rounded-xl border border-slate-300 bg-white px-3 text-sm dark:border-slate-700 dark:bg-slate-950';
export default function CurriculumManagePage() {
  const user = authService.getCurrentUser(); const qc = useQueryClient(); const [tab,setTab] = useState('books');
  const [publisher,setPublisher] = useState({name:'',website:''}); const [book,setBook] = useState({title:'',classId:'',subjectId:'',publisherId:'',board:'CBSE',resourcePreference:'BOTH_CBSE_NCERT'}); const [chapter,setChapter] = useState({chapterName:'',chapterNumber:1,classId:'',subjectId:'',bookId:'',estimatedClasses:4,resourcePreference:'INHERIT'});
  const context = useQuery({queryKey:['curriculum-context'],queryFn:curriculumService.academicContext}); const publishers = useQuery({queryKey:['publishers'],queryFn:curriculumService.publishers}); const books = useQuery({queryKey:['curriculum-books'],queryFn:curriculumService.books}); const chapters = useQuery({queryKey:['curriculum-chapters'],queryFn:curriculumService.chapters});
  const curricula = useQuery({queryKey:['curricula'],queryFn:curriculumService.curricula});
  const classes=context.data?.data?.classes||[]; const subjects=context.data?.data?.subjects||[]; const bookOptions=useMemo(()=> (books.data?.data||[]).filter(item=>(!chapter.classId||item.classId===chapter.classId)&&(!chapter.subjectId||item.subjectId===chapter.subjectId)),[books.data,chapter.classId,chapter.subjectId]);
  const draftVersionId = (curricula.data?.data || []).flatMap((item) => item.versions || []).find((version) => version.status === 'DRAFT')?.id;
  const publisherMutation=useMutation({mutationFn:curriculumService.savePublisher,onSuccess:()=>{toast.success('Publisher saved');setPublisher({name:'',website:''});qc.invalidateQueries({queryKey:['publishers']});},onError:e=>toast.error(e.response?.data?.message||'Could not save publisher')});
  const bookMutation=useMutation({mutationFn:(payload)=>curriculumService.createBook({...payload,curriculumVersionId:draftVersionId}),onSuccess:()=>{toast.success('Book added to the active draft');setBook({...book,title:''});qc.invalidateQueries({queryKey:['curriculum-books']});qc.invalidateQueries({queryKey:['curriculum-overview']});},onError:e=>toast.error(e.response?.data?.message||'Could not add book')});
  const chapterMutation=useMutation({mutationFn:(payload)=>curriculumService.createChapter({...payload,curriculumVersionId:draftVersionId}),onSuccess:()=>{toast.success('Chapter added to the active draft');setChapter({...chapter,chapterName:'',chapterNumber:Number(chapter.chapterNumber)+1});qc.invalidateQueries({queryKey:['curriculum-chapters']});qc.invalidateQueries({queryKey:['curriculum-overview']});},onError:e=>toast.error(e.response?.data?.message||'Could not add chapter')});
  return <DashboardLayout role={user?.role}><div className="space-y-6"><header><p className="text-xs font-bold uppercase tracking-widest text-indigo-600">Curriculum workspace</p><h1 className="mt-1 text-3xl font-black">Books, publishers & chapters</h1><p className="mt-2 text-sm text-slate-500">Configure the school’s actual teaching material without assuming a fixed board or textbook.</p></header>{!draftVersionId&&<div className="rounded-2xl border border-amber-300 bg-amber-50 p-4 text-sm text-amber-900">Create a curriculum draft from the dashboard before adding books or chapters.</div>}<nav className="flex gap-2 rounded-2xl bg-slate-100 p-1.5 dark:bg-slate-900">{[['books','Books',LibraryBig],['publishers','Publishers',Building2],['chapters','Chapters',BookOpen]].map(([key,label,Icon])=><button key={key} onClick={()=>setTab(key)} className={`flex-1 rounded-xl px-3 py-2.5 text-sm font-bold ${tab===key?'bg-white text-indigo-700 shadow-sm dark:bg-slate-800':'text-slate-500'}`}><Icon size={16} className="mr-2 inline"/>{label}</button>)}</nav>
  {tab==='publishers'&&<div className="grid gap-5 lg:grid-cols-[360px,1fr]"><form onSubmit={e=>{e.preventDefault();publisherMutation.mutate(publisher)}} className="space-y-3 rounded-3xl border bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><h2 className="font-black">Add publisher</h2><input required className={control} placeholder="Publisher name" value={publisher.name} onChange={e=>setPublisher({...publisher,name:e.target.value})}/><input className={control} type="url" placeholder="Website (optional)" value={publisher.website} onChange={e=>setPublisher({...publisher,website:e.target.value})}/><button className="w-full rounded-xl bg-indigo-600 py-3 font-bold text-white"><Plus size={16} className="mr-2 inline"/>Save publisher</button></form><div className="rounded-3xl border bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><h2 className="font-black">Configured publishers</h2><div className="mt-4 grid gap-3 sm:grid-cols-2">{(publishers.data?.data||[]).map(item=><div key={item.id} className="rounded-2xl border p-4 dark:border-slate-700"><p className="font-bold">{item.name}</p><p className="text-xs text-slate-500">{item.website||'No website'}</p></div>)}</div></div></div>}
  {tab==='books'&&<div className="grid gap-5 xl:grid-cols-[380px,1fr]"><form onSubmit={e=>{e.preventDefault();bookMutation.mutate(book)}} className="space-y-3 rounded-3xl border bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><h2 className="font-black">Add a curriculum book</h2><input required className={control} placeholder="Book title" value={book.title} onChange={e=>setBook({...book,title:e.target.value})}/><select required className={control} value={book.classId} onChange={e=>setBook({...book,classId:e.target.value})}><option value="">Select class</option>{classes.map(item=><option key={item.id} value={item.id}>{item.className}</option>)}</select><select required className={control} value={book.subjectId} onChange={e=>setBook({...book,subjectId:e.target.value})}><option value="">Select subject</option>{subjects.map(item=><option key={item.id} value={item.id}>{item.subjectName}</option>)}</select><select className={control} value={book.publisherId} onChange={e=>setBook({...book,publisherId:e.target.value})}><option value="">No publisher / school-created</option>{(publishers.data?.data||[]).map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select><select className={control} value={book.resourcePreference} onChange={e=>setBook({...book,resourcePreference:e.target.value})}>{['CBSE','NCERT','BOTH_CBSE_NCERT','SCHOOL_ONLY','PUBLISHER','EXTERNAL_CUSTOM','NO_EXTERNAL'].map(item=><option key={item}>{item.replaceAll('_',' ')}</option>)}</select><button className="w-full rounded-xl bg-indigo-600 py-3 font-bold text-white">Add book</button></form><div className="grid content-start gap-3 sm:grid-cols-2">{(books.data?.data||[]).map(item=><article key={item.id} className="rounded-3xl border bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><p className="text-xs font-bold uppercase text-indigo-600">{item.class?.className} · {item.subject?.subjectName}</p><h3 className="mt-2 font-black">{item.title}</h3><p className="mt-1 text-sm text-slate-500">{item.publisher?.name||'School-created'} · {item.board||'Custom'}</p><span className="mt-3 inline-block rounded-full bg-slate-100 px-2.5 py-1 text-xs font-bold dark:bg-slate-800">{(item.resourcePreference||'SCHOOL_ONLY').replaceAll('_',' ')}</span></article>)}</div></div>}
  {tab==='chapters'&&<div className="grid gap-5 xl:grid-cols-[380px,1fr]"><form onSubmit={e=>{e.preventDefault();chapterMutation.mutate(chapter)}} className="space-y-3 rounded-3xl border bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><h2 className="font-black">Add chapter</h2><input required className={control} placeholder="Chapter title" value={chapter.chapterName} onChange={e=>setChapter({...chapter,chapterName:e.target.value})}/><div className="grid grid-cols-2 gap-2"><input required min="1" type="number" className={control} value={chapter.chapterNumber} onChange={e=>setChapter({...chapter,chapterNumber:e.target.value})}/><input min="1" type="number" className={control} value={chapter.estimatedClasses} onChange={e=>setChapter({...chapter,estimatedClasses:e.target.value})}/></div><select required className={control} value={chapter.classId} onChange={e=>setChapter({...chapter,classId:e.target.value,bookId:''})}><option value="">Select class</option>{classes.map(item=><option key={item.id} value={item.id}>{item.className}</option>)}</select><select required className={control} value={chapter.subjectId} onChange={e=>setChapter({...chapter,subjectId:e.target.value,bookId:''})}><option value="">Select subject</option>{subjects.map(item=><option key={item.id} value={item.id}>{item.subjectName}</option>)}</select><select className={control} value={chapter.bookId} onChange={e=>setChapter({...chapter,bookId:e.target.value})}><option value="">Book-independent</option>{bookOptions.map(item=><option key={item.id} value={item.id}>{item.title}</option>)}</select><button className="w-full rounded-xl bg-indigo-600 py-3 font-bold text-white">Add draft chapter</button></form><div className="overflow-hidden rounded-3xl border bg-white shadow-sm dark:border-slate-800 dark:bg-slate-900"><div className="divide-y dark:divide-slate-800">{(chapters.data?.data||[]).map(item=><div key={item.id} className="flex items-center gap-4 p-4"><span className="grid h-10 w-10 place-items-center rounded-xl bg-indigo-50 font-black text-indigo-700">{item.chapterNumber}</span><div className="min-w-0"><p className="truncate font-bold">{item.chapterName}</p><p className="text-xs text-slate-500">{item.class?.className} · {item.subject?.subjectName} · {item.book?.title||'Book-independent'}</p></div><span className="ml-auto rounded-full bg-amber-50 px-2 py-1 text-xs font-bold text-amber-700">{item.publicationStatus||'DRAFT'}</span></div>)}</div></div></div>}
  </div></DashboardLayout>;
}
