import React, { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { AlertTriangle, BookCopy, BookOpen, CalendarDays, CheckCircle2, LibraryBig, ListChecks, Rocket, School, Sparkles } from 'lucide-react';
import toast from 'react-hot-toast';
import DashboardLayout from '../../layouts/DashboardLayout';
import curriculumService from '../../services/curriculumService';
import { authService } from '../../services/authService';

const cards = [
  ['classes', 'Active classes', School, 'from-blue-600 to-cyan-500'], ['subjects', 'Subjects', LibraryBig, 'from-violet-600 to-indigo-500'],
  ['books', 'Books', BookCopy, 'from-amber-500 to-orange-500'], ['chapters', 'Chapters', BookOpen, 'from-emerald-600 to-teal-500'],
  ['drafts', 'Draft changes', ListChecks, 'from-fuchsia-600 to-pink-500'], ['missingWeeklySlots', 'Missing weekly slots', AlertTriangle, 'from-rose-600 to-orange-500'],
];

export default function CurriculumDashboardPage() {
  const user = authService.getCurrentUser(); const qc = useQueryClient(); const [showCreate, setShowCreate] = useState(false); const [form, setForm] = useState({ name: '', curriculumType: 'CBSE', academicSession: '' });
  const overview = useQuery({ queryKey: ['curriculum-overview'], queryFn: curriculumService.overview });
  const curricula = useQuery({ queryKey: ['curricula'], queryFn: curriculumService.curricula });
  const create = useMutation({ mutationFn: curriculumService.createCurriculum, onSuccess: () => { toast.success('Draft curriculum created'); setShowCreate(false); setForm({ name: '', curriculumType: 'CBSE', academicSession: '' }); qc.invalidateQueries({ queryKey: ['curricula'] }); qc.invalidateQueries({ queryKey: ['curriculum-overview'] }); }, onError: (error) => toast.error(error.response?.data?.message || 'Could not create curriculum') });
  const publish = useMutation({ mutationFn: curriculumService.publish, onSuccess: () => { toast.success('Curriculum published'); qc.invalidateQueries({ queryKey: ['curricula'] }); }, onError: (error) => toast.error(error.response?.data?.data?.warnings?.join(' · ') || error.response?.data?.message || 'Validation failed') });
  const stats = overview.data?.data?.stats || {}; const completion = stats.subjects ? Math.max(0, Math.round(((stats.subjects - Math.max(stats.missingBooks || 0, stats.missingChapters || 0, stats.missingWeeklySlots || 0)) / stats.subjects) * 100)) : 0;
  return <DashboardLayout role={user?.role || 'CURRICULUM_MANAGER'}><div className="space-y-6">
    <header className="overflow-hidden rounded-3xl bg-gradient-to-br from-indigo-950 via-violet-900 to-indigo-700 p-7 text-white shadow-xl"><div className="flex flex-wrap items-center justify-between gap-5"><div><p className="flex items-center gap-2 text-xs font-bold uppercase tracking-[.2em] text-indigo-200"><Sparkles size={15}/> Academic control centre</p><h1 className="mt-2 text-3xl font-black">Curriculum workspace</h1><p className="mt-2 max-w-2xl text-sm text-indigo-100">Build school-specific books, chapters and teaching sequences safely in drafts, validate them, then publish.</p></div><button onClick={() => setShowCreate(true)} className="rounded-2xl bg-white px-5 py-3 text-sm font-black text-indigo-800 shadow-lg">Create curriculum draft</button></div><div className="mt-6"><div className="mb-2 flex justify-between text-xs font-bold"><span>Curriculum completeness</span><span>{completion}%</span></div><div className="h-2 overflow-hidden rounded-full bg-white/15"><div className="h-full rounded-full bg-emerald-400 transition-all" style={{ width: `${completion}%` }}/></div></div></header>
    {overview.isLoading ? <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{cards.map(([key]) => <div key={key} className="h-28 animate-pulse rounded-3xl bg-slate-200 dark:bg-slate-800"/>)}</div> : <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{cards.map(([key,label,Icon,color]) => <article key={key} className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><div className="flex items-center justify-between"><span className={`rounded-2xl bg-gradient-to-br ${color} p-3 text-white`}><Icon size={20}/></span><strong className="text-3xl font-black">{stats[key] ?? 0}</strong></div><p className="mt-4 text-sm font-semibold text-slate-500">{label}</p></article>)}</section>}
    <section className="grid gap-6 xl:grid-cols-[1fr,340px]"><div className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm dark:border-slate-800 dark:bg-slate-900"><div className="flex items-center justify-between border-b border-slate-100 p-5 dark:border-slate-800"><div><h2 className="text-lg font-black">Curriculum versions</h2><p className="text-sm text-slate-500">Draft, published, and archived history</p></div><Rocket className="text-indigo-500"/></div>{curricula.isLoading ? <div className="p-8 text-sm text-slate-500">Loading versions…</div> : !(curricula.data?.data || []).length ? <div className="p-10 text-center"><BookCopy className="mx-auto text-slate-300"/><p className="mt-3 font-bold">No curriculum draft yet</p><p className="text-sm text-slate-500">Create one to begin a versioned academic setup.</p></div> : <div className="divide-y divide-slate-100 dark:divide-slate-800">{curricula.data.data.map((item) => <article key={item.id} className="p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="font-black">{item.name}</h3><p className="text-xs text-slate-500">{item.curriculumType} · {item.academicSession}</p></div><div className="flex flex-wrap gap-2">{item.versions.map((version) => <span key={version.id} className={`rounded-full px-3 py-1 text-xs font-bold ${version.status === 'PUBLISHED' ? 'bg-emerald-50 text-emerald-700' : version.status === 'DRAFT' ? 'bg-amber-50 text-amber-700' : 'bg-slate-100 text-slate-600'}`}>v{version.versionNumber} {version.status}</span>)}</div></div>{item.versions.find((version) => version.status === 'DRAFT') && <button onClick={() => publish.mutate(item.versions.find((version) => version.status === 'DRAFT').id)} className="mt-4 inline-flex items-center gap-2 rounded-xl bg-indigo-600 px-4 py-2 text-xs font-black text-white"><CheckCircle2 size={15}/> Validate & publish</button>}</article>)}</div>}</div>
      <aside className="space-y-4"><div className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><h2 className="font-black">Validation summary</h2><div className="mt-4 space-y-3 text-sm">{[['Subjects missing books',stats.missingBooks],['Subjects missing chapters',stats.missingChapters],['Missing weekly slots',stats.missingWeeklySlots]].map(([label,count]) => <div key={label} className="flex items-center justify-between rounded-xl bg-slate-50 p-3 dark:bg-slate-950"><span>{label}</span><strong className={count ? 'text-rose-600' : 'text-emerald-600'}>{count || 0}</strong></div>)}</div></div><div className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><h2 className="font-black">Quick actions</h2><div className="mt-3 grid gap-2">{[['Books & publishers','/dashboard/curriculum/manage'],['Chapters & units','/dashboard/curriculum/manage'],['Weekly slots','/dashboard/admin/weekly-slots'],['Academic calendar','/dashboard/calendar']].map(([label,href]) => <a key={label} href={href} className="flex items-center justify-between rounded-xl border border-slate-200 px-3 py-2.5 text-sm font-semibold hover:border-indigo-400 hover:text-indigo-700 dark:border-slate-700">{label}<span>→</span></a>)}</div></div></aside></section>
    {showCreate && <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/60 p-4"><form onSubmit={(event) => { event.preventDefault(); create.mutate(form); }} className="w-full max-w-lg space-y-4 rounded-3xl bg-white p-6 shadow-2xl dark:bg-slate-900"><div><h2 className="text-xl font-black">New curriculum draft</h2><p className="text-sm text-slate-500">Changes stay private until validation and publication.</p></div><input required className="h-11 w-full rounded-xl border px-3 dark:bg-slate-950" placeholder="Curriculum name" value={form.name} onChange={(e) => setForm({...form,name:e.target.value})}/><select className="h-11 w-full rounded-xl border px-3 dark:bg-slate-950" value={form.curriculumType} onChange={(e) => setForm({...form,curriculumType:e.target.value})}>{['CBSE','NCERT','ICSE','STATE_BOARD','INTERNATIONAL','CUSTOM'].map((item) => <option key={item}>{item}</option>)}</select><input className="h-11 w-full rounded-xl border px-3 dark:bg-slate-950" placeholder="Academic session (e.g. 2026-27)" value={form.academicSession} onChange={(e) => setForm({...form,academicSession:e.target.value})}/><div className="flex gap-2"><button type="button" onClick={() => setShowCreate(false)} className="flex-1 rounded-xl border py-3 font-bold">Cancel</button><button disabled={create.isPending} className="flex-1 rounded-xl bg-indigo-600 py-3 font-bold text-white">Create draft</button></div></form></div>}
  </div></DashboardLayout>;
}
