import React, { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { BarChart3, CheckCircle2, ChevronRight, ClipboardCheck, FileDown, GraduationCap, Loader2, Plus, RefreshCw, Save, Search, Send, ShieldCheck, XCircle } from 'lucide-react';
import toast from 'react-hot-toast';
import DashboardLayout from '../../layouts/DashboardLayout';
import { authService } from '../../services/authService';
import { examinationService } from '../../services/examinationService';

const panel = 'rounded-2xl border border-slate-200 bg-white shadow-sm dark:border-slate-800 dark:bg-slate-900';
const input = 'h-10 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm outline-none focus:border-emerald-500 dark:border-slate-700 dark:bg-slate-950';
const primary = 'inline-flex h-10 items-center justify-center gap-2 rounded-xl bg-emerald-600 px-4 text-sm font-semibold text-white transition hover:bg-emerald-700 disabled:cursor-not-allowed disabled:opacity-50';
const secondary = 'inline-flex h-10 items-center justify-center gap-2 rounded-xl border border-slate-200 px-4 text-sm font-semibold transition hover:bg-slate-50 dark:border-slate-700 dark:hover:bg-slate-800';
const statusStyle = { DRAFT: 'bg-slate-100 text-slate-700', SCHEDULED: 'bg-blue-100 text-blue-700', MARK_ENTRY_OPEN: 'bg-amber-100 text-amber-800', MARK_ENTRY_CLOSED: 'bg-orange-100 text-orange-800', VERIFICATION: 'bg-violet-100 text-violet-700', APPROVED: 'bg-emerald-100 text-emerald-700', PUBLISHED: 'bg-teal-100 text-teal-800', ARCHIVED: 'bg-slate-200 text-slate-600' };
const nextStatus = { DRAFT: 'SCHEDULED', SCHEDULED: 'MARK_ENTRY_OPEN', MARK_ENTRY_OPEN: 'MARK_ENTRY_CLOSED', MARK_ENTRY_CLOSED: 'VERIFICATION', PUBLISHED: 'ARCHIVED' };
const managerRoles = ['ADMIN', 'CURRICULUM_MANAGER', 'EXAM_COORDINATOR', 'EXAM_CONTROLLER'];

function Status({ value }) { return <span className={`inline-flex rounded-full px-2.5 py-1 text-[11px] font-bold ${statusStyle[value] || 'bg-slate-100'}`}>{String(value).replaceAll('_', ' ')}</span>; }
function Empty({ children }) { return <div className="p-10 text-center text-sm text-slate-500"><GraduationCap className="mx-auto mb-3 opacity-40" size={34}/>{children}</div>; }

export function CreateExam({ metadata, onClose, onCreated }) {
  const [busy, setBusy] = useState(false);
  const [form, setForm] = useState({ name: '', code: '', academicSessionId: metadata.sessions.find((s) => s.isActive)?.id || metadata.sessions[0]?.id || '', startDate: '', endDate: '', resultDate: '', publicationDate: '', sections: [] });
  const readySections = useMemo(() => new Map((metadata.allocationReadiness || []).filter((row) => row.academicSessionId === form.academicSessionId).map((row) => [row.sectionId, row.subjectCount])), [form.academicSessionId, metadata.allocationReadiness]);
  const toggle = (classId, sectionId) => setForm((old) => ({ ...old, sections: old.sections.some((s) => s.sectionId === sectionId) ? old.sections.filter((s) => s.sectionId !== sectionId) : [...old.sections, { classId, sectionId }] }));
  const changeSession = (academicSessionId) => setForm((old) => ({ ...old, academicSessionId, sections: [] }));
  const submit = async (event) => { event.preventDefault(); if (!form.academicSessionId) return toast.error('Configure an academic session before creating an examination'); if (form.endDate < form.startDate) return toast.error('End date cannot be before start date'); if (form.sections.some((section) => !readySections.has(section.sectionId))) return toast.error('Choose sections with ready subject allocations'); setBusy(true); try { const exam = await examinationService.create({ ...form, cohorts: form.sections }); toast.success('Examination created'); onCreated(exam); } catch (error) { toast.error(error.response?.data?.message || 'Could not create examination'); } finally { setBusy(false); } };
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/60 p-4"><form onSubmit={submit} className={`${panel} max-h-[92vh] w-full max-w-3xl overflow-y-auto p-6`}>
    <div className="flex items-start justify-between"><div><h2 className="text-xl font-bold">Plan an examination</h2><p className="mt-1 text-sm text-slate-500">Subjects and teachers are taken from published section allocations.</p></div><button type="button" onClick={onClose}><XCircle/></button></div>
    <div className="mt-6 grid gap-4 md:grid-cols-2"><label className="text-sm font-medium">Exam name<input required className={`${input} mt-1.5`} value={form.name} onChange={(e)=>setForm({...form,name:e.target.value})} placeholder="Half Yearly Examination"/></label><label className="text-sm font-medium">Code<input required className={`${input} mt-1.5 uppercase`} value={form.code} onChange={(e)=>setForm({...form,code:e.target.value})} placeholder="HY-2026"/></label><label className="text-sm font-medium">Academic session<select required className={`${input} mt-1.5`} value={form.academicSessionId} onChange={(e)=>changeSession(e.target.value)}><option value="">Select session</option>{metadata.sessions.map((s)=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><div/><label className="text-sm font-medium">Starts<input required type="date" className={`${input} mt-1.5`} value={form.startDate} onChange={(e)=>setForm({...form,startDate:e.target.value})}/></label><label className="text-sm font-medium">Ends<input required type="date" min={form.startDate || undefined} className={`${input} mt-1.5`} value={form.endDate} onChange={(e)=>setForm({...form,endDate:e.target.value})}/></label><label className="text-sm font-medium">Result date<input type="date" className={`${input} mt-1.5`} value={form.resultDate} onChange={(e)=>setForm({...form,resultDate:e.target.value})}/></label><label className="text-sm font-medium">Publication date<input type="date" className={`${input} mt-1.5`} value={form.publicationDate} onChange={(e)=>setForm({...form,publicationDate:e.target.value})}/></label></div>
    {!metadata.sessions.length && <p className="mt-5 rounded-xl border border-amber-200 bg-amber-50 p-3 text-sm font-medium text-amber-900">No academic session is configured for this school. Ask an administrator to complete academic setup.</p>}
    <div className="mt-6"><div className="mb-3 flex items-center justify-between"><h3 className="font-semibold">Applicable sections</h3><span className="text-xs text-slate-500">{form.sections.length} selected</span></div><div className="grid max-h-52 gap-2 overflow-y-auto md:grid-cols-2">{metadata.classes.flatMap((klass)=>klass.sections.map((section)=><label key={section.id} className="flex cursor-pointer items-center gap-3 rounded-xl border border-slate-200 p-3 dark:border-slate-700"><input type="checkbox" checked={form.sections.some((s)=>s.sectionId===section.id)} onChange={()=>toggle(klass.id,section.id)}/><span className="text-sm font-medium">{klass.className} · {section.sectionName}</span></label>))}</div></div>
    <div className="mt-6 flex flex-col-reverse gap-3 sm:flex-row sm:justify-end"><button type="button" className={secondary} onClick={onClose}>Cancel</button><button className={primary} disabled={busy || !form.academicSessionId || !form.sections.length}>{busy&&<Loader2 className="animate-spin" size={16}/>}Create draft</button></div>
  </form></div>;
}

export function MarkGrid({ exam, subject, onBack, refresh }) {
  const [sheet, setSheet] = useState(null); const [values, setValues] = useState({}); const [search, setSearch] = useState(''); const [saving, setSaving] = useState(false); const dirty = useRef(new Set()); const timer = useRef();
  const load = useCallback(async()=>{ const data=await examinationService.markSheet(exam.id,subject.id); setSheet(data); const next={}; data.students.forEach((student)=>data.examSubject.components.forEach((component)=>{const mark=student.marks[component.id]; next[`${student.id}:${component.id}`]={marks:mark?.marks??'',attendanceStatus:mark?.attendanceStatus||'PRESENT'};})); setValues(next); },[exam.id,subject.id]);
  useEffect(()=>{load().catch((e)=>toast.error(e.response?.data?.message||'Could not load marks'));},[load]);
  const flush=useCallback(async()=>{if(!dirty.current.size)return; const keys=[...dirty.current]; dirty.current.clear(); setSaving(true); try{await examinationService.saveMarks(exam.id,subject.id,keys.map((key)=>{const [studentId,componentId]=key.split(':');return{studentId,componentId,...values[key]};}));}catch(e){keys.forEach((k)=>dirty.current.add(k));toast.error(e.response?.data?.message||'Autosave failed');}finally{setSaving(false);}},[exam.id,subject.id,values]);
  useEffect(()=>{clearTimeout(timer.current);if(dirty.current.size)timer.current=setTimeout(flush,1800);return()=>clearTimeout(timer.current);},[values,flush]);
  const change=(key,patch)=>{dirty.current.add(key);setValues((old)=>({...old,[key]:{...old[key],...patch}}));};
  const submit=async()=>{await flush();try{await examinationService.submitMarks(exam.id,subject.id);toast.success('Marks submitted and locked');refresh();onBack();}catch(e){toast.error(e.response?.data?.message||'Submission validation failed');}};
  if(!sheet)return <Empty><Loader2 className="mx-auto animate-spin"/></Empty>;
  const students=sheet.students.filter((s)=>`${s.rollNumber||''} ${s.studentFirstName} ${s.studentLastName||''}`.toLowerCase().includes(search.toLowerCase()));
  return <div><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><div><button onClick={onBack} className="text-xs font-semibold text-emerald-700">← All subjects</button><h2 className="mt-1 text-xl font-bold">{sheet.examSubject.subject.subjectName}</h2><p className="text-sm text-slate-500">{sheet.examSubject.cohort.class.className} · {sheet.examSubject.cohort.section.sectionName}</p></div><div className="flex gap-2"><span className="self-center text-xs text-slate-500">{saving?'Saving…':'Autosaved'}</span><button className={secondary} onClick={flush}><Save size={16}/>Save</button><button className={primary} onClick={submit}><Send size={16}/>Submit</button></div></div><div className="relative mb-3 max-w-sm"><Search className="absolute left-3 top-3 text-slate-400" size={15}/><input className={`${input} pl-9`} placeholder="Search student or roll number" value={search} onChange={(e)=>setSearch(e.target.value)}/></div><div className={`${panel} overflow-auto`}><table className="min-w-full border-collapse text-sm"><thead className="sticky top-0 z-10 bg-slate-50 dark:bg-slate-950"><tr><th className="sticky left-0 bg-inherit px-3 py-3 text-left">Roll · Student</th>{sheet.examSubject.components.map((c)=><th key={c.id} className="min-w-36 px-3 py-3 text-left">{c.name}<span className="block text-[10px] font-normal text-slate-500">Max {c.maximumMarks} · Pass {c.passingMarks}</span></th>)}</tr></thead><tbody>{students.map((student)=><tr key={student.id} className="border-t border-slate-100 dark:border-slate-800"><td className="sticky left-0 bg-white px-3 py-2 font-medium dark:bg-slate-900">{student.rollNumber||'—'} · {student.studentFirstName} {student.studentLastName||''}</td>{sheet.examSubject.components.map((component)=>{const key=`${student.id}:${component.id}`;const value=values[key];return <td key={component.id} className="px-3 py-2"><div className="flex gap-1"><input aria-label={`${student.studentFirstName} ${component.name}`} disabled={value.attendanceStatus!=='PRESENT'} type="number" min="0" max={component.maximumMarks} step={component.allowDecimal?'0.5':'1'} className="h-9 w-20 rounded-lg border border-slate-200 px-2 dark:border-slate-700 dark:bg-slate-950" value={value.marks} onChange={(e)=>change(key,{marks:e.target.value})}/><select aria-label="Attendance status" className="h-9 w-12 rounded-lg border border-slate-200 text-xs dark:border-slate-700 dark:bg-slate-950" value={value.attendanceStatus} onChange={(e)=>change(key,{attendanceStatus:e.target.value,marks:e.target.value==='PRESENT'?value.marks:''})}><option value="PRESENT">P</option><option value="ABSENT">AB</option><option value="MEDICAL">ML</option><option value="EXEMPTED">EX</option><option value="TRANSFERRED">TR</option><option value="LATE_ADMISSION">LA</option></select></div></td>})}</tr>)}</tbody></table></div></div>;
}

function Analytics({ examId }) { const [data,setData]=useState(null);useEffect(()=>{examinationService.analytics(examId).then(setData).catch(()=>setData({}));},[examId]);if(!data)return <Empty><Loader2 className="mx-auto animate-spin"/></Empty>;return <div className="grid gap-4 md:grid-cols-4"><Metric label="Students" value={data.studentCount||0}/><Metric label="School average" value={`${Number(data.averagePercentage||0).toFixed(1)}%`}/><Metric label="Pass rate" value={`${Number(data.passPercentage||0).toFixed(1)}%`}/><Metric label="Highest" value={`${Number(data.highestPercentage||0).toFixed(1)}%`}/><div className={`${panel} p-5 md:col-span-4`}><h3 className="font-semibold">Subject performance</h3><div className="mt-4 space-y-3">{data.subjectPerformance?.map((row)=><div key={row.subject}><div className="mb-1 flex justify-between text-sm"><span>{row.subject}</span><span>{Number(row.average).toFixed(1)}%</span></div><div className="h-2 rounded-full bg-slate-100 dark:bg-slate-800"><div className="h-full rounded-full bg-emerald-500" style={{width:`${Math.min(100,row.average)}%`}}/></div></div>)}</div></div></div>; }
function Metric({label,value}){return <div className={`${panel} p-5`}><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">{label}</p><p className="mt-2 text-2xl font-bold">{value}</p></div>;}

function StudentResults({ role }) { const [data,setData]=useState(null);useEffect(()=>{examinationService.myResults().then(setData).catch((e)=>toast.error(e.response?.data?.message||'Could not load results'));},[]);const download=async(result)=>{try{const blob=await examinationService.downloadReportCard(result.examination.id,data.student.id);const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=`${data.student.admissionNo||'report-card'}-${result.examination.name}.pdf`;link.click();URL.revokeObjectURL(url);}catch(e){toast.error(e.response?.data?.message||'Could not download report card');}};return <DashboardLayout role={role}><div className="mx-auto max-w-6xl p-4 md:p-8"><div className="mb-6"><p className="text-xs font-bold uppercase tracking-[.2em] text-emerald-600">Result portal</p><h1 className="mt-1 text-3xl font-bold">Examinations & report cards</h1></div>{!data?<Empty><Loader2 className="mx-auto animate-spin"/></Empty>:!data.results.length?<div className={panel}><Empty>No published results are available yet.</Empty></div>:<div className="grid gap-4 md:grid-cols-2">{data.results.map((result)=><div key={result.id} className={`${panel} p-5`}><div className="flex justify-between"><div><h2 className="font-bold">{result.examination.name}</h2><p className="text-sm text-slate-500">{result.examination.academicSession.name}</p></div><Status value="PUBLISHED"/></div><div className="mt-5 grid grid-cols-3 gap-3"><Metric label="Percentage" value={`${Number(result.percentage).toFixed(1)}%`}/><Metric label="Grade" value={result.grade||'—'}/><Metric label="Rank" value={result.rank||'—'}/></div><button className={`${primary} mt-4 w-full`} onClick={()=>download(result)}><FileDown size={16}/>Download report card</button></div>)}</div>}</div></DashboardLayout>;}

export default function ExaminationWorkspacePage(){const user=authService.getCurrentUser();const role=user?.role||'ADMIN';const [exams,setExams]=useState([]);const [metadata,setMetadata]=useState(null);const [selected,setSelected]=useState(null);const [markSubject,setMarkSubject]=useState(null);const [showCreate,setShowCreate]=useState(false);const [tab,setTab]=useState('workflow');const [busy,setBusy]=useState(false);
  const load=useCallback(async()=>{const list=await examinationService.list();setExams(list);if(selected){const fresh=await examinationService.detail(selected.id);setSelected(fresh);}},[selected?.id]);useEffect(()=>{if(!['STUDENT','PARENT'].includes(role)){Promise.all([examinationService.list(),examinationService.metadata().catch(()=>null)]).then(([list,meta])=>{setExams(list);setMetadata(meta);}).catch(()=>toast.error('Could not load examinations'));}},[role]);
  if(['STUDENT','PARENT'].includes(role))return <StudentResults role={role}/>;
  const open=async(exam)=>{setSelected(await examinationService.detail(exam.id));setMarkSubject(null);setTab('workflow');};
  const act=async(fn,message)=>{setBusy(true);try{await fn();toast.success(message);await load();}catch(e){toast.error(e.response?.data?.message||'Action failed');}finally{setBusy(false);}};
  const correct=async(item)=>{const reason=window.prompt('Reason for reopening this published subject:');if(reason?.trim())await act(()=>examinationService.requestCorrection(selected.id,item.id,reason.trim()),'Correction workflow opened');};
  const subjectList=selected?.cohorts.flatMap((cohort)=>cohort.subjects.map((subject)=>({...subject,cohort})))||[];
  return <DashboardLayout role={role}><div className="min-h-screen bg-slate-50 p-4 text-slate-900 dark:bg-slate-950 dark:text-slate-100 md:p-8"><div className="mx-auto max-w-[1500px]">{markSubject?<MarkGrid exam={selected} subject={markSubject} onBack={()=>setMarkSubject(null)} refresh={load}/>:<><header className="mb-6 flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-emerald-600">Academic operations</p><h1 className="mt-1 text-3xl font-bold">Examinations & Results</h1><p className="mt-2 max-w-2xl text-sm text-slate-500">Plan, enter, verify, approve, publish and analyse results through one governed workflow.</p></div>{managerRoles.includes(role)&&metadata&&<button className={primary} onClick={()=>setShowCreate(true)}><Plus size={17}/>New examination</button>}</header>
  <div className="grid gap-5 lg:grid-cols-[330px_1fr]"><aside className={`${panel} h-fit overflow-hidden`}><div className="border-b border-slate-100 p-4 dark:border-slate-800"><h2 className="font-semibold">Exam cycles</h2><p className="text-xs text-slate-500">{exams.length} configured</p></div>{!exams.length?<Empty>No examinations configured.</Empty>:<div className="divide-y divide-slate-100 dark:divide-slate-800">{exams.map((exam)=><button key={exam.id} onClick={()=>open(exam)} className={`w-full p-4 text-left transition hover:bg-slate-50 dark:hover:bg-slate-800 ${selected?.id===exam.id?'bg-emerald-50 dark:bg-emerald-950/30':''}`}><div className="flex items-start justify-between gap-2"><div><p className="font-semibold">{exam.name}</p><p className="mt-1 text-xs text-slate-500">{exam.academicSession.name} · {exam.cohorts.length} sections</p></div><ChevronRight size={16}/></div><div className="mt-3"><Status value={exam.status}/></div></button>)}</div>}</aside>
  <main>{!selected?<div className={panel}><Empty>Select an examination to open its control centre.</Empty></div>:<><div className={`${panel} mb-5 p-5`}><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex items-center gap-3"><h2 className="text-2xl font-bold">{selected.name}</h2><Status value={selected.status}/></div><p className="mt-2 text-sm text-slate-500">{new Date(selected.startDate).toLocaleDateString()} – {new Date(selected.endDate).toLocaleDateString()} · {selected.academicSession.name}</p></div><div className="flex flex-wrap gap-2"><button className={secondary} onClick={()=>load()}><RefreshCw size={16}/></button>{nextStatus[selected.status]&&['ADMIN','EXAM_COORDINATOR','PRINCIPAL'].includes(role)&&<button disabled={busy} className={primary} onClick={()=>act(()=>examinationService.transition(selected.id,nextStatus[selected.status]),`Moved to ${nextStatus[selected.status].replaceAll('_',' ')}`)}>{nextStatus[selected.status].replaceAll('_',' ')}</button>}{selected.status==='VERIFICATION'&&['ADMIN','EXAM_COORDINATOR'].includes(role)&&<button className={primary} onClick={()=>act(()=>examinationService.calculate(selected.id),'Results calculated')}><BarChart3 size={16}/>Calculate</button>}{selected.status==='APPROVED'&&['PRINCIPAL','EXAM_COORDINATOR'].includes(role)&&<button className={primary} onClick={()=>act(()=>examinationService.publish(selected.id),'Results published')}><ShieldCheck size={16}/>Publish</button>}</div></div></div>
  <div className="mb-4 flex gap-2 overflow-x-auto">{[['workflow','Workflow',ClipboardCheck],['marks','Marks',GraduationCap],['analytics','Analytics',BarChart3]].map(([key,label,Icon])=><button key={key} onClick={()=>setTab(key)} className={`${tab===key?primary:secondary} whitespace-nowrap`}><Icon size={16}/>{label}</button>)}</div>
  {tab==='workflow'&&<div className="space-y-4">{selected.cohorts.map((cohort)=><div key={cohort.id} className={`${panel} p-5`}><div className="flex flex-wrap justify-between gap-3"><div><h3 className="font-bold">{cohort.class.className} · {cohort.section.sectionName}</h3><p className="mt-1 text-xs text-slate-500">{cohort.subjects.filter((s)=>s.status==='SUBMITTED').length}/{cohort.subjects.length} subjects submitted</p></div><Status value={cohort.status}/></div><div className="mt-4 h-2 overflow-hidden rounded-full bg-slate-100 dark:bg-slate-800"><div className="h-full bg-emerald-500" style={{width:`${cohort.subjects.length?cohort.subjects.filter((s)=>s.status==='SUBMITTED').length*100/cohort.subjects.length:0}%`}}/></div>{cohort.status==='READY_FOR_CLASS_REVIEW'&&role==='TEACHER'&&<button className={`${primary} mt-4`} onClick={()=>act(()=>examinationService.review(selected.id,{cohortId:cohort.id,level:'CLASS_TEACHER',decision:'FORWARDED'}),'Forwarded to coordinator')}><Send size={16}/>Forward</button>}{cohort.status==='FORWARDED'&&['ADMIN','EXAM_COORDINATOR'].includes(role)&&<div className="mt-4 flex gap-2"><button className={primary} onClick={()=>act(()=>examinationService.review(selected.id,{cohortId:cohort.id,level:'EXAM_COORDINATOR',decision:'APPROVED'}),'Coordinator approved')}><CheckCircle2 size={16}/>Approve</button><button className={secondary} onClick={()=>act(()=>examinationService.review(selected.id,{cohortId:cohort.id,level:'EXAM_COORDINATOR',decision:'REJECTED',reason:'Corrections required'}),'Returned for correction')}>Reject</button></div>}{cohort.status==='COORDINATOR_APPROVED'&&role==='PRINCIPAL'&&<button className={`${primary} mt-4`} onClick={()=>act(()=>examinationService.review(selected.id,{cohortId:cohort.id,level:'PRINCIPAL',decision:'APPROVED'}),'Principal approved')}><ShieldCheck size={16}/>Final approval</button>}</div>)}</div>}
  {tab==='marks'&&<div className={`${panel} overflow-hidden`}><div className="grid gap-px bg-slate-100 dark:bg-slate-800 md:grid-cols-2">{subjectList.map((item)=><div key={item.id} className="flex items-center justify-between bg-white p-4 dark:bg-slate-900"><button onClick={()=>setMarkSubject(item)} className="flex-1 text-left hover:text-emerald-700"><p className="font-semibold">{item.subject.subjectName}</p><p className="text-xs text-slate-500">{item.cohort.class.className} · {item.cohort.section.sectionName}</p></button><div className="flex items-center gap-2"><Status value={item.status}/>{selected.status==='PUBLISHED'&&['PRINCIPAL','EXAM_COORDINATOR'].includes(role)&&<button className="text-xs font-semibold text-amber-700" onClick={()=>correct(item)}>Correct</button>}</div></div>)}</div></div>}{tab==='analytics'&&<Analytics examId={selected.id}/>}</>}</main></div></>}{showCreate&&<CreateExam metadata={metadata} onClose={()=>setShowCreate(false)} onCreated={(exam)=>{setShowCreate(false);setExams((old)=>[exam,...old]);open(exam);}}/>}</div></div></DashboardLayout>;
}
