import React, { useState } from 'react';
import { Link } from 'react-router-dom';
import { CheckCircle2, KeyRound, ShieldCheck } from 'lucide-react';
import toast from 'react-hot-toast';
import securityService from '../services/securityService';
import PasswordInput from '../components/ui/PasswordInput';

const field = 'h-11 w-full rounded-xl border border-slate-300 bg-white px-3 text-sm outline-none focus:border-indigo-500 focus:ring-2 focus:ring-indigo-200';

export default function AccountRecoveryPage() {
  const [step, setStep] = useState(1); const [busy, setBusy] = useState(false); const [identifier, setIdentifier] = useState(''); const [challenge, setChallenge] = useState(''); const [questions, setQuestions] = useState([]); const [identityDetail, setIdentityDetail] = useState(''); const [answers, setAnswers] = useState({}); const [resetToken, setResetToken] = useState(''); const [password, setPassword] = useState(''); const [confirm, setConfirm] = useState('');
  const start = async (event) => { event.preventDefault(); setBusy(true); try { const response = await securityService.startRecovery(identifier); setChallenge(response.data.challenge); setQuestions(response.data.questions || []); setStep(2); } catch { toast.error('Recovery could not be started'); } finally { setBusy(false); } };
  const verify = async (event) => { event.preventDefault(); setBusy(true); try { const response = await securityService.verifyRecovery({ challenge, identityDetail, answers: questions.map((item) => ({ questionKey: item.questionKey, answer: answers[item.questionKey] || '' })) }); setResetToken(response.data.resetToken); setStep(3); } catch (error) { toast.error(error.response?.data?.message || 'Recovery verification failed'); } finally { setBusy(false); } };
  const finish = async (event) => { event.preventDefault(); if (password !== confirm) return toast.error('Passwords do not match'); setBusy(true); try { await securityService.completeRecovery({ resetToken, password }); setStep(4); } catch (error) { toast.error(error.response?.data?.message || 'Password reset failed'); } finally { setBusy(false); } };

  return <main className="min-h-screen bg-gradient-to-br from-slate-950 via-indigo-950 to-slate-900 p-4 sm:p-8"><div className="mx-auto max-w-xl pt-8"><div className="mb-6 text-center text-white"><span className="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-white/10"><ShieldCheck/></span><h1 className="mt-4 text-3xl font-black">Recover your SchoolOS account</h1><p className="mt-2 text-sm text-slate-300">Two-factor identity verification protects school accounts from unauthorized recovery.</p></div><section className="rounded-3xl bg-white p-6 shadow-2xl sm:p-8"><div className="mb-6 flex items-center gap-2">{[1,2,3].map((item) => <React.Fragment key={item}><span className={`grid h-8 w-8 place-items-center rounded-full text-xs font-bold ${step >= item ? 'bg-indigo-600 text-white' : 'bg-slate-100 text-slate-400'}`}>{item}</span>{item < 3 && <span className={`h-1 flex-1 rounded ${step > item ? 'bg-indigo-600' : 'bg-slate-100'}`}/>}</React.Fragment>)}</div>
    {step === 1 && <form onSubmit={start} className="space-y-4"><div><h2 className="text-xl font-black">Find your account</h2><p className="mt-1 text-sm text-slate-500">Enter your login ID, registered email, admission number, or employee ID.</p></div><input className={field} required value={identifier} onChange={(event) => setIdentifier(event.target.value)} placeholder="Login ID or registered identifier" autoComplete="username"/><button disabled={busy} className="w-full rounded-xl bg-indigo-600 py-3 font-bold text-white">{busy ? 'Continuing…' : 'Continue securely'}</button><p className="text-xs text-slate-500">For privacy, SchoolOS uses the same response whether or not an identifier exists.</p></form>}
    {step === 2 && <form onSubmit={verify} className="space-y-4"><div><h2 className="text-xl font-black">Verify two factors</h2><p className="mt-1 text-sm text-slate-500">Provide the account reference and answer every configured recovery question.</p></div><label className="block space-y-1 text-sm font-semibold">Admission number or employee ID<input className={field} required value={identityDetail} onChange={(event) => setIdentityDetail(event.target.value)} /></label>{questions.map((item) => <label key={item.questionKey} className="block space-y-1 text-sm font-semibold">{item.question}<input className={field} required autoComplete="off" value={answers[item.questionKey] || ''} onChange={(event) => setAnswers((current) => ({ ...current, [item.questionKey]: event.target.value }))}/></label>)}<button disabled={busy} className="w-full rounded-xl bg-indigo-600 py-3 font-bold text-white">{busy ? 'Verifying…' : 'Verify identity'}</button></form>}
    {step === 3 && <form onSubmit={finish} className="space-y-4"><div><h2 className="text-xl font-black">Create a new password</h2><p className="mt-1 text-sm text-slate-500">All existing sessions will be invalidated.</p></div><PasswordInput label="New password" showStrength value={password} onChange={(event) => setPassword(event.target.value)} autoComplete="new-password" required/><PasswordInput label="Confirm password" error={confirm && confirm !== password ? 'Passwords do not match' : ''} value={confirm} onChange={(event) => setConfirm(event.target.value)} autoComplete="new-password" required/><button disabled={busy} className="w-full rounded-xl bg-indigo-600 py-3 font-bold text-white">{busy ? 'Securing account…' : 'Set new password'}</button></form>}
    {step === 4 && <div className="py-5 text-center"><CheckCircle2 size={48} className="mx-auto text-emerald-600"/><h2 className="mt-4 text-2xl font-black">Password changed</h2><p className="mt-2 text-sm text-slate-500">Your sessions were invalidated. Sign in again with the new password.</p><Link to="/login" className="mt-6 inline-flex items-center gap-2 rounded-xl bg-indigo-600 px-5 py-3 font-bold text-white"><KeyRound size={17}/> Return to login</Link></div>}
    <Link to="/login" className="mt-5 block text-center text-sm font-semibold text-slate-500 hover:text-indigo-600">Back to sign in</Link></section></div></main>;
}
