export const adminModuleConfigs = {
  pages: {
    label: 'Pages Manager',
    endpoint: '/pages',
    idKey: '_id',
    idParam: 'pageId',
    fields: ['title', 'slug', 'pageType', 'metaTitle', 'metaDescription'],
    defaults: { title: '', slug: '', pageType: 'about', metaTitle: '', metaDescription: '' },
  },
  menus: {
    label: 'Menu Builder',
    endpoint: '/menus',
    idKey: '_id',
    idParam: 'menuId',
    fields: ['key', 'isPublished', 'items'],
    defaults: {
      key: 'header',
      isPublished: true,
      items: [
        { label: 'Home', href: '/', order: 1 },
        { label: 'About', href: '/about', order: 2 },
      ],
    },
  },
  events: {
    label: 'Events Manager',
    endpoint: '/events',
    idKey: '_id',
    idParam: 'eventId',
    fields: ['title', 'description', 'startDate', 'location', 'featured'],
    defaults: { title: '', description: '', startDate: '', location: '', featured: false },
  },
  gallery: {
    label: 'Gallery Manager',
    endpoint: '/gallery',
    idKey: '_id',
    idParam: 'albumId',
    fields: ['title', 'description', 'category', 'thumbnail'],
    defaults: { title: '', description: '', category: 'general', thumbnail: '' },
  },
  faculty: {
    label: 'Faculty Manager',
    endpoint: '/faculty',
    idKey: '_id',
    idParam: 'facultyId',
    fields: ['firstName', 'lastName', 'designation', 'qualification', 'experience', 'bio'],
    defaults: { firstName: '', lastName: '', designation: '', qualification: '', experience: 0, bio: '' },
  },
  notices: {
    label: 'News Manager',
    endpoint: '/notices',
    idKey: '_id',
    idParam: 'noticeId',
    fields: ['title', 'description', 'audience', 'isPinned', 'isPublished'],
    defaults: { title: '', description: '', audience: 'public', isPinned: false, isPublished: true },
  },
  admissions: {
    label: 'Admissions Enquiries',
    endpoint: '/admissions',
    idKey: '_id',
    idParam: 'enquiryId',
    fields: ['studentName', 'parentName', 'email', 'phone', 'classApplying', 'status'],
    defaults: { studentName: '', parentName: '', email: '', phone: '', classApplying: '', status: 'new' },
  },
  media: {
    label: 'Media Library',
    endpoint: '/media',
    idKey: '_id',
    idParam: 'mediaId',
    fields: ['fileName', 'fileType', 'mimeType', 'fileSize', 'url', 'folder'],
    defaults: { fileName: '', fileType: 'image', mimeType: 'image/jpeg', fileSize: 0, url: '', folder: 'general' },
  },
  careers: {
    label: 'Careers Manager',
    endpoint: '/careers',
    idKey: '_id',
    idParam: 'careerId',
    fields: ['position', 'qualification', 'experience', 'description', 'closesOn'],
    defaults: { position: '', qualification: '', experience: '', description: '', closesOn: '' },
  },
};

export const adminMenu = [
  { key: 'dashboard', label: 'Dashboard', path: '/admin/dashboard' },
  { key: 'pages', label: 'Pages', path: '/admin/pages' },
  { key: 'menus', label: 'Menu Builder', path: '/admin/menus' },
  { key: 'events', label: 'Events', path: '/admin/events' },
  { key: 'notices', label: 'News', path: '/admin/notices' },
  { key: 'gallery', label: 'Gallery', path: '/admin/gallery' },
  { key: 'faculty', label: 'Faculty', path: '/admin/faculty' },
  { key: 'admissions', label: 'Admissions', path: '/admin/admissions' },
  { key: 'careers', label: 'Careers', path: '/admin/careers' },
  { key: 'media', label: 'Media Library', path: '/admin/media' },
  { key: 'settings', label: 'Settings', path: '/admin/settings' },
];
