export const PERMISSIONS = Object.freeze({
  USERS_CREDENTIALS_VIEW: 'users.credentials.view',
  USERS_PASSWORD_RESET: 'users.password.reset',
  CURRICULUM_VIEW: 'curriculum.view',
  CURRICULUM_MANAGE: 'curriculum.manage',
  SUBJECTS_VIEW: 'subjects.view',
  SUBJECTS_CREATE: 'subjects.create',
  SUBJECTS_UPDATE: 'subjects.update',
  SUBJECTS_DELETE: 'subjects.delete',
  CHAPTERS_VIEW: 'chapters.view',
  CHAPTERS_MANAGE: 'chapters.manage',
  RESOURCES_MANAGE: 'academicResources.manage',
  WEEKLY_SLOTS_VIEW: 'weeklySlots.view',
  WEEKLY_SLOTS_MANAGE: 'weeklySlots.manage',
  CLASS_CURRICULUM_ASSIGN: 'classCurriculum.assign',
  SECTION_CURRICULUM_OVERRIDE: 'sectionCurriculum.override',
  CALENDAR_VIEW: 'academicCalendar.view',
  CALENDAR_MANAGE: 'academicCalendar.manage',
  FEES_VIEW: 'fees.view',
  FEES_CONFIGURE: 'fees.configure',
  FEES_COLLECT: 'fees.collect',
  FEES_ADJUST_REQUEST: 'fees.adjust.request',
  FEES_APPROVE: 'fees.approve',
  FEES_REPORT: 'fees.report',
  FEES_REMIND: 'fees.remind',
  HR_MANAGE: 'hr.manage',
  HR_SELF_SERVICE: 'hr.selfService',
});

const allCurriculum = [
  PERMISSIONS.CURRICULUM_VIEW, PERMISSIONS.CURRICULUM_MANAGE,
  PERMISSIONS.SUBJECTS_VIEW, PERMISSIONS.SUBJECTS_CREATE, PERMISSIONS.SUBJECTS_UPDATE, PERMISSIONS.SUBJECTS_DELETE,
  PERMISSIONS.CHAPTERS_VIEW, PERMISSIONS.CHAPTERS_MANAGE, PERMISSIONS.RESOURCES_MANAGE,
  PERMISSIONS.WEEKLY_SLOTS_VIEW, PERMISSIONS.WEEKLY_SLOTS_MANAGE,
  PERMISSIONS.CLASS_CURRICULUM_ASSIGN, PERMISSIONS.SECTION_CURRICULUM_OVERRIDE,
  PERMISSIONS.CALENDAR_VIEW,
];

export const ROLE_PERMISSIONS = Object.freeze({
  PLATFORM_OWNER: ['*'],
  SCHOOL_OWNER: ['*'],
  ADMIN: ['*'],
  FEE_MANAGER: [PERMISSIONS.FEES_VIEW, PERMISSIONS.FEES_COLLECT, PERMISSIONS.FEES_ADJUST_REQUEST, PERMISSIONS.FEES_REPORT, PERMISSIONS.FEES_REMIND],
  HR: [PERMISSIONS.HR_MANAGE, PERMISSIONS.HR_SELF_SERVICE],
  CURRICULUM_MANAGER: allCurriculum,
  TEACHER: [PERMISSIONS.CURRICULUM_VIEW, PERMISSIONS.SUBJECTS_VIEW, PERMISSIONS.CHAPTERS_VIEW, PERMISSIONS.CALENDAR_VIEW],
  STUDENT: [PERMISSIONS.CALENDAR_VIEW, PERMISSIONS.FEES_VIEW],
  PARENT: [PERMISSIONS.CALENDAR_VIEW, PERMISSIONS.FEES_VIEW],
  STAFF: [PERMISSIONS.CALENDAR_VIEW],
});

export const hasPermission = (role, permission) => {
  const granted = ROLE_PERMISSIONS[role] || [];
  return granted.includes('*') || granted.includes(permission);
};
