import React, { useMemo, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { KeyRound, LockKeyhole, Search, ShieldCheck, Unlock } from 'lucide-react';
import toast from 'react-hot-toast';
import DashboardLayout from '../../layouts/DashboardLayout';
import securityService from '../../services/securityService';
import PasswordInput from '../../components/ui/PasswordInput';

const formatDate = (value) => value ? new Intl.DateTimeFormat('en-IN', { dateStyle: 'medium' }).format(new Date(value)) : 'Never';

export default function LoginCredentialsPage() {
  const queryClient = useQueryClient();
  const [search, setSearch] = useState(''); const [role, setRole] = useState(''); const [status, setStatus] = useState('');
  const [selected, setSelected] = useState(null); const [method, setMethod] = useState('GENERATED'); const [password, setPassword] = useState(''); const [result, setResult] = useState(null);
  const query = useQuery({ queryKey: ['credential-accounts'], queryFn: () => securityService.credentials() });
  const rows = useMemo(() => (query.data?.data || []).filter((row) => (!role || row.role === role) && (!status || (status === 'LOCKED' ? row.locked : status === 'ACTIVE' ? row.active : !row.active)) && (!search || [row.name, row.loginId, row.referenceId, row.linkedStudent, row.className, row.sectionName].some((value) => String(value || '').toLowerCase().includes(search.toLowerCase())))), [query.data, role, status, search]);
  const reset = useMutation({ mutationFn: () => securityService.resetPassword(selected.accountKey, { method, password: method === 'MANUAL' ? password : undefined }), onSuccess: (response) => { setResult(response.data); toast.success('Password reset and sessions invalidated'); queryClient.invalidateQueries({ queryKey: ['credential-accounts'] }); }, onError: (error) => toast.error(error.response?.data?.message || 'Password reset failed') });
  const unlock = useMutation({ mutationFn: securityService.unlock, onSuccess: () => { toast.success('Account unlocked'); queryClient.invalidateQueries({ queryKey: ['credential-accounts'] }); } });
  const close = () => { setSelected(null); setResult(null); setPassword(''); setMethod('GENERATED'); };

  return <DashboardLayout role="ADMIN"><div className="space-y-6">
    <header className="rounded-3xl bg-gradient-to-r from-slate-950 to-indigo-950 p-7 text-white shadow-xl"><div className="flex items-center gap-3"><span className="rounded-2xl bg-white/10 p-3"><ShieldCheck /></span><div><h1 className="text-2xl font-black">Login credentials</h1><p className="text-sm text-slate-300">School-scoped account health and secure password resets. Passwords and recovery answers are never shown.</p></div></div></header>
    <section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><div className="grid gap-3 md:grid-cols-[1fr,180px,180px]"><label className="relative"><Search className="absolute left-3 top-3 text-slate-400" size={18}/><input aria-label="Search credential accounts" className="h-11 w-full rounded-xl border border-slate-300 pl-10 pr-3 dark:border-slate-700 dark:bg-slate-950" placeholder="Name, login ID, admission or employee ID…" value={search} onChange={(event) => setSearch(event.target.value)} /></label><select aria-label="Filter by role" className="rounded-xl border border-slate-300 px-3 dark:border-slate-700 dark:bg-slate-950" value={role} onChange={(event) => setRole(event.target.value)}><option value="">All roles</option>{['SCHOOL_OWNER','ADMIN','CURRICULUM_MANAGER','TEACHER','STAFF','STUDENT','PARENT'].map((item) => <option key={item}>{item}</option>)}</select><select aria-label="Filter by account state" className="rounded-xl border border-slate-300 px-3 dark:border-slate-700 dark:bg-slate-950" value={status} onChange={(event) => setStatus(event.target.value)}><option value="">All states</option><option value="ACTIVE">Active</option><option value="INACTIVE">Inactive</option><option value="LOCKED">Locked</option></select></div></section>
    <section className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm dark:border-slate-800 dark:bg-slate-900">{query.isLoading ? <div className="p-8 text-sm text-slate-500">Loading accounts…</div> : query.isError ? <div className="p-8 text-rose-600">Could not load accounts. <button onClick={() => query.refetch()} className="underline">Retry</button></div> : !rows.length ? <div className="p-10 text-center text-slate-500">No accounts match these filters.</div> : <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500 dark:bg-slate-950"><tr><th className="p-4">User</th><th className="p-4">Role / placement</th><th className="p-4">Security</th><th className="p-4">Activity</th><th className="p-4 text-right">Actions</th></tr></thead><tbody>{rows.map((row) => <tr key={row.accountKey} className="border-t border-slate-100 dark:border-slate-800"><td className="p-4"><p className="font-bold">{row.name || 'Unnamed account'}</p><p className="font-mono text-xs text-slate-500">{row.loginId}</p><p className="text-xs text-slate-500">{row.referenceId}</p></td><td className="p-4"><span className="rounded-full bg-indigo-50 px-2.5 py-1 text-xs font-bold text-indigo-700">{row.role.replaceAll('_',' ')}</span><p className="mt-2 text-xs text-slate-500">{[row.className, row.sectionName].filter(Boolean).join(' · ') || 'School-wide'}</p></td><td className="p-4"><p className={row.securityConfigured ? 'text-emerald-700' : 'text-amber-700'}>{row.securityConfigured ? 'Recovery configured' : 'Setup missing'}</p><p className="text-xs text-slate-500">{row.locked ? 'Locked' : row.active ? 'Active' : 'Inactive'}</p></td><td className="p-4 text-xs text-slate-500"><p>Last login: {formatDate(row.lastLoginAt)}</p><p>Password: {formatDate(row.passwordChangedAt)}</p></td><td className="p-4"><div className="flex justify-end gap-2">{row.locked && <button title="Unlock account" onClick={() => unlock.mutate(row.accountKey)} className="rounded-xl border p-2 text-emerald-700"><Unlock size={17}/></button>}<button onClick={() => setSelected(row)} className="inline-flex items-center gap-2 rounded-xl bg-slate-900 px-3 py-2 text-xs font-bold text-white"><KeyRound size={15}/> Reset</button></div></td></tr>)}</tbody></table></div>}</section>
    {selected && <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/60 p-4" role="dialog" aria-modal="true"><div className="w-full max-w-lg rounded-3xl bg-white p-6 shadow-2xl dark:bg-slate-900"><div className="flex gap-3"><span className="rounded-2xl bg-amber-50 p-3 text-amber-700"><LockKeyhole/></span><div><h2 className="text-xl font-black">Reset password</h2><p className="text-sm text-slate-500">{selected.name} · {selected.role.replaceAll('_',' ')} · {selected.loginId}</p></div></div>{result ? <div className="mt-5 space-y-4"><div className="rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-950"><p className="font-bold">Copy this temporary credential now</p><p className="mt-2 font-mono text-lg">{result.temporaryPassword}</p><p className="mt-2 text-xs">It is returned once and must be changed after sign-in.</p></div><button onClick={() => navigator.clipboard.writeText(`Login ID: ${result.loginId}\nTemporary password: ${result.temporaryPassword}`).then(() => toast.success('Credential copied'))} className="w-full rounded-xl bg-indigo-600 py-3 font-bold text-white">Copy credential</button></div> : <div className="mt-5 space-y-4"><div className="grid grid-cols-2 gap-2">{['GENERATED','MANUAL'].map((item) => <button key={item} onClick={() => setMethod(item)} className={`rounded-xl border p-3 text-sm font-bold ${method === item ? 'border-indigo-600 bg-indigo-50 text-indigo-700' : 'border-slate-200'}`}>{item === 'GENERATED' ? 'Generate securely' : 'Enter manually'}</button>)}</div>{method === 'MANUAL' && <PasswordInput label="New temporary password" showStrength value={password} onChange={(event) => setPassword(event.target.value)} autoComplete="new-password" />}<p className="text-xs text-slate-500">Continuing invalidates all existing sessions and forces a password change at next login.</p><button disabled={reset.isPending} onClick={() => reset.mutate()} className="w-full rounded-xl bg-rose-600 py-3 font-bold text-white disabled:opacity-60">{reset.isPending ? 'Resetting…' : 'Confirm password reset'}</button></div>}<button onClick={close} className="mt-3 w-full rounded-xl border border-slate-300 py-2.5 text-sm font-bold">Close</button></div></div>}
  </div></DashboardLayout>;
}
