export const WEEK_DAYS = ['MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY'];

export const PERIOD_TEMPLATE = [
  { periodNumber: 1, startTime: '08:00', endTime: '08:40', isActivityPeriod: false },
  { periodNumber: 2, startTime: '08:40', endTime: '09:20', isActivityPeriod: false },
  { periodNumber: 3, startTime: '09:20', endTime: '10:00', isActivityPeriod: false },
  { periodNumber: 4, startTime: '10:00', endTime: '10:40', isActivityPeriod: false },
  { periodNumber: 5, startTime: '11:00', endTime: '11:40', isActivityPeriod: false },
  { periodNumber: 6, startTime: '11:40', endTime: '12:20', isActivityPeriod: false },
  { periodNumber: 7, startTime: '12:20', endTime: '13:00', isActivityPeriod: false },
  { periodNumber: 8, startTime: '13:00', endTime: '13:40', isActivityPeriod: true },
];

export const ACADEMIC_LEVELS = [
  { code: 'PRE_PRIMARY', name: 'Pre-Primary', minClassOrder: 1, maxClassOrder: 2, displayOrder: 1 },
  { code: 'PRIMARY', name: 'Primary', minClassOrder: 3, maxClassOrder: 7, displayOrder: 2 },
  { code: 'MIDDLE', name: 'Middle', minClassOrder: 8, maxClassOrder: 10, displayOrder: 3 },
  { code: 'SECONDARY', name: 'Secondary', minClassOrder: 11, maxClassOrder: 12, displayOrder: 4 },
  { code: 'SENIOR_SECONDARY', name: 'Senior Secondary', minClassOrder: 13, maxClassOrder: 14, displayOrder: 5 },
];

export const OPTIONAL_ACTIVITIES = [
  { name: 'Sports', code: 'ACT_SPORTS', capacity: 80, displayOrder: 1 },
  { name: 'Yoga', code: 'ACT_YOGA', capacity: 40, displayOrder: 2 },
  { name: 'Dance', code: 'ACT_DANCE', capacity: 40, displayOrder: 3 },
  { name: 'Music', code: 'ACT_MUSIC', capacity: 40, displayOrder: 4 },
  { name: 'Drama', code: 'ACT_DRAMA', capacity: 35, displayOrder: 5 },
  { name: 'Robotics', code: 'ACT_ROBOTICS', capacity: 30, displayOrder: 6 },
  { name: 'Coding Club', code: 'ACT_CODING', capacity: 30, displayOrder: 7 },
  { name: 'Debate', code: 'ACT_DEBATE', capacity: 35, displayOrder: 8 },
  { name: 'Art Club', code: 'ACT_ART', capacity: 35, displayOrder: 9 },
  { name: 'Chess', code: 'ACT_CHESS', capacity: 30, displayOrder: 10 },
  { name: 'Photography', code: 'ACT_PHOTO', capacity: 25, displayOrder: 11 },
];

export const SUBJECT_MASTER = [
  { name: 'Science', code: 'SCI', subjectType: 'CORE', isLab: false, isOptional: false, displayOrder: 10 },
  { name: 'Physics', code: 'PHY', subjectType: 'CORE', isLab: false, isOptional: false, displayOrder: 11, parentCode: 'SCI' },
  { name: 'Chemistry', code: 'CHE', subjectType: 'CORE', isLab: false, isOptional: false, displayOrder: 12, parentCode: 'SCI' },
  { name: 'Biology', code: 'BIO', subjectType: 'CORE', isLab: false, isOptional: false, displayOrder: 13, parentCode: 'SCI' },
  { name: 'Physics Lab', code: 'PHY_LAB', subjectType: 'LAB', isLab: true, isOptional: false, displayOrder: 14, parentCode: 'PHY' },
  { name: 'Chemistry Lab', code: 'CHE_LAB', subjectType: 'LAB', isLab: true, isOptional: false, displayOrder: 15, parentCode: 'CHE' },
  { name: 'Social Science', code: 'SST', subjectType: 'CORE', isLab: false, isOptional: false, displayOrder: 20 },
  { name: 'History', code: 'HIS', subjectType: 'CORE', isLab: false, isOptional: false, displayOrder: 21, parentCode: 'SST' },
  { name: 'Geography', code: 'GEO', subjectType: 'CORE', isLab: false, isOptional: false, displayOrder: 22, parentCode: 'SST' },
  { name: 'Civics', code: 'CIV', subjectType: 'CORE', isLab: false, isOptional: false, displayOrder: 23, parentCode: 'SST' },
  { name: 'Economics', code: 'ECO', subjectType: 'CORE', isLab: false, isOptional: false, displayOrder: 24, parentCode: 'SST' },
  { name: 'English', code: 'ENG', subjectType: 'CORE', isLab: false, isOptional: false, displayOrder: 1 },
  { name: 'Hindi', code: 'HIN', subjectType: 'CORE', isLab: false, isOptional: false, displayOrder: 2 },
  { name: 'Sanskrit', code: 'SAN', subjectType: 'CORE', isLab: false, isOptional: false, displayOrder: 3 },
  { name: 'Mathematics', code: 'MAT', subjectType: 'CORE', isLab: false, isOptional: false, displayOrder: 4 },
  { name: 'EVS', code: 'EVS', subjectType: 'CORE', isLab: false, isOptional: false, displayOrder: 5 },
  { name: 'Drawing', code: 'DRW', subjectType: 'ACTIVITY', isLab: false, isOptional: false, displayOrder: 30 },
  { name: 'Rhymes', code: 'RHY', subjectType: 'CORE', isLab: false, isOptional: false, displayOrder: 31 },
  { name: 'Computer Basics', code: 'CB', subjectType: 'CORE', isLab: false, isOptional: false, displayOrder: 32 },
  { name: 'Computer', code: 'COMP', subjectType: 'CORE', isLab: false, isOptional: false, displayOrder: 33 },
  { name: 'Computer Science', code: 'CS', subjectType: 'CORE', isLab: false, isOptional: false, displayOrder: 34 },
  { name: 'GK', code: 'GK', subjectType: 'CORE', isLab: false, isOptional: false, displayOrder: 35 },
  { name: 'Moral Science', code: 'MS', subjectType: 'CORE', isLab: false, isOptional: false, displayOrder: 36 },
  { name: 'Physical Education', code: 'PE', subjectType: 'CORE', isLab: false, isOptional: false, displayOrder: 37 },
  { name: 'Music', code: 'MUS', subjectType: 'ACTIVITY', isLab: false, isOptional: false, displayOrder: 38 },
  { name: 'Activity', code: 'ACT', subjectType: 'ACTIVITY', isLab: false, isOptional: true, displayOrder: 39 },
  { name: 'Art', code: 'ART', subjectType: 'ACTIVITY', isLab: false, isOptional: false, displayOrder: 40 },
  { name: 'Value Education', code: 'VAL', subjectType: 'CORE', isLab: false, isOptional: false, displayOrder: 41 },
  { name: 'Library', code: 'LIB', subjectType: 'CORE', isLab: false, isOptional: false, displayOrder: 42 },
  { name: 'Commerce', code: 'COM', subjectType: 'CORE', isLab: false, isOptional: false, displayOrder: 50 },
  { name: 'Humanities', code: 'HUM', subjectType: 'CORE', isLab: false, isOptional: false, displayOrder: 51 },
];

export const STREAM_DEFINITIONS = [
  {
    code: 'PCM',
    name: 'Science PCM',
    subjects: [
      { code: 'PHY', periodsPerWeek: 7, isMandatory: true, displayOrder: 1 },
      { code: 'CHE', periodsPerWeek: 7, isMandatory: true, displayOrder: 2 },
      { code: 'MAT', periodsPerWeek: 7, isMandatory: true, displayOrder: 3 },
      { code: 'ENG', periodsPerWeek: 5, isMandatory: true, displayOrder: 4 },
      { code: 'CS', periodsPerWeek: 6, isMandatory: true, displayOrder: 5 },
      { code: 'PE', periodsPerWeek: 4, isMandatory: true, displayOrder: 6 },
      { code: 'PHY_LAB', periodsPerWeek: 4, isMandatory: true, displayOrder: 7 },
      { code: 'CHE_LAB', periodsPerWeek: 4, isMandatory: true, displayOrder: 8 },
      { code: 'LIB', periodsPerWeek: 2, isMandatory: true, displayOrder: 9 },
      { code: 'VAL', periodsPerWeek: 2, isMandatory: true, displayOrder: 10 },
    ],
  },
  {
    code: 'PCB',
    name: 'Science PCB',
    subjects: [
      { code: 'PHY', periodsPerWeek: 7, isMandatory: true, displayOrder: 1 },
      { code: 'CHE', periodsPerWeek: 7, isMandatory: true, displayOrder: 2 },
      { code: 'BIO', periodsPerWeek: 7, isMandatory: true, displayOrder: 3 },
      { code: 'ENG', periodsPerWeek: 5, isMandatory: true, displayOrder: 4 },
      { code: 'CS', periodsPerWeek: 6, isMandatory: true, displayOrder: 5 },
      { code: 'PE', periodsPerWeek: 4, isMandatory: true, displayOrder: 6 },
      { code: 'PHY_LAB', periodsPerWeek: 4, isMandatory: true, displayOrder: 7 },
      { code: 'CHE_LAB', periodsPerWeek: 4, isMandatory: true, displayOrder: 8 },
      { code: 'LIB', periodsPerWeek: 2, isMandatory: true, displayOrder: 9 },
      { code: 'VAL', periodsPerWeek: 2, isMandatory: true, displayOrder: 10 },
    ],
  },
  {
    code: 'PCMB',
    name: 'Science PCMB',
    subjects: [
      { code: 'PHY', periodsPerWeek: 6, isMandatory: true, displayOrder: 1 },
      { code: 'CHE', periodsPerWeek: 6, isMandatory: true, displayOrder: 2 },
      { code: 'MAT', periodsPerWeek: 6, isMandatory: true, displayOrder: 3 },
      { code: 'BIO', periodsPerWeek: 6, isMandatory: true, displayOrder: 4 },
      { code: 'ENG', periodsPerWeek: 5, isMandatory: true, displayOrder: 5 },
      { code: 'CS', periodsPerWeek: 5, isMandatory: true, displayOrder: 6 },
      { code: 'PE', periodsPerWeek: 4, isMandatory: true, displayOrder: 7 },
      { code: 'PHY_LAB', periodsPerWeek: 4, isMandatory: true, displayOrder: 8 },
      { code: 'CHE_LAB', periodsPerWeek: 4, isMandatory: true, displayOrder: 9 },
      { code: 'LIB', periodsPerWeek: 1, isMandatory: true, displayOrder: 10 },
      { code: 'VAL', periodsPerWeek: 1, isMandatory: true, displayOrder: 11 },
    ],
  },
  {
    code: 'COM',
    name: 'Commerce',
    subjects: [
      { code: 'ENG', periodsPerWeek: 6, isMandatory: true, displayOrder: 1 },
      { code: 'ECO', periodsPerWeek: 7, isMandatory: true, displayOrder: 2 },
      { code: 'MAT', periodsPerWeek: 7, isMandatory: true, displayOrder: 3 },
      { code: 'CS', periodsPerWeek: 6, isMandatory: true, displayOrder: 4 },
      { code: 'PE', periodsPerWeek: 4, isMandatory: true, displayOrder: 5 },
      { code: 'LIB', periodsPerWeek: 2, isMandatory: true, displayOrder: 6 },
      { code: 'VAL', periodsPerWeek: 2, isMandatory: true, displayOrder: 7 },
      { code: 'ACT', periodsPerWeek: 4, isMandatory: false, isOptional: true, displayOrder: 8 },
      { code: 'HIS', periodsPerWeek: 5, isMandatory: true, displayOrder: 9 },
      { code: 'GEO', periodsPerWeek: 5, isMandatory: true, displayOrder: 10 },
    ],
  },
  {
    code: 'HUM',
    name: 'Humanities',
    subjects: [
      { code: 'ENG', periodsPerWeek: 6, isMandatory: true, displayOrder: 1 },
      { code: 'HIS', periodsPerWeek: 7, isMandatory: true, displayOrder: 2 },
      { code: 'GEO', periodsPerWeek: 7, isMandatory: true, displayOrder: 3 },
      { code: 'CIV', periodsPerWeek: 6, isMandatory: true, displayOrder: 4 },
      { code: 'ECO', periodsPerWeek: 6, isMandatory: true, displayOrder: 5 },
      { code: 'PE', periodsPerWeek: 4, isMandatory: true, displayOrder: 6 },
      { code: 'LIB', periodsPerWeek: 2, isMandatory: true, displayOrder: 7 },
      { code: 'VAL', periodsPerWeek: 2, isMandatory: true, displayOrder: 8 },
      { code: 'CS', periodsPerWeek: 4, isMandatory: false, isOptional: true, displayOrder: 9 },
      { code: 'ACT', periodsPerWeek: 4, isMandatory: false, isOptional: true, displayOrder: 10 },
    ],
  },
];

export const CLASS_WEEKLY_SUBJECTS = {
  LKG: [
    { name: 'English', periodsPerWeek: 10 },
    { name: 'Hindi', periodsPerWeek: 8 },
    { name: 'Mathematics', periodsPerWeek: 10 },
    { name: 'EVS', periodsPerWeek: 8 },
    { name: 'Drawing', periodsPerWeek: 4 },
    { name: 'Rhymes', periodsPerWeek: 4 },
    { name: 'Computer Basics', periodsPerWeek: 2 },
    { name: 'Physical Education', periodsPerWeek: 2 },
  ],
  UKG: [
    { name: 'English', periodsPerWeek: 10 },
    { name: 'Hindi', periodsPerWeek: 8 },
    { name: 'Mathematics', periodsPerWeek: 10 },
    { name: 'EVS', periodsPerWeek: 8 },
    { name: 'Drawing', periodsPerWeek: 4 },
    { name: 'Rhymes', periodsPerWeek: 4 },
    { name: 'Computer Basics', periodsPerWeek: 2 },
    { name: 'Physical Education', periodsPerWeek: 2 },
  ],
  PRIMARY_1_5: [
    { name: 'English', periodsPerWeek: 8 },
    { name: 'Hindi', periodsPerWeek: 8 },
    { name: 'Mathematics', periodsPerWeek: 8 },
    { name: 'EVS', periodsPerWeek: 6 },
    { name: 'Computer', periodsPerWeek: 2 },
    { name: 'GK', periodsPerWeek: 2 },
    { name: 'Drawing', periodsPerWeek: 2 },
    { name: 'Moral Science', periodsPerWeek: 2 },
    { name: 'Physical Education', periodsPerWeek: 4 },
    { name: 'Music', periodsPerWeek: 2 },
    { name: 'Activity', periodsPerWeek: 4, isOptional: true },
  ],
  MIDDLE_6_8: [
    { name: 'English', periodsPerWeek: 7 },
    { name: 'Hindi', periodsPerWeek: 6 },
    { name: 'Sanskrit', periodsPerWeek: 5 },
    { name: 'Mathematics', periodsPerWeek: 7 },
    { name: 'Science', periodsPerWeek: 7 },
    { name: 'Social Science', periodsPerWeek: 6 },
    { name: 'Computer', periodsPerWeek: 2 },
    { name: 'GK', periodsPerWeek: 2 },
    { name: 'Art', periodsPerWeek: 2 },
    { name: 'Music', periodsPerWeek: 2 },
    { name: 'Physical Education', periodsPerWeek: 2 },
  ],
  SECONDARY_9_10: [
    { name: 'English', periodsPerWeek: 6 },
    { name: 'Hindi', periodsPerWeek: 6 },
    { name: 'Mathematics', periodsPerWeek: 7 },
    { name: 'Science', periodsPerWeek: 9 },
    { name: 'Social Science', periodsPerWeek: 8 },
    { name: 'Computer', periodsPerWeek: 2 },
    { name: 'Physical Education', periodsPerWeek: 4 },
    { name: 'Art', periodsPerWeek: 2 },
    { name: 'Value Education', periodsPerWeek: 2 },
    { name: 'Library', periodsPerWeek: 2 },
  ],
};

export const SCIENCE_COMPONENT_SPLIT = [
  { componentName: 'Physics', code: 'SCI_PHY', periodsPerWeek: 3, displayOrder: 1 },
  { componentName: 'Chemistry', code: 'SCI_CHE', periodsPerWeek: 3, displayOrder: 2 },
  { componentName: 'Biology', code: 'SCI_BIO', periodsPerWeek: 3, displayOrder: 3 },
];

export const CLASS_NAMES = ['LKG', 'UKG', ...Array.from({ length: 12 }, (_, index) => `Class ${index + 1}`)];

export const SENIOR_SECTION_CATALOG = ['PCM-A', 'PCB-A', 'PCMB-A', 'COM-A', 'HUM-A'];
