export const WIDGET_CATALOG = [
  {
    key: 'school-kpis',
    title: 'School KPIs',
    description: 'Core counts across students, staff, classes, and sections.',
    kind: 'stats',
    size: 'lg',
    roles: ['PLATFORM_OWNER', 'SCHOOL_OWNER', 'ADMIN'],
    icon: 'Building2',
  },
  {
    key: 'curriculum-health',
    title: 'Curriculum Health',
    description: 'Subjects, requirements, and assignment coverage.',
    kind: 'stats',
    size: 'lg',
    roles: ['PLATFORM_OWNER', 'SCHOOL_OWNER', 'ADMIN', 'TEACHER'],
    icon: 'BookOpenCheck',
  },
  {
    key: 'timetable-health',
    title: 'Timetable Health',
    description: 'Timetable bodies, slots, and activity-period coverage.',
    kind: 'stats',
    size: 'lg',
    roles: ['PLATFORM_OWNER', 'SCHOOL_OWNER', 'ADMIN', 'TEACHER'],
    icon: 'CalendarRange',
  },
  {
    key: 'teacher-load',
    title: 'Teacher Load',
    description: 'Assignment volume and load balancing across teachers.',
    kind: 'stats',
    size: 'md',
    roles: ['PLATFORM_OWNER', 'SCHOOL_OWNER', 'ADMIN'],
    icon: 'UsersRound',
  },
  {
    key: 'academic-levels',
    title: 'Academic Levels',
    description: 'Configured academic levels and class ranges.',
    kind: 'list',
    size: 'md',
    roles: ['PLATFORM_OWNER', 'SCHOOL_OWNER', 'ADMIN'],
    icon: 'Layers3',
  },
  {
    key: 'streams',
    title: 'Streams',
    description: 'Senior secondary stream definitions and mappings.',
    kind: 'list',
    size: 'md',
    roles: ['PLATFORM_OWNER', 'SCHOOL_OWNER', 'ADMIN'],
    icon: 'Shuffle',
  },
  {
    key: 'section-map',
    title: 'Section Map',
    description: 'Class-to-section distribution by grade.',
    kind: 'list',
    size: 'md',
    roles: ['PLATFORM_OWNER', 'SCHOOL_OWNER', 'ADMIN'],
    icon: 'GitBranch',
  },
  {
    key: 'subject-map',
    title: 'Subject Map',
    description: 'How subjects are mapped into classes and sections.',
    kind: 'list',
    size: 'md',
    roles: ['PLATFORM_OWNER', 'SCHOOL_OWNER', 'ADMIN', 'TEACHER'],
    icon: 'LibraryBig',
  },
  {
    key: 'gallery-highlights',
    title: 'Gallery Highlights',
    description: 'Latest visible gallery groups and photo counts.',
    kind: 'list',
    size: 'md',
    roles: ['PLATFORM_OWNER', 'SCHOOL_OWNER', 'ADMIN', 'TEACHER', 'PARENT', 'STUDENT', 'STAFF'],
    icon: 'Images',
  },
  {
    key: 'school-branding',
    title: 'School Branding',
    description: 'Current logo, colors, and public-facing contact details.',
    kind: 'summary',
    size: 'md',
    roles: ['PLATFORM_OWNER', 'SCHOOL_OWNER', 'ADMIN'],
    icon: 'Palette',
  },
  {
    key: 'quick-actions',
    title: 'Quick Actions',
    description: 'Role-specific shortcuts to the most common tasks.',
    kind: 'actions',
    size: 'md',
    roles: ['PLATFORM_OWNER', 'SCHOOL_OWNER', 'ADMIN', 'TEACHER', 'PARENT', 'STUDENT', 'STAFF'],
    icon: 'Bolt',
  },
  {
    key: 'pending-todos',
    title: 'Pending Todos',
    description: 'Open tasks assigned to the current user.',
    kind: 'list',
    size: 'md',
    roles: ['PLATFORM_OWNER', 'SCHOOL_OWNER', 'ADMIN', 'TEACHER', 'PARENT', 'STUDENT', 'STAFF'],
    icon: 'CheckSquare',
  },
  {
    key: 'notes',
    title: 'Notes',
    description: 'Pinned and recent notes for the current user.',
    kind: 'editor',
    size: 'md',
    roles: ['PLATFORM_OWNER', 'SCHOOL_OWNER', 'ADMIN', 'TEACHER', 'PARENT', 'STUDENT', 'STAFF'],
    icon: 'StickyNote',
  },
  {
    key: 'bookmarks',
    title: 'Bookmarks',
    description: 'Saved links and external shortcuts.',
    kind: 'list',
    size: 'md',
    roles: ['PLATFORM_OWNER', 'SCHOOL_OWNER', 'ADMIN', 'TEACHER', 'PARENT', 'STUDENT', 'STAFF'],
    icon: 'Bookmark',
  },
  {
    key: 'notifications',
    title: 'Notifications',
    description: 'Unread and recent in-app notices.',
    kind: 'list',
    size: 'md',
    roles: ['PLATFORM_OWNER', 'SCHOOL_OWNER', 'ADMIN', 'TEACHER', 'PARENT', 'STUDENT', 'STAFF'],
    icon: 'BellRing',
  },
  {
    key: 'activity-feed',
    title: 'Activity Feed',
    description: 'Recent widget activity captured for the user.',
    kind: 'list',
    size: 'md',
    roles: ['PLATFORM_OWNER', 'SCHOOL_OWNER', 'ADMIN', 'TEACHER', 'PARENT', 'STUDENT', 'STAFF'],
    icon: 'Sparkles',
  },
  {
    key: 'login-streak',
    title: 'Login Streak',
    description: 'Current login streak and best streak for the user.',
    kind: 'summary',
    size: 'sm',
    roles: ['PLATFORM_OWNER', 'SCHOOL_OWNER', 'ADMIN', 'TEACHER', 'PARENT', 'STUDENT', 'STAFF'],
    icon: 'Flame',
  },
  {
    key: 'lab-ready',
    title: 'Lab Ready',
    description: 'Lab rooms and lab-linked subject rules.',
    kind: 'stats',
    size: 'md',
    roles: ['PLATFORM_OWNER', 'SCHOOL_OWNER', 'ADMIN', 'TEACHER'],
    icon: 'FlaskConical',
  },
  {
    key: 'activity-planner',
    title: 'Activity Planner',
    description: 'Optional activities and capacity snapshots.',
    kind: 'list',
    size: 'md',
    roles: ['PLATFORM_OWNER', 'SCHOOL_OWNER', 'ADMIN', 'TEACHER'],
    icon: 'CalendarPlus',
  },
  {
    key: 'system-content',
    title: 'System Content',
    description: 'Published school notices and system copy blocks.',
    kind: 'list',
    size: 'lg',
    roles: ['PLATFORM_OWNER', 'SCHOOL_OWNER', 'ADMIN', 'TEACHER', 'PARENT', 'STUDENT', 'STAFF'],
    icon: 'FileText',
  },
];

export const ROLE_WIDGET_MAP = WIDGET_CATALOG.reduce((accumulator, widget) => {
  for (const role of widget.roles) {
    if (!accumulator[role]) {
      accumulator[role] = [];
    }
    accumulator[role].push(widget.key);
  }
  return accumulator;
}, {});

export const getWidgetsForRole = (role) => {
  const allowed = ROLE_WIDGET_MAP[role] || [];
  return WIDGET_CATALOG.filter((widget) => allowed.includes(widget.key));
};
