import React, { useMemo, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { CalendarDays, CalendarPlus, List, Trash2 } from 'lucide-react';
import toast from 'react-hot-toast';
import DashboardLayout from '../../layouts/DashboardLayout';
import AttendanceCalendar from '../../components/attendance/AttendanceCalendar';
import { Button } from '../../components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '../../components/ui/card';
import { attendanceService } from '../../services/managementService';
import { authService } from '../../services/authService';

const today = () => new Date().toISOString().slice(0, 10);
const TYPES = ['HOLIDAY', 'WORKING_DAY', 'WEEKLY_OFF', 'EXAM', 'EVENT', 'VACATION'];

export default function AcademicCalendarPage() {
  const user = authService.getCurrentUser();
  const qc = useQueryClient();
  const [month, setMonth] = useState(today().slice(0, 7));
  const [view, setView] = useState('MONTH');
  const [typeFilter, setTypeFilter] = useState('');
  const [form, setForm] = useState({ date: today(), dayType: 'HOLIDAY', title: '', description: '' });
  const query = useQuery({ queryKey: ['academic-calendar', month], queryFn: () => attendanceService.calendar({ month }) });
  const records = query.data?.data?.days || [];
  const filteredRecords = useMemo(() => records.filter((row) => !typeFilter || row.dayType === typeFilter || row.eventType === typeFilter), [records, typeFilter]);
  const recordByDate = useMemo(() => new Map(filteredRecords.map((row) => [row.date, row])), [filteredRecords]);
  const canManage = ['ADMIN', 'SCHOOL_OWNER'].includes(user?.role);
  const visibleAgenda = useMemo(() => view !== 'WEEK' ? filteredRecords : filteredRecords.filter((row) => { const event = new Date(`${row.date}T00:00:00`); const now = new Date(); const start = new Date(now); start.setDate(now.getDate() - now.getDay()); start.setHours(0,0,0,0); const end = new Date(start); end.setDate(start.getDate() + 7); return event >= start && event < end; }), [filteredRecords, view]);
  const days = useMemo(() => { const [y, m] = month.split('-').map(Number); return Array.from({ length: new Date(Date.UTC(y, m, 0)).getUTCDate() }, (_, i) => { const date = `${month}-${String(i + 1).padStart(2, '0')}`; const saved = recordByDate.get(date); return saved || { date, dayType: new Date(`${date}T00:00:00Z`).getUTCDay() === 0 ? 'WEEKLY_OFF' : 'WORKING_DAY', title: null }; }); }, [month, recordByDate]);
  const save = useMutation({ mutationFn: attendanceService.saveCalendarDay, onSuccess: () => { toast.success('Calendar updated'); qc.invalidateQueries({ queryKey: ['academic-calendar', month] }); }, onError: (e) => toast.error(e.response?.data?.message || 'Could not save event') });
  const remove = useMutation({ mutationFn: attendanceService.deleteCalendarDay, onSuccess: () => { toast.success('Marker removed'); qc.invalidateQueries({ queryKey: ['academic-calendar', month] }); } });
  const choose = (day) => { const saved = recordByDate.get(day.date); setForm({ date: day.date, dayType: saved?.dayType || day.dayType, title: saved?.title || '', description: saved?.description || '' }); };
  return <DashboardLayout role={user?.role}><div className="space-y-5"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-sm font-semibold uppercase text-slate-500">School calendar</p><h1 className="text-2xl font-bold">Academic calendar</h1><p className="text-sm text-slate-500">Visible events are filtered for your school, role, class and section.</p></div><div className="flex flex-wrap gap-2"><select aria-label="Filter events by type" className="h-10 rounded-xl border px-3 dark:bg-slate-950" value={typeFilter} onChange={(e)=>setTypeFilter(e.target.value)}><option value="">All event types</option>{TYPES.map(type=><option key={type}>{type.replaceAll('_',' ')}</option>)}</select><input type="month" className="h-10 rounded-xl border px-3 dark:bg-slate-950" value={month} onChange={(e) => setMonth(e.target.value)}/></div></div>
  <div className="inline-flex rounded-xl bg-slate-100 p-1 dark:bg-slate-900">{[['MONTH',CalendarDays],['WEEK',CalendarDays],['AGENDA',List]].map(([name,Icon])=><button key={name} onClick={()=>setView(name)} className={`inline-flex items-center gap-2 rounded-lg px-3 py-2 text-xs font-bold ${view===name?'bg-white text-blue-700 shadow-sm dark:bg-slate-800':'text-slate-500'}`}><Icon size={15}/>{name}</button>)}</div>
  {query.isError && <div className="rounded-2xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-700">Calendar could not be loaded. <button className="font-bold underline" onClick={()=>query.refetch()}>Retry</button></div>}
  <div className={`grid gap-5 ${canManage ? 'xl:grid-cols-[1fr_340px]' : ''}`}><Card><CardHeader><CardTitle>{view === 'MONTH' ? 'Month view' : view === 'WEEK' ? 'This week' : 'Agenda'}</CardTitle></CardHeader><CardContent>{query.isLoading ? <div className="h-72 animate-pulse rounded-2xl bg-slate-100 dark:bg-slate-800"/> : view === 'MONTH' ? <AttendanceCalendar month={month} days={days} onSelectDay={canManage ? choose : undefined}/> : !visibleAgenda.length ? <div className="py-16 text-center text-sm text-slate-500">No visible events match this view.</div> : <div className="space-y-3">{visibleAgenda.map(row=><article key={row.id} className="flex gap-4 rounded-2xl border p-4 dark:border-slate-700"><div className="min-w-16 text-center"><p className="text-xs font-bold uppercase text-slate-500">{new Date(`${row.date}T00:00:00`).toLocaleDateString('en-IN',{month:'short'})}</p><p className="text-2xl font-black">{new Date(`${row.date}T00:00:00`).getDate()}</p></div><div><span className="rounded-full bg-blue-50 px-2 py-1 text-xs font-bold text-blue-700">{(row.eventType||row.dayType).replaceAll('_',' ')}</span><h3 className="mt-2 font-black">{row.title||row.dayType.replaceAll('_',' ')}</h3><p className="mt-1 text-sm text-slate-500">{row.description||'No additional details.'}</p></div></article>)}</div>}</CardContent></Card>{canManage&&<Card><CardHeader><CardTitle>Add or edit a day</CardTitle></CardHeader><CardContent className="space-y-3"><input type="date" className="h-10 w-full rounded-md border px-3 dark:bg-slate-950" value={form.date} onChange={(e) => setForm((old) => ({ ...old, date: e.target.value }))}/><div className="grid grid-cols-2 gap-2">{TYPES.map((type) => <button key={type} type="button" onClick={() => setForm((old) => ({ ...old, dayType: type }))} className={`rounded-lg border p-2 text-xs font-bold ${form.dayType === type ? 'border-blue-500 bg-blue-50 text-blue-700' : 'dark:border-slate-700'}`}>{type.replace(/_/g, ' ')}</button>)}</div><input className="h-10 w-full rounded-md border px-3 dark:bg-slate-950" placeholder="Event title" value={form.title} onChange={(e) => setForm((old) => ({ ...old, title: e.target.value }))}/><textarea className="min-h-24 w-full rounded-md border p-3 dark:bg-slate-950" placeholder="Optional details" value={form.description} onChange={(e) => setForm((old) => ({ ...old, description: e.target.value }))}/><Button leftIcon={CalendarPlus} className="w-full" onClick={() => save.mutate(form)} loading={save.isPending}>Publish calendar day</Button>{recordByDate.get(form.date) && <Button variant="outline" leftIcon={Trash2} className="w-full" onClick={() => remove.mutate(recordByDate.get(form.date).id)} loading={remove.isPending}>Remove custom marker</Button>}<p className="text-xs text-slate-500">Only School Owners and Administrators can publish calendar changes.</p></CardContent></Card>}</div></div></DashboardLayout>;
}
