import React, { useMemo, useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { AlertTriangle, CheckCircle2, ClipboardCheck, History, Settings, ShieldCheck, Users, XCircle } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import DashboardLayout from '../../layouts/DashboardLayout';
import { Button } from '../../components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '../../components/ui/card';
import { attendanceService } from '../../services/managementService';
import { authService } from '../../services/authService';

const localDate = () => { const now = new Date(); return new Date(now.getTime() - now.getTimezoneOffset() * 60000).toISOString().slice(0, 10); };
const badge = { NOT_STARTED: 'bg-slate-100 text-slate-700', DRAFT: 'bg-amber-100 text-amber-800', LOCKED: 'bg-emerald-100 text-emerald-800', CORRECTED: 'bg-violet-100 text-violet-800', NOT_APPLICABLE: 'bg-sky-100 text-sky-800', CANCELLED: 'bg-rose-100 text-rose-800' };

export default function AttendanceDashboardPage() {
  const user = authService.getCurrentUser(); const navigate = useNavigate(); const [date, setDate] = useState(localDate()); const [filter, setFilter] = useState('');
  const query = useQuery({ queryKey: ['attendance-overview', date], queryFn: () => attendanceService.attendanceOverview(date), refetchInterval: 60000 });
  const data = query.data?.data; const sections = useMemo(() => (data?.sections || []).filter((row) => !filter || (filter === 'PENDING' ? ['NOT_STARTED', 'DRAFT'].includes(row.attendanceStatus) : row.attendanceStatus === filter)), [data?.sections, filter]);
  const cards = data ? [
    [Users, 'Total sections', data.summary.totalSections, ''], [CheckCircle2, 'Submitted', data.summary.submitted, 'LOCKED'],
    [AlertTriangle, 'Pending', data.summary.pending, 'PENDING'], [ShieldCheck, 'Marked by Admin', data.summary.markedByAdmin, ''],
    [History, 'Corrected', data.summary.corrected, 'CORRECTED'], [XCircle, 'Not applicable', data.summary.notApplicable, 'NOT_APPLICABLE'],
  ] : [];
  return <DashboardLayout role={user?.role}><div className="space-y-5">
    <header className="flex flex-col gap-3 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-bold uppercase tracking-widest text-indigo-600">Attendance control centre</p><h1 className="text-3xl font-bold">Daily section oversight</h1><p className="text-sm text-slate-500">Assigned teacher, actual marker, submission state and corrections remain visible together.</p></div><div className="flex flex-wrap gap-2"><input aria-label="Attendance date" type="date" max={localDate()} value={date} onChange={(event) => setDate(event.target.value)} className="h-10 rounded-lg border bg-white px-3 dark:bg-slate-950"/>{user?.role === 'ADMIN' && <Button variant="outline" leftIcon={Settings} onClick={() => navigate('/attendance/settings')}>Rules</Button>}{user?.role === 'ADMIN' && <Button leftIcon={ClipboardCheck} onClick={() => navigate('/dashboard/admin/attendance/students')}>Mark attendance</Button>}</div></header>
    {query.isLoading ? <div className="grid grid-cols-2 gap-3 lg:grid-cols-6">{Array.from({ length: 6 }, (_, index) => <div key={index} className="h-28 animate-pulse rounded-xl bg-slate-100 dark:bg-slate-800"/>)}</div> : query.isError ? <div className="rounded-xl bg-rose-50 p-4 text-sm text-rose-700">{query.error?.response?.data?.message || 'Attendance overview could not be loaded.'}</div> : <>
      <div className="grid grid-cols-2 gap-3 lg:grid-cols-6">{cards.map(([Icon, label, value, valueFilter]) => <button type="button" key={label} onClick={() => setFilter(filter === valueFilter ? '' : valueFilter)} className={`rounded-2xl border bg-white p-4 text-left transition hover:border-indigo-400 dark:border-slate-800 dark:bg-slate-900 ${filter === valueFilter && valueFilter ? 'ring-2 ring-indigo-500' : ''}`}><Icon className="text-indigo-500" size={19}/><p className="mt-3 text-2xl font-black">{value}</p><p className="text-xs text-slate-500">{label}</p></button>)}</div>
      <Card><CardHeader><div><CardTitle>Section status</CardTitle><p className="mt-1 text-sm text-slate-500">Teacher attendance is context only; Admin intervention is always intentional.</p></div></CardHeader><CardContent className="p-0"><div className="overflow-x-auto"><table className="min-w-[950px] w-full text-sm"><thead className="bg-slate-50 text-left text-xs uppercase tracking-wide text-slate-500 dark:bg-slate-800"><tr><th className="p-3">Class</th><th className="p-3">Section</th><th className="p-3">Class Teacher</th><th className="p-3">Teacher status</th><th className="p-3">Attendance</th><th className="p-3">Marked by</th><th className="p-3">Submitted</th><th className="p-3">Action</th></tr></thead><tbody>{sections.map((row) => <tr key={row.sectionId} className="border-t dark:border-slate-800"><td className="p-3 font-semibold">{row.className}</td><td className="p-3">{row.sectionName}</td><td className="p-3">{row.assignedClassTeacher?.name || 'Assignment vacant'}</td><td className="p-3">{row.teacherStatus === 'UNAVAILABLE' ? 'Status unavailable' : row.teacherStatus.replaceAll('_', ' ')}</td><td className="p-3"><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${badge[row.attendanceStatus] || badge.NOT_STARTED}`}>{row.attendanceStatus.replaceAll('_', ' ')}{row.currentRevisionNumber > 1 ? ` · R${row.currentRevisionNumber}` : ''}</span></td><td className="p-3">{row.markedByType === 'ADMIN' ? 'School Admin override' : row.markedByType === 'CLASS_TEACHER' ? 'Class Teacher' : '—'}</td><td className="p-3 text-slate-500">{row.submittedAt ? new Date(row.submittedAt).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }) : '—'}</td><td className="p-3"><button type="button" className="font-semibold text-indigo-600 hover:underline" onClick={() => navigate(`/dashboard/admin/attendance/students?classId=${row.classId}&sectionId=${row.sectionId}&date=${date}`)}>{['LOCKED', 'CORRECTED'].includes(row.attendanceStatus) ? 'View attendance' : user?.role === 'ADMIN' ? 'Mark attendance' : 'View'}</button></td></tr>)}</tbody></table>{!sections.length && <p className="p-10 text-center text-sm text-slate-500">No sections match this filter.</p>}</div></CardContent></Card>
      <div className="grid gap-3 md:grid-cols-3">{[['Corrections', '/attendance/corrections'], ['Audit history', '/attendance/audit'], ['Attendance settings', '/attendance/settings']].filter(([, path]) => user?.role === 'ADMIN' || path !== '/attendance/settings').map(([label, path]) => <button key={label} onClick={() => navigate(path)} className="rounded-xl border bg-white p-4 text-left font-semibold transition hover:border-indigo-400 hover:text-indigo-600 dark:border-slate-800 dark:bg-slate-900">{label}</button>)}</div>
    </>}
  </div></DashboardLayout>;
}
