import React, { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Check, X } from 'lucide-react';
import toast from 'react-hot-toast';
import DashboardLayout from '../../layouts/DashboardLayout';
import { Button } from '../../components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '../../components/ui/card';
import { attendanceService } from '../../services/managementService';
import { authService } from '../../services/authService';
export default function AttendanceCorrectionsPage(){const user=authService.getCurrentUser(),client=useQueryClient(),[status,setStatus]=useState('PENDING'),query=useQuery({queryKey:['attendance-corrections',status],queryFn:()=>attendanceService.corrections({status})}),mutation=useMutation({mutationFn:({id,...payload})=>attendanceService.reviewCorrection(id,payload),onSuccess:r=>{toast.success(r.message);client.invalidateQueries({queryKey:['attendance-corrections']})},onError:e=>toast.error(e.response?.data?.message||'Review failed')});const review=(row,decision)=>{const remark=window.prompt(`${decision==='APPROVED'?'Approval':'Rejection'} remark:`);if(remark===null)return;mutation.mutate({id:row.id,decision,reviewRemark:remark})};return <DashboardLayout role={user?.role}><div className="space-y-5"><header><p className="text-xs font-bold uppercase tracking-widest text-indigo-600">Attendance / Corrections</p><h1 className="text-2xl font-bold">Correction requests</h1><p className="text-sm text-slate-500">Review changes without rewriting locked history.</p></header><Card><CardHeader><CardTitle className="flex items-center justify-between">Requests<select className="h-9 rounded-lg border bg-white px-3 text-sm dark:bg-slate-950" value={status} onChange={e=>setStatus(e.target.value)}>{['PENDING','APPROVED','REJECTED'].map(item=><option key={item}>{item}</option>)}</select></CardTitle></CardHeader><CardContent>{query.isLoading?<div className="h-40 animate-pulse rounded-xl bg-slate-100 dark:bg-slate-800"/>:(query.data?.data||[]).length?<div className="space-y-3">{query.data.data.map(row=><div key={row.id} className="grid gap-3 rounded-xl border p-4 dark:border-slate-800 lg:grid-cols-[1fr_1fr_2fr_auto] lg:items-center"><div><p className="font-semibold">{row.personType}</p><p className="text-xs text-slate-500">{row.personId}</p></div><div><p className="text-sm"><span className="line-through text-slate-400">{row.existingStatus}</span> → <strong>{row.requestedStatus}</strong></p><p className="text-xs text-slate-500">{new Date(row.attendanceDate).toLocaleDateString()}</p></div><div><p className="text-sm">{row.reason}</p>{row.reviewRemark&&<p className="text-xs text-slate-500">Review: {row.reviewRemark}</p>}</div>{row.status==='PENDING'?<div className="flex gap-2"><Button variant="outline" leftIcon={X} onClick={()=>review(row,'REJECTED')}>Reject</Button><Button leftIcon={Check} onClick={()=>review(row,'APPROVED')}>Approve</Button></div>:<span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-bold dark:bg-slate-800">{row.status}</span>}</div>)}</div>:<p className="py-12 text-center text-sm text-slate-500">No {status.toLowerCase()} correction requests.</p>}</CardContent></Card></div></DashboardLayout>}
