import React, { useMemo, useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { Download, Printer, Search } from 'lucide-react';
import { useNavigate, useParams } from 'react-router-dom';
import toast from 'react-hot-toast';
import DashboardLayout from '../../layouts/DashboardLayout';
import { Button } from '../../components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '../../components/ui/card';
import { attendanceService } from '../../services/managementService';
import { authService } from '../../services/authService';

export default function EmployeeMonthlyAttendancePage(){
  const user=authService.getCurrentUser(),navigate=useNavigate(),{month}=useParams(),[search,setSearch]=useState(''),[department,setDepartment]=useState(''),[threshold,setThreshold]=useState(false);
  const query=useQuery({queryKey:['employee-month-attendance',month,department],queryFn:()=>attendanceService.employeeMonth(month,{department:department||undefined})});const data=query.data?.data;
  const departments=useMemo(()=>[...new Set((data?.rows||[]).map(row=>row.department))].sort(),[data]);const rows=useMemo(()=>(data?.rows||[]).filter(row=>(!search||`${row.name} ${row.employeeId} ${row.role}`.toLowerCase().includes(search.toLowerCase()))&&(!threshold||row.warning)),[data,search,threshold]);
  const exportCsv=async()=>{try{const blob=await attendanceService.exportCsv('employees',month),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`employee-attendance-${month}.csv`;a.click();URL.revokeObjectURL(url)}catch{toast.error('Export could not be generated')}};
  return <DashboardLayout role={user?.role}><div className="space-y-5"><header className="flex flex-col gap-3 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-bold uppercase tracking-widest text-indigo-600">Attendance / Employees / Monthly report</p><h1 className="text-2xl font-bold">Teacher and staff attendance</h1><p className="text-sm text-slate-500">Payroll-ready attendance summary for {month}.</p></div><div className="flex gap-2"><input aria-label="Employee attendance month" type="month" value={month} onChange={e=>navigate(`/attendance/employees/month/${e.target.value}`)} className="h-10 rounded-lg border bg-white px-3 text-sm dark:bg-slate-950"/><Button variant="outline" leftIcon={Printer} onClick={()=>window.print()}>Print</Button><Button leftIcon={Download} onClick={exportCsv}>Export CSV</Button></div></header>
  {data&&<div className="grid grid-cols-2 gap-3 md:grid-cols-5">{[['Employees',data.summary.totalEmployees],['Average',`${data.summary.averagePercentage??'—'}%`],['Absent days',data.summary.totalAbsent],['Payroll deduction',data.summary.payrollDeductionDays],['Below threshold',data.summary.belowThreshold]].map(([label,value])=><div key={label} className="rounded-xl border bg-white p-4 dark:border-slate-800 dark:bg-slate-900"><p className="text-xl font-black">{value}</p><p className="text-xs text-slate-500">{label}</p></div>)}</div>}
  <Card><CardHeader><CardTitle>Monthly employee register</CardTitle></CardHeader><CardContent className="space-y-4"><div className="grid gap-2 md:grid-cols-[1fr_220px_auto]"><label className="relative"><Search size={17} className="absolute left-3 top-3 text-slate-400"/><input className="h-10 w-full rounded-lg border bg-white pl-9 pr-3 text-sm dark:bg-slate-950" placeholder="Search employee, ID or role" value={search} onChange={e=>setSearch(e.target.value)}/></label><select className="h-10 rounded-lg border bg-white px-3 text-sm dark:bg-slate-950" value={department} onChange={e=>setDepartment(e.target.value)}><option value="">All departments</option>{departments.map(item=><option key={item}>{item}</option>)}</select><label className="flex items-center gap-2 rounded-lg border px-3 text-sm"><input type="checkbox" checked={threshold} onChange={e=>setThreshold(e.target.checked)}/> Below threshold only</label></div>
  {query.isLoading?<div className="h-64 animate-pulse rounded-xl bg-slate-100 dark:bg-slate-800"/>:query.isError?<p className="rounded-xl bg-rose-50 p-4 text-sm text-rose-700">{query.error?.response?.data?.message||'Report could not be loaded.'}</p>:<div className="overflow-auto rounded-xl border dark:border-slate-800"><table className="min-w-[1250px] w-full text-xs"><thead className="sticky top-0 bg-slate-100 dark:bg-slate-800"><tr>{['Employee','Role / department','Working','Present units','Absent','Paid leave','Unpaid leave','Half-days','Late','Early exits','Official duty','Attendance','Leave balance','Salary impact','Status'].map(item=><th key={item} className="px-3 py-2 text-left">{item}</th>)}</tr></thead><tbody>{rows.map(row=><tr key={row.id} className="border-t dark:border-slate-800"><td className="px-3 py-3"><p className="font-semibold text-sm">{row.name}</p><p className="text-slate-500">{row.employeeId}</p></td><td className="px-3 py-3"><p>{row.role}</p><p className="text-slate-500">{row.department}</p></td><td className="px-3 py-3">{row.summary.eligibleWorkingDays}</td><td className="px-3 py-3">{row.summary.attendanceUnits}</td><td className="px-3 py-3 text-rose-700">{row.summary.counts.ABSENT||0}</td><td className="px-3 py-3">{row.paidLeave}</td><td className="px-3 py-3">{row.unpaidLeave}</td><td className="px-3 py-3">{row.summary.counts.HALF_DAY||0}</td><td className="px-3 py-3">{row.late}</td><td className="px-3 py-3">{row.earlyExit}</td><td className="px-3 py-3">{row.officialDuty}</td><td className="px-3 py-3 font-bold">{row.summary.percentage??'—'}%</td><td className="px-3 py-3">{row.leaveBalance??'—'}</td><td className="px-3 py-3">{row.salaryImpactDays}</td><td className="px-3 py-3"><span className={`rounded-full px-2 py-1 font-semibold ${row.warning?'bg-amber-100 text-amber-800':'bg-emerald-100 text-emerald-700'}`}>{row.warning?'Review':'On track'}</span></td></tr>)}</tbody></table></div>}</CardContent></Card></div></DashboardLayout>
}
