import React, { useEffect, useMemo, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Check, ChevronRight, Copy, Printer, Save, Search, Send, Users } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import toast from 'react-hot-toast';
import DashboardLayout from '../../layouts/DashboardLayout';
import { Button } from '../../components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '../../components/ui/card';
import { attendanceService } from '../../services/managementService';
import { teacherDashboardService } from '../../services/teacherDashboardService';
import { authService } from '../../services/authService';
import { useAcademicStructure } from '../../hooks/useAcademicStructure';

const localDate = (date = new Date()) => new Date(date.getTime() - date.getTimezoneOffset() * 60000).toISOString().slice(0, 10);
const label = (value) => value?.replace(/_/g, ' ').toLowerCase().replace(/^./, (char) => char.toUpperCase());

export default function StudentAttendancePage() {
  const user = authService.getCurrentUser(); const isAdmin = ['ADMIN', 'SCHOOL_OWNER'].includes(user?.role); const navigate = useNavigate(); const queryClient = useQueryClient(); const structure = useAcademicStructure();
  const [classId, setClassId] = useState(''); const [sectionId, setSectionId] = useState(''); const [date, setDate] = useState(localDate());
  const [records, setRecords] = useState({}); const [selected, setSelected] = useState(new Set()); const [search, setSearch] = useState(''); const [statusFilter, setStatusFilter] = useState(''); const [dirty, setDirty] = useState(false);
  const metadata = useQuery({ queryKey: ['attendance-metadata'], queryFn: attendanceService.metadata });
  const assignments = useQuery({ queryKey: ['teacher-class-attendance-sections'], queryFn: teacherDashboardService.getAssignments, enabled: user?.role === 'TEACHER' });
  const teacherSections = useMemo(() => (assignments.data || []).flatMap((group) => group.sections.filter((section) => section.subjects.some((subject) => ['CLASS_TEACHER', 'BOTH'].includes(subject.roleType))).map((section) => ({ classId: group.classId, className: group.className, sectionId: section.sectionId, sectionName: section.sectionName }))), [assignments.data]);
  useEffect(() => { if (!isAdmin && teacherSections[0] && !sectionId) { setClassId(teacherSections[0].classId); setSectionId(teacherSections[0].sectionId); } }, [isAdmin, sectionId, teacherSections]);
  useEffect(() => { const warn = (event) => { if (dirty) { event.preventDefault(); event.returnValue = ''; } }; window.addEventListener('beforeunload', warn); return () => window.removeEventListener('beforeunload', warn); }, [dirty]);
  const rosterQuery = useQuery({ queryKey: ['student-attendance-roster', classId, sectionId, date], queryFn: () => attendanceService.studentRoster({ classId, sectionId, date }), enabled: Boolean(classId && sectionId && date) });
  useEffect(() => { const next = {}; (rosterQuery.data?.data?.students || []).forEach((student) => { next[student.id] = { status: student.status || 'NOT_MARKED', remarks: student.remarks || '' }; }); setRecords(next); setSelected(new Set()); setDirty(false); }, [rosterQuery.data]);
  const statuses = metadata.data?.data?.studentStatuses || []; const students = rosterQuery.data?.data?.students || []; const canMark = Boolean(rosterQuery.data?.data?.canMark);
  const visible = useMemo(() => students.filter((student) => { const needle = search.toLowerCase(); const matches = !needle || `${student.name} ${student.rollNumber || ''} ${student.admissionNo || ''}`.toLowerCase().includes(needle); return matches && (!statusFilter || records[student.id]?.status === statusFilter); }), [students, records, search, statusFilter]);
  const counts = useMemo(() => students.reduce((acc, student) => { const status = records[student.id]?.status || 'NOT_MARKED'; acc[status] = (acc[status] || 0) + 1; return acc; }, {}), [students, records]);
  const saveMutation = useMutation({ mutationFn: attendanceService.saveStudentAttendance, onSuccess: (response) => { toast.success(response.message); setDirty(false); queryClient.invalidateQueries({ queryKey: ['student-attendance-roster', classId, sectionId, date] }); }, onError: (error) => toast.error(error.response?.data?.message || 'Attendance could not be saved') });
  const setRows = (ids, status) => { const defaultRemark = ['ABSENT', 'UNAPPROVED_LEAVE'].includes(status) ? 'Marked by teacher' : ''; setRecords((old) => Object.fromEntries(Object.entries(old).map(([id, row]) => [id, ids.includes(id) ? { ...row, status, remarks: row.remarks || defaultRemark } : row]))); setDirty(true); };
  const save = (state) => { const unmarked = students.filter((student) => records[student.id]?.status === 'NOT_MARKED'); if (state === 'SUBMITTED' && unmarked.length) return toast.error(`${unmarked.length} student(s) are still not marked`); saveMutation.mutate({ classId, sectionId, date, state, records: students.map((student) => ({ studentId: student.id, ...records[student.id] })) }); };
  const copyPrevious = async () => { const previous = new Date(`${date}T12:00:00`); do previous.setDate(previous.getDate() - 1); while (previous.getDay() === 0); try { const response = await attendanceService.studentRoster({ classId, sectionId, date: localDate(previous) }); const prior = new Map((response.data?.students || []).map((row) => [row.id, row])); setRecords(Object.fromEntries(students.map((student) => [student.id, { status: prior.get(student.id)?.status || 'NOT_MARKED', remarks: prior.get(student.id)?.remarks || '' }]))); setDirty(true); toast.success('Previous working day copied'); } catch { toast.error('Previous working day could not be loaded'); } };
  const sections = structure.getSections(classId);
  return <DashboardLayout role={user?.role || 'TEACHER'}><div className="space-y-5 print:p-0">
    <header className="flex flex-col gap-3 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-bold uppercase tracking-widest text-indigo-600">Attendance / Daily register</p><h1 className="text-2xl font-bold text-slate-950 dark:text-white">Student attendance</h1><p className="text-sm text-slate-500">Mark exceptions quickly, save a draft, and submit when the register is complete.</p></div><div className="flex flex-wrap gap-2"><Button variant="outline" leftIcon={Printer} onClick={() => window.print()}>Print</Button>{classId && sectionId && <Button variant="outline" rightIcon={ChevronRight} onClick={() => navigate(`/attendance/students/class/${classId}/section/${sectionId}/month/${date.slice(0, 7)}`)}>Monthly report</Button>}</div></header>
    <Card><CardContent className="pt-6"><div className="grid gap-3 md:grid-cols-4">
      {isAdmin ? <><label className="text-xs font-semibold text-slate-500">Class<select className="mt-1 h-10 w-full rounded-lg border bg-white px-3 text-sm dark:bg-slate-950" value={classId} onChange={(e) => { setClassId(e.target.value); setSectionId(''); }}>{<option value="">Select class</option>}{structure.classes.map((item) => <option key={item.id} value={item.id}>{item.className}</option>)}</select></label><label className="text-xs font-semibold text-slate-500">Section<select className="mt-1 h-10 w-full rounded-lg border bg-white px-3 text-sm dark:bg-slate-950" value={sectionId} onChange={(e) => setSectionId(e.target.value)}><option value="">Select section</option>{sections.map((item) => <option key={item.id} value={item.id}>{item.sectionName}</option>)}</select></label></> : <label className="text-xs font-semibold text-slate-500 md:col-span-2">Assigned section<select className="mt-1 h-10 w-full rounded-lg border bg-white px-3 text-sm dark:bg-slate-950" value={sectionId} onChange={(e) => { const item = teacherSections.find((row) => row.sectionId === e.target.value); setClassId(item?.classId || ''); setSectionId(e.target.value); }}><option value="">Select section</option>{teacherSections.map((item) => <option key={item.sectionId} value={item.sectionId}>{item.className} · {item.sectionName}</option>)}</select></label>}
      <label className="text-xs font-semibold text-slate-500">Attendance date<input type="date" className="mt-1 h-10 w-full rounded-lg border bg-white px-3 text-sm dark:bg-slate-950" value={date} onChange={(e) => setDate(e.target.value)} /></label><div className="rounded-xl bg-slate-50 px-4 py-2 dark:bg-slate-800"><p className="text-xs text-slate-500">Register state</p><p className="font-bold">{students.some((student) => student.attendanceId) ? 'Saved' : 'Not started'}</p><p className="text-xs text-slate-500">{new Date(`${date}T12:00:00`).toLocaleDateString(undefined, { weekday: 'long' })}</p></div>
    </div></CardContent></Card>
    {students.length > 0 && <div className="grid grid-cols-2 gap-2 sm:grid-cols-4 lg:grid-cols-6">{statuses.slice(0, 6).map((status) => <div key={status.code} className="rounded-xl border bg-white p-3 dark:border-slate-800 dark:bg-slate-900"><p className="text-xl font-black">{counts[status.code] || 0}</p><p className="text-xs text-slate-500">{status.displayName}</p></div>)}</div>}
    <Card><CardHeader><CardTitle className="flex items-center gap-2"><Users size={18}/> Student roster</CardTitle></CardHeader><CardContent className="space-y-4">
      {students.length > 0 && <><div className="flex flex-wrap gap-2 rounded-xl bg-slate-50 p-3 dark:bg-slate-800/60"><Button variant="outline" leftIcon={Check} onClick={() => setRows(students.map((s) => s.id), 'PRESENT')} disabled={!canMark}>Mark all present</Button><Button variant="outline" onClick={() => setRows([...selected], 'ABSENT')} disabled={!canMark || !selected.size}>Selected absent</Button><Button variant="outline" onClick={() => setRows([...selected], 'APPROVED_LEAVE')} disabled={!canMark || !selected.size}>Selected leave</Button><Button variant="outline" leftIcon={Copy} onClick={copyPrevious} disabled={!canMark}>Copy previous day</Button><Button variant="outline" onClick={() => { setRecords(Object.fromEntries(students.map((s) => [s.id, { status: 'NOT_MARKED', remarks: '' }]))); setDirty(true); }} disabled={!canMark}>Reset</Button></div>
      <div className="flex flex-col gap-2 sm:flex-row"><label className="relative flex-1"><Search className="absolute left-3 top-2.5 text-slate-400" size={17}/><input className="h-10 w-full rounded-lg border bg-white pl-9 pr-3 text-sm dark:bg-slate-950" placeholder="Search name, roll or admission number" value={search} onChange={(e) => setSearch(e.target.value)} /></label><select className="h-10 rounded-lg border bg-white px-3 text-sm dark:bg-slate-950" value={statusFilter} onChange={(e) => setStatusFilter(e.target.value)}><option value="">All statuses</option>{statuses.map((status) => <option key={status.code} value={status.code}>{status.displayName}</option>)}</select></div><p className="text-xs text-slate-500">Absence and unapproved leave require a remark; quick actions add a default that you can edit.</p></>}
      {!sectionId ? <p className="py-12 text-center text-sm text-slate-500">Choose a class and section to begin.</p> : rosterQuery.isLoading ? <div className="space-y-2">{Array.from({ length: 8 }, (_, i) => <div key={i} className="h-12 animate-pulse rounded-lg bg-slate-100 dark:bg-slate-800" />)}</div> : students.length === 0 ? <p className="py-12 text-center text-sm text-slate-500">No active students are enrolled in this section.</p> : <div className="max-h-[62vh] overflow-auto rounded-xl border dark:border-slate-800"><table className="min-w-[850px] w-full text-sm"><thead className="sticky top-0 z-20 bg-slate-100 dark:bg-slate-800"><tr><th className="sticky left-0 z-30 w-10 bg-inherit p-3"><input aria-label="Select all students" type="checkbox" checked={selected.size === students.length} onChange={(e) => setSelected(e.target.checked ? new Set(students.map((s) => s.id)) : new Set())}/></th><th className="sticky left-10 z-30 bg-inherit p-3 text-left">Student</th><th className="p-3 text-left">Status</th><th className="p-3 text-left">Remark</th><th className="p-3 text-left">Save state</th></tr></thead><tbody>{visible.map((student) => <tr key={student.id} className="border-t dark:border-slate-800"><td className="sticky left-0 bg-white p-3 dark:bg-slate-900"><input aria-label={`Select ${student.name}`} type="checkbox" checked={selected.has(student.id)} onChange={() => setSelected((old) => { const next = new Set(old); next.has(student.id) ? next.delete(student.id) : next.add(student.id); return next; })}/></td><td className="sticky left-10 min-w-56 bg-white p-3 dark:bg-slate-900"><p className="font-semibold">{student.name}</p><p className="text-xs text-slate-500">Roll {student.rollNumber || '—'} · {student.admissionNo || 'No admission number'}</p></td><td className="p-3"><div className="flex flex-wrap gap-1">{statuses.filter((s) => !s.excludedFromWork).slice(0, 6).map((status) => <button type="button" key={status.code} disabled={!canMark} onClick={() => { setRecords((old) => ({ ...old, [student.id]: { ...old[student.id], status: status.code } })); setDirty(true); }} className={`rounded-full border px-2.5 py-1 text-xs font-semibold ${records[student.id]?.status === status.code ? 'border-indigo-600 bg-indigo-600 text-white' : 'bg-white text-slate-600 dark:bg-slate-950 dark:text-slate-300'}`}>{status.shortLabel}</button>)}</div></td><td className="p-3"><input aria-label={`Remark for ${student.name}`} className="h-9 w-full min-w-48 rounded-lg border bg-white px-3 dark:bg-slate-950" value={records[student.id]?.remarks || ''} onChange={(e) => { setRecords((old) => ({ ...old, [student.id]: { ...old[student.id], remarks: e.target.value } })); setDirty(true); }} disabled={!canMark}/></td><td className="p-3 text-xs font-semibold text-slate-500">{student.attendanceId && !dirty ? 'Saved' : dirty ? 'Unsaved' : 'New'}</td></tr>)}</tbody></table></div>}
      {students.length > 0 && canMark && <div className="sticky bottom-3 flex justify-end gap-2 rounded-xl border bg-white/95 p-3 shadow-lg backdrop-blur dark:border-slate-700 dark:bg-slate-900/95"><Button variant="outline" leftIcon={Save} onClick={() => save('DRAFT')} loading={saveMutation.isPending}>Save draft</Button><Button leftIcon={Send} onClick={() => save('SUBMITTED')} loading={saveMutation.isPending}>Submit attendance</Button></div>}
    </CardContent></Card>
  </div></DashboardLayout>;
}
