import React, { useMemo, useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { AlertCircle, CalendarDays, Download, TrendingUp } from 'lucide-react';
import { useParams, useSearchParams } from 'react-router-dom';
import DashboardLayout from '../../layouts/DashboardLayout';
import { Card, CardContent, CardHeader, CardTitle } from '../../components/ui/card';
import AttendanceCalendar from '../../components/attendance/AttendanceCalendar';
import { attendanceService } from '../../services/managementService';
import { authService } from '../../services/authService';

const currentMonth = () => new Date().toISOString().slice(0, 7);
export default function StudentAttendanceProfilePage() {
  const user = authService.getCurrentUser(); const { studentId } = useParams(); const [params] = useSearchParams(); const [month, setMonth] = useState(currentMonth());
  const query = useQuery({ queryKey: ['attendance-student-profile', studentId, params.get('session')], queryFn: () => attendanceService.studentProfile(studentId, { academicSession: params.get('session') || undefined }) }); const data = query.data?.data;
  const calendar = useMemo(() => { const [year, value] = month.split('-').map(Number); return Array.from({ length: new Date(Date.UTC(year, value, 0)).getUTCDate() }, (_, index) => { const date = `${month}-${String(index + 1).padStart(2, '0')}`; return { date, dayType: new Date(`${date}T00:00:00Z`).getUTCDay() === 0 ? 'WEEKLY_OFF' : 'WORKING_DAY' }; }); }, [month]);
  const monthRows = data?.monthlyHistory || []; const max = Math.max(100, ...monthRows.map((row) => row.percentage || 0));
  return <DashboardLayout role={user?.role}><div className="space-y-5"><header><p className="text-xs font-bold uppercase tracking-widest text-indigo-600">Attendance / Student profile</p><h1 className="text-2xl font-bold">{data?.student.name || 'Student attendance'}</h1><p className="text-sm text-slate-500">{data ? `${data.student.className} · ${data.student.section} · ${data.academicSession}` : 'Loading attendance history…'}</p></header>
    {query.isError && <div className="rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-700">{query.error?.response?.data?.message || 'Attendance profile could not be loaded.'}</div>}
    {data && <><div className="grid grid-cols-2 gap-3 md:grid-cols-4 lg:grid-cols-7">{[['Cumulative', data.overview.percentage === null ? '—' : `${data.overview.percentage}%`], ['Working days', data.overview.workingDays], ['Present units', data.overview.attendanceUnits], ['Absent', data.overview.counts.ABSENT || 0], ['Approved leave', (data.overview.counts.APPROVED_LEAVE || 0) + (data.overview.counts.LEAVE || 0)], ['Late', data.overview.counts.LATE || 0], ['Half-days', data.overview.counts.HALF_DAY || 0]].map(([label, value]) => <div key={label} className="rounded-xl border bg-white p-4 dark:border-slate-800 dark:bg-slate-900"><p className="text-xl font-black">{value}</p><p className="text-xs text-slate-500">{label}</p></div>)}</div>
      {data.alerts.belowThreshold && <div className="flex items-start gap-3 rounded-xl border border-amber-200 bg-amber-50 p-4 text-amber-900"><AlertCircle className="mt-0.5" size={18}/><div><p className="font-semibold">Attendance support may be helpful</p><p className="text-sm">The cumulative percentage is below the school’s configured minimum. Review recent absences and contact the school if a record needs correction.</p></div></div>}
      <div className="grid gap-5 xl:grid-cols-[1.35fr_.65fr]"><Card><CardHeader><CardTitle className="flex items-center justify-between gap-3"><span className="flex items-center gap-2"><CalendarDays size={18}/> Monthly calendar</span><input aria-label="Calendar month" type="month" className="h-9 rounded-lg border bg-white px-3 text-sm dark:bg-slate-950" value={month} onChange={(e) => setMonth(e.target.value)}/></CardTitle></CardHeader><CardContent><AttendanceCalendar month={month} days={calendar} personalRecords={data.records.filter((record) => record.date.startsWith(month))}/></CardContent></Card>
      <Card><CardHeader><CardTitle className="flex items-center gap-2"><TrendingUp size={18}/> Monthly trend</CardTitle></CardHeader><CardContent className="space-y-4">{monthRows.length ? monthRows.map((row) => <div key={row.month}><div className="mb-1 flex justify-between text-sm"><span>{new Date(`${row.month}-01T12:00:00`).toLocaleDateString(undefined, { month: 'short', year: 'numeric' })}</span><span className="font-bold">{row.percentage ?? '—'}%</span></div><div className="h-2 overflow-hidden rounded-full bg-slate-100 dark:bg-slate-800"><div className="h-full rounded-full bg-indigo-600" style={{ width: `${((row.percentage || 0) / max) * 100}%` }}/></div><p className="mt-1 text-xs text-slate-500">{row.present} present units · {row.absent} absent · {row.leave} leave</p></div>) : <p className="text-sm text-slate-500">No attendance has been recorded in this session.</p>}</CardContent></Card></div>
      <Card><CardHeader><CardTitle className="flex items-center gap-2"><Download size={18}/> Monthly history</CardTitle></CardHeader><CardContent><div className="overflow-auto"><table className="w-full min-w-[600px] text-sm"><thead className="bg-slate-100 dark:bg-slate-800"><tr>{['Month','Working days','Present units','Absent','Leave','Percentage','Status'].map((item) => <th key={item} className="px-3 py-2 text-left">{item}</th>)}</tr></thead><tbody>{monthRows.map((row) => <tr key={row.month} className="border-t dark:border-slate-800"><td className="px-3 py-2 font-semibold">{row.month}</td><td className="px-3 py-2">{row.workingDays}</td><td className="px-3 py-2">{row.present}</td><td className="px-3 py-2">{row.absent}</td><td className="px-3 py-2">{row.leave}</td><td className="px-3 py-2 font-bold">{row.percentage ?? '—'}%</td><td className="px-3 py-2">{row.percentage === null ? 'Not calculated' : row.percentage >= 75 ? 'On track' : 'Needs support'}</td></tr>)}</tbody></table></div></CardContent></Card>
    </>}
  </div></DashboardLayout>;
}
