import React, { useEffect, useMemo, useState } from 'react';
import PropTypes from 'prop-types';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { AlertCircle, CalendarCheck, Check, ChevronRight, Copy, Printer, Save, Search, Send, UserCheck, UserX, Users } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import toast from 'react-hot-toast';
import DashboardLayout from '../../layouts/DashboardLayout';
import { Button } from '../../components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '../../components/ui/card';
import { attendanceService } from '../../services/managementService';
import { teacherDashboardService } from '../../services/teacherDashboardService';
import { authService } from '../../services/authService';
import { useAcademicStructure } from '../../hooks/useAcademicStructure';

const localDate = (date = new Date()) => new Date(date.getTime() - date.getTimezoneOffset() * 60000).toISOString().slice(0, 10);
const summaryTone = {
  slate: 'border-slate-200 bg-white text-slate-700 dark:border-slate-800 dark:bg-slate-900 dark:text-slate-200',
  emerald: 'border-emerald-200 bg-emerald-50 text-emerald-700 dark:border-emerald-900 dark:bg-emerald-950/50 dark:text-emerald-300',
  rose: 'border-rose-200 bg-rose-50 text-rose-700 dark:border-rose-900 dark:bg-rose-950/50 dark:text-rose-300',
  amber: 'border-amber-200 bg-amber-50 text-amber-700 dark:border-amber-900 dark:bg-amber-950/50 dark:text-amber-300',
};

function SummaryCard({ icon: Icon, label, value, helper, tone = 'slate', onClick, active }) {
  const Component = onClick ? 'button' : 'div';
  return <Component type={onClick ? 'button' : undefined} onClick={onClick} className={`rounded-2xl border p-4 text-left transition ${summaryTone[tone]} ${onClick ? 'hover:-translate-y-0.5 hover:shadow-sm' : ''} ${active ? 'ring-2 ring-indigo-500 ring-offset-2 dark:ring-offset-slate-950' : ''}`}><div className="flex items-center justify-between gap-2"><p className="text-xs font-bold uppercase tracking-wide opacity-80">{label}</p><Icon size={18}/></div><p className="mt-3 text-2xl font-black">{value}</p><p className="mt-1 text-xs opacity-75">{helper}</p></Component>;
}
SummaryCard.propTypes = { icon: PropTypes.elementType.isRequired, label: PropTypes.string.isRequired, value: PropTypes.node.isRequired, helper: PropTypes.node.isRequired, tone: PropTypes.oneOf(Object.keys(summaryTone)), onClick: PropTypes.func, active: PropTypes.bool };

export default function StudentAttendancePage() {
  const user = authService.getCurrentUser(); const isAdmin = user?.role === 'ADMIN'; const navigate = useNavigate(); const queryClient = useQueryClient(); const structure = useAcademicStructure({ enabled: isAdmin, retry: false }); const initial = new URLSearchParams(window.location.search);
  const [classId, setClassId] = useState(initial.get('classId') || ''); const [sectionId, setSectionId] = useState(initial.get('sectionId') || ''); const [date, setDate] = useState(initial.get('date') || localDate());
  const [records, setRecords] = useState({}); const [selected, setSelected] = useState(new Set()); const [search, setSearch] = useState(''); const [statusFilter, setStatusFilter] = useState(''); const [dirty, setDirty] = useState(false); const [changedIds, setChangedIds] = useState(new Set()); const [overrideReason, setOverrideReason] = useState(''); const [overrideReasonCode, setOverrideReasonCode] = useState(''); const [correctionMode, setCorrectionMode] = useState(false);
  const metadata = useQuery({ queryKey: ['attendance-metadata', user?.schoolId, user?.role], queryFn: attendanceService.metadata, retry: false });
  const assignments = useQuery({ queryKey: ['teacher-class-attendance-sections', user?.schoolId], queryFn: teacherDashboardService.getAssignments, enabled: user?.role === 'TEACHER', retry: false });
  const teacherSections = useMemo(() => {
    if (user?.role === 'CLASS_TEACHER') return (user.classTeacherContext?.sections || []).map((section) => ({ classId: section.classId, className: section.className, sectionId: section.sectionId, sectionName: section.sectionName }));
    return (assignments.data || []).flatMap((group) => group.sections.filter((section) => section.subjects.some((subject) => ['CLASS_TEACHER', 'BOTH'].includes(subject.roleType))).map((section) => ({ classId: group.classId, className: group.className, sectionId: section.sectionId, sectionName: section.sectionName })));
  }, [assignments.data, user?.classTeacherContext?.sections, user?.role]);
  useEffect(() => { if (!isAdmin && teacherSections[0] && !sectionId) { setClassId(teacherSections[0].classId); setSectionId(teacherSections[0].sectionId); } }, [isAdmin, sectionId, teacherSections]);
  useEffect(() => { const warn = (event) => { if (dirty) { event.preventDefault(); event.returnValue = ''; } }; window.addEventListener('beforeunload', warn); return () => window.removeEventListener('beforeunload', warn); }, [dirty]);
  const rosterQuery = useQuery({ queryKey: ['student-attendance-roster', user?.schoolId, user?.role, classId, sectionId, date], queryFn: () => attendanceService.studentRoster({ classId, sectionId, date }), enabled: Boolean(classId && sectionId && date), retry: false });
  useEffect(() => { const next = {}; (rosterQuery.data?.data?.students || []).forEach((student) => { next[student.id] = { status: student.status || 'NOT_MARKED', remarks: student.remarks || '' }; }); setRecords(next); setSelected(new Set()); setChangedIds(new Set()); setOverrideReason(''); setOverrideReasonCode(''); setCorrectionMode(false); setDirty(false); }, [rosterQuery.data]);
  const statuses = metadata.data?.data?.studentStatuses || []; const students = rosterQuery.data?.data?.students || []; const register = rosterQuery.data?.data?.register; const locked = Boolean(register?.isLocked || ['LOCKED', 'CORRECTED'].includes(register?.state)); const canMark = Boolean(rosterQuery.data?.data?.canMark || (isAdmin && locked && correctionMode));
  const historyQuery = useQuery({ queryKey: ['attendance-history', register?.id], queryFn: () => attendanceService.attendanceHistory(register.id), enabled: Boolean(register?.id), retry: false });
  const visible = useMemo(() => students.filter((student) => { const needle = search.toLowerCase(); const matches = !needle || `${student.name} ${student.rollNumber || ''} ${student.admissionNo || ''}`.toLowerCase().includes(needle); return matches && (!statusFilter || records[student.id]?.status === statusFilter); }), [students, records, search, statusFilter]);
  const counts = useMemo(() => students.reduce((acc, student) => { const status = records[student.id]?.status || 'NOT_MARKED'; acc[status] = (acc[status] || 0) + 1; return acc; }, {}), [students, records]);
  const markedCount = students.length - (counts.NOT_MARKED || 0); const attendedUnits = (counts.PRESENT || 0) + (counts.LATE || 0) + (counts.OFFICIAL_DUTY || 0) + (counts.HALF_DAY || 0) * 0.5; const completion = students.length ? Math.round(markedCount / students.length * 100) : 0; const attendanceRate = markedCount ? Math.round(attendedUnits / markedCount * 1000) / 10 : 0;
  const requiresOverrideReason = isAdmin && canMark;
  const saveMutation = useMutation({ mutationFn: ({ mode, ...payload }) => mode === 'CORRECTION' ? attendanceService.correctAttendance(register.id, payload) : mode === 'DRAFT' ? attendanceService.saveAttendanceDraft(sectionId, date, payload) : attendanceService.submitAttendance(sectionId, date, payload), onSuccess: (response) => { toast.success(response.message); setChangedIds(new Set()); setCorrectionMode(false); setDirty(false); queryClient.invalidateQueries({ queryKey: ['student-attendance-roster', user?.schoolId, user?.role, classId, sectionId, date] }); queryClient.invalidateQueries({ queryKey: ['attendance-overview'] }); queryClient.invalidateQueries({ queryKey: ['attendance-history', register?.id] }); }, onError: (error) => toast.error(error.response?.data?.message || 'Attendance could not be saved') });
  const setRows = (ids, status) => { if (!ids.length) return; const defaultRemark = ['ABSENT', 'UNAPPROVED_LEAVE'].includes(status) ? 'Marked by teacher' : ''; setRecords((old) => Object.fromEntries(Object.entries(old).map(([id, row]) => [id, ids.includes(id) ? { ...row, status, remarks: row.remarks || defaultRemark } : row]))); setChangedIds((old) => new Set([...old, ...ids])); setDirty(true); };
  const updateRow = (studentId, patch) => { setRecords((old) => ({ ...old, [studentId]: { ...old[studentId], ...patch } })); setChangedIds((old) => new Set(old).add(studentId)); setDirty(true); };
  const save = (state) => { const unmarked = students.filter((student) => records[student.id]?.status === 'NOT_MARKED'); if (state === 'SUBMITTED' && unmarked.length) { setStatusFilter('NOT_MARKED'); return toast.error(`Mark attendance for the remaining ${unmarked.length} student${unmarked.length === 1 ? '' : 's'}`); } const missingRemarks = students.filter((student) => statuses.find((status) => status.code === records[student.id]?.status)?.requiresRemark && !records[student.id]?.remarks?.trim()); if (missingRemarks.length) { setSearch(missingRemarks[0].name); return toast.error(`Add a remark for ${missingRemarks[0].name}`); } if (requiresOverrideReason && (!overrideReasonCode || !overrideReason.trim())) return toast.error('Select a reason and add an explanation'); if (correctionMode) { if (!changedIds.size) return toast.error('Change at least one student record'); return saveMutation.mutate({ mode: 'CORRECTION', reasonCode: overrideReasonCode, reasonNote: overrideReason.trim(), expectedRevision: register.currentRevisionNumber, changes: [...changedIds].map((studentId) => ({ studentId, newStatus: records[studentId].status, newRemark: records[studentId].remarks })) }); } saveMutation.mutate({ mode: state === 'DRAFT' ? 'DRAFT' : 'SUBMITTED', academicSession: metadata.data?.data?.sessions?.find((item) => item.isActive)?.name, expectedRevision: register?.currentRevisionNumber, overrideReasonCode: overrideReasonCode || undefined, overrideReasonNote: overrideReason.trim() || undefined, records: students.map((student) => ({ studentId: student.id, ...records[student.id] })) }); };
  const copyPrevious = async () => { const previous = new Date(`${date}T12:00:00`); do previous.setDate(previous.getDate() - 1); while (previous.getDay() === 0); try { const response = await attendanceService.studentRoster({ classId, sectionId, date: localDate(previous) }); const prior = new Map((response.data?.students || []).map((row) => [row.id, row])); setRecords(Object.fromEntries(students.map((student) => [student.id, { status: prior.get(student.id)?.status || 'NOT_MARKED', remarks: prior.get(student.id)?.remarks || '' }]))); setChangedIds(new Set(students.map((student) => student.id))); setDirty(true); toast.success('Previous working day copied'); } catch { toast.error('Previous working day could not be loaded'); } };
  const sections = structure.getSections(classId);
  return <DashboardLayout role={user?.role || 'TEACHER'}><div className="space-y-5 print:p-0">
    <header className="flex flex-col gap-3 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-bold uppercase tracking-widest text-indigo-600">Attendance / Daily register</p><h1 className="text-2xl font-bold text-slate-950 dark:text-white">Student attendance</h1><p className="text-sm text-slate-500">Mark exceptions quickly, save a draft, and submit when the register is complete.</p></div><div className="flex flex-wrap gap-2"><Button variant="outline" leftIcon={Printer} onClick={() => window.print()}>Print</Button>{classId && sectionId && <Button variant="outline" rightIcon={ChevronRight} onClick={() => navigate(`/attendance/students/class/${classId}/section/${sectionId}/month/${date.slice(0, 7)}`)}>Monthly report</Button>}</div></header>
    {locked && <div className="flex flex-col gap-3 rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-950 sm:flex-row sm:items-center sm:justify-between dark:border-emerald-900 dark:bg-emerald-950/40 dark:text-emerald-100"><div><p className="font-bold">Attendance submitted and locked · Revision {register.currentRevisionNumber}</p><p>{register.markedByType === 'ADMIN' ? 'Marked by School Admin override. ' : 'Marked by the assigned Class Teacher. '}Class Teachers can view this record and its history but cannot edit it.</p></div>{isAdmin && !correctionMode && <Button variant="outline" onClick={() => setCorrectionMode(true)}>Correct Attendance</Button>}{correctionMode && <Button variant="outline" onClick={() => { setCorrectionMode(false); rosterQuery.refetch(); }}>Cancel correction</Button>}</div>}
    <Card><CardContent className="pt-6"><div className="grid gap-3 md:grid-cols-4">
      {isAdmin ? <><label className="text-xs font-semibold text-slate-500">Class<select className="mt-1 h-10 w-full rounded-lg border bg-white px-3 text-sm dark:bg-slate-950" value={classId} onChange={(e) => { setClassId(e.target.value); setSectionId(''); }}>{<option value="">Select class</option>}{structure.classes.map((item) => <option key={item.id} value={item.id}>{item.className}</option>)}</select></label><label className="text-xs font-semibold text-slate-500">Section<select className="mt-1 h-10 w-full rounded-lg border bg-white px-3 text-sm dark:bg-slate-950" value={sectionId} onChange={(e) => setSectionId(e.target.value)}><option value="">Select section</option>{sections.map((item) => <option key={item.id} value={item.id}>{item.sectionName}</option>)}</select></label></> : <label className="text-xs font-semibold text-slate-500 md:col-span-2">Assigned section<select className="mt-1 h-10 w-full rounded-lg border bg-white px-3 text-sm dark:bg-slate-950" value={sectionId} onChange={(e) => { const item = teacherSections.find((row) => row.sectionId === e.target.value); setClassId(item?.classId || ''); setSectionId(e.target.value); }}><option value="">Select section</option>{teacherSections.map((item) => <option key={item.sectionId} value={item.sectionId}>{item.className} · {item.sectionName}</option>)}</select></label>}
      <label className="text-xs font-semibold text-slate-500">Attendance date<input type="date" max={localDate()} className="mt-1 h-11 w-full rounded-lg border bg-white px-3 text-base sm:h-10 sm:text-sm dark:bg-slate-950" value={date} onChange={(e) => setDate(e.target.value)} /></label><div className="rounded-xl bg-slate-50 px-4 py-2 dark:bg-slate-800"><p className="text-xs text-slate-500">Register state</p><p className="font-bold">{dirty ? 'Unsaved changes' : rosterQuery.data?.data?.register?.state === 'SUBMITTED' ? 'Submitted' : rosterQuery.data?.data?.register?.state === 'DRAFT' ? 'Draft saved' : students.length ? 'Not started' : 'Waiting for selection'}</p><p className="text-xs text-slate-500">{new Date(`${date}T12:00:00`).toLocaleDateString(undefined, { weekday: 'long' })}</p></div>
    </div></CardContent></Card>
    {students.length > 0 && <><div className="grid grid-cols-2 gap-3 lg:grid-cols-4"><SummaryCard icon={Users} label="Students" value={students.length} helper={`${rosterQuery.data?.data?.class?.className || ''} · ${rosterQuery.data?.data?.section?.sectionName || ''}`}/><SummaryCard icon={CalendarCheck} label="Register complete" value={`${completion}%`} helper={`${markedCount} of ${students.length} marked`} tone={completion === 100 ? 'emerald' : 'amber'} onClick={() => setStatusFilter(counts.NOT_MARKED ? 'NOT_MARKED' : '')} active={statusFilter === 'NOT_MARKED'}/><SummaryCard icon={UserCheck} label="Attendance rate" value={markedCount ? `${attendanceRate}%` : '—'} helper="Based on marked students" tone="emerald"/><SummaryCard icon={UserX} label="Needs attention" value={(counts.ABSENT || 0) + (counts.UNAPPROVED_LEAVE || 0) + (counts.LATE || 0)} helper={`${counts.ABSENT || 0} absent · ${counts.LATE || 0} late`} tone={counts.ABSENT ? 'rose' : 'slate'} onClick={() => setStatusFilter(statusFilter === 'ABSENT' ? '' : 'ABSENT')} active={statusFilter === 'ABSENT'}/></div><div className="rounded-2xl border bg-white p-4 dark:border-slate-800 dark:bg-slate-900"><div className="flex items-center justify-between gap-3"><div><p className="text-sm font-bold">{counts.NOT_MARKED ? `${counts.NOT_MARKED} student${counts.NOT_MARKED === 1 ? '' : 's'} still to mark` : 'Register is complete'}</p><p className="text-xs text-slate-500">Present {counts.PRESENT || 0} · Absent {counts.ABSENT || 0} · Late {counts.LATE || 0} · Leave {(counts.APPROVED_LEAVE || 0) + (counts.UNAPPROVED_LEAVE || 0) + (counts.MEDICAL_LEAVE || 0)}</p></div><span className="text-sm font-black text-indigo-600">{completion}%</span></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-slate-100 dark:bg-slate-800"><div className={`h-full rounded-full transition-all ${completion === 100 ? 'bg-emerald-500' : 'bg-indigo-600'}`} style={{ width: `${completion}%` }}/></div></div></>}
    <Card><CardHeader className="flex-col items-start gap-1 sm:flex-row sm:items-center"><div><CardTitle className="flex items-center gap-2"><Users size={18}/> Student roster</CardTitle><p className="text-sm text-slate-500">Mark the remaining students present, then record only the exceptions.</p></div>{changedIds.size > 0 && <span className="rounded-full bg-amber-100 px-3 py-1 text-xs font-bold text-amber-800">{changedIds.size} unsaved change{changedIds.size === 1 ? '' : 's'}</span>}</CardHeader><CardContent className="space-y-4">
      {students.length > 0 && <><div className="grid grid-cols-2 gap-2 rounded-xl bg-slate-50 p-3 sm:flex sm:flex-wrap dark:bg-slate-800/60"><Button variant="success" leftIcon={Check} onClick={() => setRows(students.filter((student) => records[student.id]?.status === 'NOT_MARKED').map((student) => student.id), 'PRESENT')} disabled={!canMark || !counts.NOT_MARKED}>Mark remaining</Button><Button variant="outline" onClick={() => setRows([...selected], 'ABSENT')} disabled={!canMark || !selected.size}>Selected absent</Button><Button variant="outline" onClick={() => setRows([...selected], 'APPROVED_LEAVE')} disabled={!canMark || !selected.size}>Selected leave</Button><Button variant="outline" leftIcon={Copy} onClick={copyPrevious} disabled={!canMark}>Copy previous</Button></div>
      <div className="flex flex-col gap-2 sm:flex-row"><label className="relative flex-1"><Search className="absolute left-3 top-3 text-slate-400 sm:top-2.5" size={17}/><input className="h-11 w-full rounded-lg border bg-white pl-9 pr-3 text-base sm:h-10 sm:text-sm dark:bg-slate-950" placeholder="Search name, roll or admission number" value={search} onChange={(e) => setSearch(e.target.value)} /></label><select className="h-11 rounded-lg border bg-white px-3 text-base sm:h-10 sm:text-sm dark:bg-slate-950" value={statusFilter} onChange={(e) => setStatusFilter(e.target.value)}><option value="">All statuses</option>{statuses.map((status) => <option key={status.code} value={status.code}>{status.displayName}</option>)}</select></div><p className="text-xs text-slate-500">Absence and unapproved leave require a remark; quick actions add a default that you can edit.</p></>}
      {!sectionId ? <p className="py-12 text-center text-sm text-slate-500">Choose a class and section to begin.</p> : rosterQuery.isLoading ? <div className="space-y-2">{Array.from({ length: 8 }, (_, i) => <div key={i} className="h-12 animate-pulse rounded-lg bg-slate-100 dark:bg-slate-800" />)}</div> : students.length === 0 ? <p className="py-12 text-center text-sm text-slate-500">No active students are enrolled in this section.</p> : visible.length === 0 ? <p className="py-12 text-center text-sm text-slate-500">No students match the current search or status filter.</p> : <>
      <div className="grid gap-3 md:hidden">{visible.map((student) => {
        const definition = statuses.find((status) => status.code === records[student.id]?.status);
        const needsRemark = definition?.requiresRemark && !records[student.id]?.remarks?.trim();
        return <article key={student.id} className="rounded-xl border bg-white p-3 dark:border-slate-800 dark:bg-slate-900"><div className="flex items-start gap-3"><input className="mt-1 h-5 w-5 shrink-0" aria-label={`Select ${student.name}`} type="checkbox" checked={selected.has(student.id)} onChange={() => setSelected((old) => { const next = new Set(old); next.has(student.id) ? next.delete(student.id) : next.add(student.id); return next; })}/><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-2"><div className="min-w-0"><p className="truncate font-bold">{student.name}</p><p className="text-xs text-slate-500">Roll {student.rollNumber || '—'} · {student.admissionNo || 'No admission number'}</p></div><span className={`shrink-0 rounded-full px-2 py-1 text-[10px] font-bold ${records[student.id]?.status === 'NOT_MARKED' ? 'bg-slate-100 text-slate-600' : changedIds.has(student.id) ? 'bg-amber-100 text-amber-800' : 'bg-emerald-100 text-emerald-700'}`}>{records[student.id]?.status === 'NOT_MARKED' ? 'Not marked' : changedIds.has(student.id) ? 'Unsaved' : 'Saved'}</span></div><div className="mt-3 grid grid-cols-4 gap-1.5">{statuses.filter((status) => !status.excludedFromWork && status.code !== 'NOT_MARKED').slice(0, 7).map((status) => <button type="button" key={status.code} disabled={!canMark} onClick={() => updateRow(student.id, { status: status.code })} className={`min-h-10 rounded-lg border px-1 text-xs font-bold ${records[student.id]?.status === status.code ? 'border-indigo-600 bg-indigo-600 text-white' : 'bg-white text-slate-600 dark:bg-slate-950 dark:text-slate-300'}`}><span className="block">{status.shortLabel}</span><span className="sr-only">{status.displayName}</span></button>)}</div><input aria-label={`Remark for ${student.name}`} placeholder={definition?.requiresRemark ? 'Remark required' : 'Add a remark (optional)'} className={`mt-3 h-11 w-full rounded-lg border bg-white px-3 text-base dark:bg-slate-950 ${needsRemark ? 'border-amber-400' : ''}`} value={records[student.id]?.remarks || ''} onChange={(event) => updateRow(student.id, { remarks: event.target.value })} disabled={!canMark}/></div></div></article>;
      })}</div>
      <div className="hidden max-h-[62vh] overflow-auto rounded-xl border md:block dark:border-slate-800">
        <table className="min-w-[900px] w-full text-sm">
          <thead className="sticky top-0 z-20 bg-slate-100 dark:bg-slate-800"><tr><th className="sticky left-0 z-30 w-10 bg-inherit p-3"><input aria-label="Select visible students" type="checkbox" checked={visible.length > 0 && visible.every((student) => selected.has(student.id))} onChange={(event) => setSelected((old) => { const next = new Set(old); visible.forEach((student) => event.target.checked ? next.add(student.id) : next.delete(student.id)); return next; })}/></th><th className="sticky left-10 z-30 bg-inherit p-3 text-left">Student</th><th className="p-3 text-left">Today’s status</th><th className="p-3 text-left">Remark</th><th className="p-3 text-left">State</th></tr></thead>
          <tbody>{visible.map((student) => <tr key={student.id} className="border-t dark:border-slate-800">
            <td className="sticky left-0 bg-white p-3 dark:bg-slate-900"><input aria-label={`Select ${student.name}`} type="checkbox" checked={selected.has(student.id)} onChange={() => setSelected((old) => { const next = new Set(old); next.has(student.id) ? next.delete(student.id) : next.add(student.id); return next; })}/></td>
            <td className="sticky left-10 min-w-56 bg-white p-3 dark:bg-slate-900"><p className="font-semibold">{student.name}</p><p className="text-xs text-slate-500">Roll {student.rollNumber || '—'} · {student.admissionNo || 'No admission number'}</p></td>
            <td className="p-3"><div className="flex flex-wrap gap-1">{statuses.filter((status) => !status.excludedFromWork && status.code !== 'NOT_MARKED').slice(0, 7).map((status) => <button type="button" key={status.code} title={status.displayName} aria-label={`Mark ${student.name} ${status.displayName}`} disabled={!canMark} onClick={() => updateRow(student.id, { status: status.code })} className={`rounded-full border px-2.5 py-1 text-xs font-semibold ${records[student.id]?.status === status.code ? 'border-indigo-600 bg-indigo-600 text-white' : 'bg-white text-slate-600 hover:border-slate-400 dark:bg-slate-950 dark:text-slate-300'}`}>{status.shortLabel}</button>)}</div></td>
            <td className="p-3"><input aria-label={`Remark for ${student.name}`} placeholder={statuses.find((status) => status.code === records[student.id]?.status)?.requiresRemark ? 'Required for this status' : 'Optional'} className={`h-9 w-full min-w-48 rounded-lg border bg-white px-3 dark:bg-slate-950 ${statuses.find((status) => status.code === records[student.id]?.status)?.requiresRemark && !records[student.id]?.remarks?.trim() ? 'border-amber-400' : ''}`} value={records[student.id]?.remarks || ''} onChange={(event) => updateRow(student.id, { remarks: event.target.value })} disabled={!canMark}/></td>
            <td className="p-3"><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${records[student.id]?.status === 'NOT_MARKED' ? 'bg-slate-100 text-slate-600' : changedIds.has(student.id) ? 'bg-amber-100 text-amber-800' : 'bg-emerald-100 text-emerald-700'}`}>{records[student.id]?.status === 'NOT_MARKED' ? 'Not marked' : changedIds.has(student.id) ? 'Unsaved' : student.attendanceId ? 'Saved' : 'Ready'}</span></td>
          </tr>)}</tbody>
        </table>
      </div></>}
      {requiresOverrideReason && <label className="block rounded-xl border border-amber-200 bg-amber-50 p-3 text-sm text-amber-900 dark:border-amber-900 dark:bg-amber-950/40 dark:text-amber-200"><span className="font-bold">{correctionMode ? 'Correction reason' : 'Admin override reason'}</span><span className="mt-0.5 block text-xs opacity-80">The reason, Admin identity, timestamp, previous values and updated values will be retained.</span><select className="mt-2 h-10 w-full rounded-lg border border-amber-300 bg-white px-3 text-slate-900 dark:bg-slate-950 dark:text-white" value={overrideReasonCode} onChange={(event) => setOverrideReasonCode(event.target.value)}><option value="">Select reason</option>{(correctionMode ? [['INCORRECT_STATUS','Incorrect status'],['REGISTER_VERIFICATION','Physical register verification'],['LATE_ARRIVAL_VERIFIED','Late arrival verified'],['MEDICAL_EVIDENCE','Medical evidence received'],['OTHER','Other']] : [['CLASS_TEACHER_ABSENT','Class Teacher absent'],['CLASS_TEACHER_APPROVED_LEAVE','Class Teacher on approved leave'],['CLASS_TEACHER_UNAVAILABLE','Class Teacher unavailable'],['ATTENDANCE_DEADLINE_MISSED','Attendance deadline missed'],['CLASS_TEACHER_TECHNICAL_ISSUE','Technical issue'],['CLASS_TEACHER_ASSIGNMENT_VACANT','Assignment vacant'],['EMERGENCY_ADMIN_ACTION','Emergency action'],['PHYSICAL_REGISTER_ENTRY','Physical register entry'],['OTHER','Other']]).map(([code,label])=><option key={code} value={code}>{label}</option>)}</select><textarea className="mt-2 min-h-20 w-full rounded-lg border border-amber-300 bg-white p-3 text-base text-slate-900 sm:text-sm dark:bg-slate-950 dark:text-white" maxLength={500} placeholder="Explain why this action is required" value={overrideReason} onChange={(event) => setOverrideReason(event.target.value)}/></label>}
      {students.length > 0 && canMark && <div className="sticky bottom-2 z-30 flex flex-col gap-3 rounded-xl border bg-white/95 p-3 shadow-lg backdrop-blur sm:bottom-3 sm:flex-row sm:items-center sm:justify-between dark:border-slate-700 dark:bg-slate-900/95"><div className="flex items-center gap-2 text-sm">{correctionMode ? <><AlertCircle size={18} className="shrink-0 text-amber-600"/><span><strong>{changedIds.size} changed student{changedIds.size === 1 ? '' : 's'}.</strong> All changes will create a new immutable revision.</span></> : counts.NOT_MARKED ? <><AlertCircle size={18} className="shrink-0 text-amber-600"/><span><strong>{counts.NOT_MARKED} not marked.</strong> Save a draft or finish the register.</span></> : <><Check size={18} className="shrink-0 text-emerald-600"/><span><strong>All {students.length} students marked.</strong> Ready to submit.</span></>}</div><div className="grid grid-cols-2 gap-2 sm:flex sm:justify-end">{!correctionMode && <Button variant="outline" leftIcon={Save} onClick={() => save('DRAFT')} loading={saveMutation.isPending}>Save draft</Button>}<Button variant="primary" leftIcon={Send} onClick={() => save('SUBMITTED')} loading={saveMutation.isPending} disabled={correctionMode ? !changedIds.size : Boolean(counts.NOT_MARKED)}>{correctionMode ? 'Confirm correction' : 'Submit'}</Button></div></div>}
    </CardContent></Card>
    {register?.id && <Card><CardHeader><CardTitle>History and activity</CardTitle></CardHeader><CardContent>{historyQuery.isLoading ? <p className="text-sm text-slate-500">Loading history…</p> : historyQuery.data?.data?.revisions?.length ? <div className="space-y-4">{historyQuery.data.data.revisions.map((revision) => <div key={revision.id} className="border-l-2 border-indigo-300 pl-4"><div className="flex flex-wrap items-center gap-2"><strong>Revision {revision.revisionNumber}</strong><span className="rounded-full bg-slate-100 px-2 py-0.5 text-xs">{revision.actionType.replaceAll('_', ' ')}</span><span className="text-xs text-slate-500">{new Date(revision.createdAt).toLocaleString()}</span></div><p className="text-sm">{revision.createdByName} · {revision.createdByRole.replaceAll('_', ' ')}</p>{revision.reasonNote && <p className="mt-1 text-sm text-slate-600">Reason: {revision.reasonNote}</p>}{revision.changes?.length > 0 && <div className="mt-2 space-y-1">{revision.changes.map((change) => <p key={change.id} className="rounded-lg bg-slate-50 px-3 py-2 text-sm dark:bg-slate-800"><strong>{change.studentName}</strong> · {change.previousStatus || 'Not marked'} → {change.newStatus}{change.previousRemark !== change.newRemark ? ` · Remark: ${change.previousRemark || '—'} → ${change.newRemark || '—'}` : ''}</p>)}</div>}</div>)}</div> : <p className="text-sm text-slate-500">Draft activity is audited. Immutable revisions appear after submission.</p>}</CardContent></Card>}
  </div></DashboardLayout>;
}
