import React, { useEffect, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import toast from 'react-hot-toast';
import { Save, Settings } from 'lucide-react';
import DashboardLayout from '../../../layouts/DashboardLayout';
import { authService } from '../../../services/authService';
import { analyticsApi } from '../api/analyticsApi';
import { Button } from '../../../components/ui/button';
import { AnalyticsError, AnalyticsLoading } from '../components/AnalyticsState';

const academic = [['examWeight', 'Exam performance'], ['chapterQuizWeight', 'Chapter and quiz'], ['attendanceWeight', 'Attendance'], ['homeworkWeight', 'Homework'], ['teacherEvaluationWeight', 'Teacher evaluation'], ['studentFeedbackWeight', 'Student feedback'], ['resourceEngagementWeight', 'Resource engagement']];
const chapter = [['chapterAssessmentWeight', 'Assessment'], ['chapterHomeworkWeight', 'Homework'], ['chapterTeacherWeight', 'Teacher evaluation'], ['chapterFeedbackWeight', 'Student feedback'], ['chapterAttendanceWeight', 'Attendance'], ['chapterResourceWeight', 'Resource engagement']];

export default function AnalyticsConfigurationPage() {
  const user = authService.getCurrentUser(); const client = useQueryClient(); const [form, setForm] = useState({});
  const query = useQuery({ queryKey: ['analytics', 'configuration'], queryFn: analyticsApi.configuration });
  const rulesQuery = useQuery({ queryKey: ['analytics', 'risk-rules'], queryFn: analyticsApi.riskRules });
  useEffect(() => { if (query.data) setForm(query.data); }, [query.data]);
  const mutation = useMutation({ mutationFn: analyticsApi.updateConfiguration, onSuccess: () => { toast.success('Analytics configuration saved'); client.invalidateQueries({ queryKey: ['analytics'] }); }, onError: (error) => toast.error(error.response?.data?.message || 'Configuration could not be saved') });
  const ruleMutation = useMutation({ mutationFn: ({ id, payload }) => analyticsApi.updateRiskRule(id, payload), onSuccess: () => { toast.success('Risk rule saved'); client.invalidateQueries({ queryKey: ['analytics', 'risk-rules'] }); client.invalidateQueries({ queryKey: ['analytics', 'student'] }); }, onError: (error) => toast.error(error.response?.data?.message || 'Risk rule could not be saved') });
  if (query.isLoading) return <DashboardLayout role={user?.role}><AnalyticsLoading /></DashboardLayout>;
  if (query.isError) return <DashboardLayout role={user?.role}><AnalyticsError error={query.error} retry={query.refetch} /></DashboardLayout>;
  const section = (title, rows) => <div className="rounded-2xl border bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><div className="mb-4 flex items-center justify-between"><h2 className="font-bold">{title}</h2><span className="text-sm font-bold">{rows.reduce((sum, [key]) => sum + Number(form[key] || 0), 0)}%</span></div><div className="grid gap-4 sm:grid-cols-2">{rows.map(([key, title]) => <label key={key} className="text-sm font-medium">{title}<div className="mt-1 flex items-center gap-2"><input type="number" min="0" max="100" value={form[key] ?? ''} onChange={(event) => setForm((old) => ({ ...old, [key]: Number(event.target.value) }))} className="h-10 w-full rounded-xl border bg-transparent px-3 dark:border-slate-700" /><span className="text-slate-500">%</span></div></label>)}</div></div>;
  return <DashboardLayout role={user?.role}><div className="space-y-5"><header><p className="flex items-center gap-2 text-xs font-bold uppercase tracking-widest text-indigo-600"><Settings size={15} /> Academic intelligence</p><h1 className="mt-1 text-2xl font-bold">Analytics configuration</h1><p className="text-sm text-slate-500">Weights must total 100 in each group. Changes create a new formula version and an audit entry.</p></header>{section('Overall academic health weights', academic)}{section('Chapter health weights', chapter)}<div className="grid gap-4 rounded-2xl border bg-white p-5 dark:border-slate-800 dark:bg-slate-900 sm:grid-cols-2 xl:grid-cols-5">{[['minimumAttendanceTarget', 'Attendance target'], ['minimumHomeworkTarget', 'Homework target'], ['minimumChapterTarget', 'Chapter target'], ['lowRiskThreshold', 'Low-risk score'], ['mediumRiskThreshold', 'Medium-risk score']].map(([key, title]) => <label key={key} className="text-sm font-medium">{title}<input type="number" min="0" max="100" value={form[key] ?? ''} onChange={(event) => setForm((old) => ({ ...old, [key]: Number(event.target.value) }))} className="mt-1 h-10 w-full rounded-xl border bg-transparent px-3 dark:border-slate-700" /></label>)}</div><div className="flex justify-end"><Button variant="primary" leftIcon={Save} loading={mutation.isPending} onClick={() => mutation.mutate({ ...form, reason: 'Analytics configuration updated from settings' })}>Save configuration</Button></div>
    <div className="overflow-hidden rounded-2xl border bg-white dark:border-slate-800 dark:bg-slate-900"><div className="border-b px-5 py-4 dark:border-slate-800"><h2 className="font-bold">Explainable risk rules</h2><p className="text-xs text-slate-500">Rules can be disabled or adjusted without hiding their explanation.</p></div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500 dark:bg-slate-950"><tr><th className="px-4 py-3">Rule</th><th className="px-4 py-3">Severity</th><th className="px-4 py-3">Threshold</th><th className="px-4 py-3">Enabled</th><th className="px-4 py-3">Action</th></tr></thead><tbody>{(rulesQuery.data || []).map((rule) => <RiskRuleRow key={rule.id} rule={rule} saving={ruleMutation.isPending} onSave={(payload) => ruleMutation.mutate({ id: rule.id, payload })} />)}</tbody></table></div>{!rulesQuery.data?.length && <p className="p-6 text-center text-sm text-slate-500">Run the analytics seed to install the default risk rules.</p>}</div>
  </div></DashboardLayout>;
}

function RiskRuleRow({ rule, saving, onSave }) {
  const [value, setValue] = useState(rule);
  return <tr className="border-t dark:border-slate-800"><td className="px-4 py-3"><p className="font-semibold">{rule.title}</p><p className="text-xs text-slate-500">{rule.code}</p></td><td className="px-4"><select className="h-9 rounded-lg border bg-transparent px-2 dark:border-slate-700" value={value.severity} onChange={(event) => setValue((old) => ({ ...old, severity: event.target.value }))}>{['LOW', 'MEDIUM', 'HIGH', 'CRITICAL'].map((item) => <option key={item}>{item}</option>)}</select></td><td className="px-4"><input aria-label={`${rule.title} threshold`} type="number" className="h-9 w-24 rounded-lg border bg-transparent px-2 dark:border-slate-700" value={value.threshold ?? ''} onChange={(event) => setValue((old) => ({ ...old, threshold: event.target.value === '' ? null : Number(event.target.value) }))} /></td><td className="px-4"><input type="checkbox" checked={value.isEnabled} onChange={(event) => setValue((old) => ({ ...old, isEnabled: event.target.checked }))} /></td><td className="px-4"><Button size="sm" variant="outline" loading={saving} onClick={() => onSave({ ...value, reason: 'Risk rule updated from analytics settings' })}>Save</Button></td></tr>;
}
