import React, { useMemo, useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { Link, useParams } from 'react-router-dom';
import { ArrowRight, Download, Printer, Users } from 'lucide-react';
import DashboardLayout from '../../../layouts/DashboardLayout';
import { authService } from '../../../services/authService';
import { analyticsApi } from '../api/analyticsApi';
import { AnalyticsError, AnalyticsLoading } from '../components/AnalyticsState';
import { Badge } from '../../../components/ui/badge';
import { label, riskVariant } from '../constants/analyticsStyles';
import { saveReport } from '../api/analyticsApi';
import { Button } from '../../../components/ui/button';

export default function ClassAnalyticsPage({ sectionMode = false }) {
  const user = authService.getCurrentUser(); const params = useParams(); const id = sectionMode ? params.sectionId : params.classId;
  const [filters, setFilters] = useState({ search: '', risk: '', sort: 'name' });
  const query = useQuery({ queryKey: ['analytics', sectionMode ? 'section' : 'class', id], queryFn: () => sectionMode ? analyticsApi.sectionOverview(id, {}) : analyticsApi.classOverview(id, {}), enabled: Boolean(id) });
  const rows = useMemo(() => (query.data?.items || []).filter((row) => (!filters.risk || row.riskLevel === filters.risk) && (!filters.search || row.name.toLowerCase().includes(filters.search.toLowerCase()) || row.admissionNo?.toLowerCase().includes(filters.search.toLowerCase()))).sort((a, b) => {
    if (filters.sort === 'health') return (b.academicHealth ?? -1) - (a.academicHealth ?? -1);
    if (filters.sort === 'attendance') return (b.attendance ?? -1) - (a.attendance ?? -1);
    if (filters.sort === 'risk') return ['CRITICAL', 'HIGH', 'MEDIUM', 'LOW', 'INSUFFICIENT_DATA'].indexOf(a.riskLevel) - ['CRITICAL', 'HIGH', 'MEDIUM', 'LOW', 'INSUFFICIENT_DATA'].indexOf(b.riskLevel);
    return a.name.localeCompare(b.name);
  }), [query.data?.items, filters]);
  if (query.isLoading) return <DashboardLayout role={user?.role}><AnalyticsLoading /></DashboardLayout>;
  if (query.isError) return <DashboardLayout role={user?.role}><AnalyticsError error={query.error} retry={query.refetch} /></DashboardLayout>;
  const data = query.data;
  const download = async (format) => saveReport(await (sectionMode ? analyticsApi.sectionReport(id, format) : analyticsApi.classReport(id, format)), `${sectionMode ? 'section' : 'class'}-academic-analytics.${format}`);
  return <DashboardLayout role={user?.role}><div className="space-y-5"><header className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-widest text-indigo-600">Class intelligence</p><h1 className="text-2xl font-bold">{data.class.name}{data.section ? ` · Section ${data.section.name}` : ''}</h1><p className="text-sm text-slate-500">{data.studentCount} students · {data.academicSession?.name || 'Current session'} · syllabus {data.syllabusCompletion === null ? 'not available' : `${Math.round(data.syllabusCompletion)}% complete`}</p></div><div className="flex gap-2 print:hidden"><Button size="sm" variant="outline" leftIcon={Download} onClick={() => download('pdf')}>PDF</Button><Button size="sm" variant="outline" onClick={() => download('csv')}>CSV</Button><Button size="sm" variant="outline" leftIcon={Printer} onClick={() => window.print()}>Print</Button></div></header>
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{[['Academic health', data.averages.academicHealth], ['Attendance', data.averages.attendance], ['Homework', data.averages.homework], ['Assessments', data.averages.examAverage], ['Data coverage', data.averages.dataCoverage]].map(([title, value]) => <div key={title} className="rounded-2xl border bg-white p-4 dark:border-slate-800 dark:bg-slate-900"><p className="text-xs uppercase tracking-wider text-slate-500">{title}</p><p className="mt-2 text-2xl font-bold">{value === null ? '—' : `${Math.round(value)}%`}</p></div>)}</div>
    <div className="flex flex-wrap gap-3 rounded-2xl border bg-white p-4 dark:border-slate-800 dark:bg-slate-900 print:hidden"><input aria-label="Search students" className="h-10 min-w-56 flex-1 rounded-xl border bg-transparent px-3 dark:border-slate-700" placeholder="Search student or admission number" value={filters.search} onChange={(event) => setFilters((old) => ({ ...old, search: event.target.value }))} /><select aria-label="Filter risk" className="h-10 rounded-xl border bg-transparent px-3 dark:border-slate-700" value={filters.risk} onChange={(event) => setFilters((old) => ({ ...old, risk: event.target.value }))}><option value="">All risk levels</option>{['CRITICAL', 'HIGH', 'MEDIUM', 'LOW', 'INSUFFICIENT_DATA'].map((value) => <option key={value}>{value}</option>)}</select><select aria-label="Sort students" className="h-10 rounded-xl border bg-transparent px-3 dark:border-slate-700" value={filters.sort} onChange={(event) => setFilters((old) => ({ ...old, sort: event.target.value }))}><option value="name">Sort by name</option><option value="health">Academic health</option><option value="attendance">Attendance</option><option value="risk">Risk level</option></select></div>
    <div className="overflow-hidden rounded-2xl border bg-white dark:border-slate-800 dark:bg-slate-900"><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="sticky top-0 bg-slate-50 text-xs uppercase text-slate-500 dark:bg-slate-950"><tr>{['Student', 'Attendance', 'Homework', 'Academic health', 'Exam average', 'Weak chapters', 'Risk', 'Trend', 'Action'].map((title) => <th key={title} className="px-4 py-3">{title}</th>)}</tr></thead><tbody>{rows.map((row) => <tr key={row.id} className="border-t dark:border-slate-800"><td className="px-4 py-4"><p className="flex items-center gap-2 font-semibold"><Users size={15} />{row.name}</p><p className="text-xs text-slate-500">{row.admissionNo || '—'}</p></td><td className="px-4">{row.attendance === null ? '—' : `${row.attendance}%`}</td><td className="px-4">{row.homework === null ? '—' : `${row.homework}%`}</td><td className="px-4">{row.academicHealth === null ? '—' : `${row.academicHealth}%`}</td><td className="px-4">{row.examAverage === null ? '—' : `${row.examAverage}%`}</td><td className="px-4">{row.weakChapters ?? '—'}</td><td className="px-4"><Badge variant={riskVariant[row.riskLevel]}>{label(row.riskLevel)}</Badge></td><td className="px-4">{label(row.trend)}</td><td className="px-4"><Link to={`/analytics/students/${row.id}`} className="inline-flex items-center gap-1 font-semibold text-indigo-600">Review <ArrowRight size={14} /></Link></td></tr>)}</tbody></table></div>{!rows.length && <p className="p-8 text-center text-sm text-slate-500">No students match these filters.</p>}</div>
  </div></DashboardLayout>;
}
