import React from 'react';
import { useQuery } from '@tanstack/react-query';
import { Activity, BookOpenCheck, CalendarCheck, ClipboardCheck, Database, Download, GraduationCap, Printer, Users } from 'lucide-react';
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import DashboardLayout from '../../../layouts/DashboardLayout';
import { authService } from '../../../services/authService';
import { analyticsApi } from '../api/analyticsApi';
import { AnalyticsError, AnalyticsLoading } from '../components/AnalyticsState';
import AnalyticsDataCoverage from '../components/AnalyticsDataCoverage';
import { Badge } from '../../../components/ui/badge';
import { label, riskVariant } from '../constants/analyticsStyles';
import { saveReport } from '../api/analyticsApi';
import { Button } from '../../../components/ui/button';

const Kpi = ({ icon: Icon, title, value, detail }) => <div className="rounded-2xl border bg-white p-4 dark:border-slate-800 dark:bg-slate-900"><div className="flex items-start justify-between"><div><p className="text-xs uppercase tracking-wider text-slate-500">{title}</p><p className="mt-2 text-2xl font-bold">{value ?? '—'}</p><p className="mt-1 text-xs text-slate-500">{detail}</p></div><Icon className="text-indigo-600" size={18} /></div></div>;

export default function SchoolAnalyticsPage() {
  const user = authService.getCurrentUser();
  const query = useQuery({ queryKey: ['analytics', 'school'], queryFn: () => analyticsApi.schoolOverview({}), staleTime: 60_000 });
  if (query.isLoading) return <DashboardLayout role={user?.role}><AnalyticsLoading /></DashboardLayout>;
  if (query.isError) return <DashboardLayout role={user?.role}><AnalyticsError error={query.error} retry={query.refetch} /></DashboardLayout>;
  const data = query.data;
  return <DashboardLayout role={user?.role}><div className="space-y-5"><header className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-widest text-indigo-600">Academic intelligence</p><h1 className="text-2xl font-bold">School analytics</h1><p className="text-sm text-slate-500">{data.academicSession?.name || 'Current session'} · finalized academic scores use the latest immutable student snapshot.</p></div><div className="flex gap-2 print:hidden"><Button size="sm" variant="outline" leftIcon={Download} onClick={async () => saveReport(await analyticsApi.schoolReport('pdf'), 'school-academic-analytics.pdf')}>PDF</Button><Button size="sm" variant="outline" onClick={async () => saveReport(await analyticsApi.schoolReport('csv'), 'school-academic-analytics.csv')}>CSV</Button><Button size="sm" variant="outline" leftIcon={Printer} onClick={() => window.print()}>Print</Button></div></header>
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-7"><Kpi icon={Users} title="Students" value={data.studentCount} detail="Active students" /><Kpi icon={Activity} title="Academic health" value={data.averages.academicHealth === null ? null : `${Math.round(data.averages.academicHealth)}%`} detail="From finalized snapshots" /><Kpi icon={CalendarCheck} title="Attendance" value={data.averages.attendance === null ? null : `${Math.round(data.averages.attendance)}%`} detail="Current session" /><Kpi icon={ClipboardCheck} title="Homework" value={data.averages.homework === null ? null : `${Math.round(data.averages.homework)}%`} detail="Snapshot completion" /><Kpi icon={GraduationCap} title="Assessments" value={data.averages.examAverage === null ? null : `${Math.round(data.averages.examAverage)}%`} detail="Recorded assessments" /><Kpi icon={BookOpenCheck} title="Syllabus completion" value={data.syllabusCompletion === null ? null : `${Math.round(data.syllabusCompletion)}%`} detail="Recorded chapter progress" /><Kpi icon={Database} title="Evaluation records" value={data.teacherEvaluationCount} detail="Teacher evaluations" /></div>
    <div className="grid gap-4 xl:grid-cols-[1.5fr_1fr]"><div className="rounded-2xl border bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><h2 className="font-bold">Academic health by class</h2><p className="text-xs text-slate-500">Text table follows the chart for accessibility.</p><div className="mt-4 h-64"><ResponsiveContainer width="100%" height="100%"><BarChart data={data.classAnalytics}><CartesianGrid strokeDasharray="3 3" vertical={false} /><XAxis dataKey="className" /><YAxis domain={[0, 100]} /><Tooltip /><Bar dataKey="academicHealth" name="Academic health" fill="#4f46e5" radius={[5, 5, 0, 0]} /></BarChart></ResponsiveContainer></div><table className="mt-3 w-full text-left text-xs"><thead><tr><th>Class</th><th>Students</th><th>Health</th><th>Attendance</th></tr></thead><tbody>{data.classAnalytics.map((row) => <tr key={row.className} className="border-t dark:border-slate-800"><td className="py-2 font-semibold">{row.className}</td><td>{row.studentCount}</td><td>{row.academicHealth === null ? '—' : `${Math.round(row.academicHealth)}%`}</td><td>{row.attendance === null ? '—' : `${Math.round(row.attendance)}%`}</td></tr>)}</tbody></table></div>
      <div className="space-y-4"><div className="rounded-2xl border bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><h2 className="font-bold">Risk distribution</h2><div className="mt-4 space-y-2">{data.riskDistribution.map((row) => <div key={row.riskLevel} className="flex items-center justify-between rounded-xl border p-3 dark:border-slate-800"><Badge variant={riskVariant[row.riskLevel]}>{label(row.riskLevel)}</Badge><strong>{row.count}</strong></div>)}</div></div><div className="rounded-2xl border bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><h2 className="mb-3 font-bold">Analytics reliability</h2><AnalyticsDataCoverage value={data.averages.dataCoverage || 0} /></div></div>
    </div>
    <div className="grid gap-4 lg:grid-cols-2"><div className="rounded-2xl border bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><h2 className="font-bold">Subject performance</h2><p className="text-xs text-slate-500">Aggregated from each student’s latest immutable snapshot.</p><div className="mt-3 overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr><th className="py-2">Subject</th><th>Students</th><th>Score</th></tr></thead><tbody>{data.subjectAnalytics.map((row) => <tr key={row.subjectId} className="border-t dark:border-slate-800"><td className="py-2 font-semibold">{row.subjectName}</td><td>{row.students}</td><td>{row.score === null ? '—' : `${Math.round(row.score)}%`}</td></tr>)}</tbody></table>{!data.subjectAnalytics.length && <p className="py-5 text-sm text-slate-500">Create student snapshots to populate subject analytics.</p>}</div></div>
      <div className="rounded-2xl border bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><h2 className="font-bold">Chapters needing attention</h2><p className="text-xs text-slate-500">Lowest recorded chapter scores; this is a review signal, not a diagnosis.</p><div className="mt-3 overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr><th className="py-2">Chapter</th><th>Subject</th><th>Score</th></tr></thead><tbody>{data.difficultChapters.map((row) => <tr key={row.chapterId} className="border-t dark:border-slate-800"><td className="py-2 font-semibold">{row.chapterTitle}</td><td>{row.subjectName || '—'}</td><td>{Math.round(row.score)}%</td></tr>)}</tbody></table>{!data.difficultChapters.length && <p className="py-5 text-sm text-slate-500">No chapter evidence is available in finalized snapshots.</p>}</div></div>
    </div>
    <div className="grid gap-4 md:grid-cols-2"><div className="rounded-2xl border bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><h2 className="font-bold">Intervention workflow</h2><div className="mt-3 flex flex-wrap gap-2">{data.interventionStatus.map((row) => <Badge key={row.status} variant="outline">{label(row.status)}: {row.count}</Badge>)}{!data.interventionStatus.length && <p className="text-sm text-slate-500">No interventions recorded.</p>}</div></div><div className="rounded-2xl border bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><h2 className="font-bold">Resource activity</h2><div className="mt-3 flex flex-wrap gap-2">{data.resourceUsage.map((row) => <Badge key={row.type} variant="outline">{label(row.type)}: {row.events}</Badge>)}{!data.resourceUsage.length && <p className="text-sm text-slate-500">No resource activity recorded.</p>}</div></div></div>
  </div></DashboardLayout>;
}
